### PR TITLE
Adding token validation for alfred /deltas and /documents endpoints

### PR DESCRIPTION
**Pull request by sharmakhushboo**
This PR includes the following changes:
1. Sending storage token from driver to alfred's /deltas and /documents apis

This changes for 'Storage token validation in alfred' will be pushed as a separate PR.

Also, this does not include the work to unify the token format across r11s. That work will be taken up later.

### CODE REVIEW

**Review by tanviraumi — COMMENTED** [review]
This needs multiple PRs. We need to update the client first and have them send tokens. Once the packages are published and we have waited for a few days, we can enforce in the server.

Alternatively, you can check these together but make sure not to enable it in the server until clients are up to date.

**Comment by sharmakhushboo** [comment]
> This needs multiple PRs. We need to update the client first and have them send tokens. Once the packages are published and we have waited for a few days, we can enforce in the server.
> 
> Alternatively, you can check these together but make sure not to enable it in the server until clients are up to date.



> This needs multiple PRs. We need to update the client first and have them send tokens. Once the packages are published and we have waited for a few days, we can enforce in the server.
> 
> Alternatively, you can check these together but make sure not to enable it in the server until clients are up to date.

Yes, We will update this in r11s

> This needs multiple PRs. We need to update the client first and have them send tokens. Once the packages are published and we have waited for a few days, we can enforce in the server.
> 
> Alternatively, you can check these together but make sure not to enable it in the server until clients are up to date.

Yes, my plan was to do the latter. But turns out that there are a lot of PRs for server side, and this change might block their deployments. So I'll split this PR into two.

**Review by tanviraumi — APPROVED** [review]

**Pull request merged**
