### PR TITLE
[v2int/7.4] Fix bundle size

### PR DESCRIPTION
**Pull request by alexvy86**
## Description

Reverts "build(protocol-definitions): Produce correct types in ESM bui…ld (#18771)".

This reverts commit cbaf3db34ab053bc1d7c3309c472553f44d62f5d, which might be the culprit of the increase in bundle size.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

### CODE REVIEW

**Review by tyler-cai-microsoft — APPROVED** [review]

**Comment by alexvy86** [comment]
I'll hold merging this, since @jason-ha is working on an alternative. Good to see it pass CI though.

**Comment by alexvy86** [comment]
Confirming the 90kb of bundle size improvement is also great 😄 
image

**Comment by tylerbutler** [comment]
@alexvy86 protocol-defs is an independent package and isn't released from the 7.4 client release branch. If you need to release a new version of protocol-defs, make the changes in main and release it, then you can update the deps on release branches as needed.

However, also note that using a different protocol-defs version will require the same change in server, and then the server deps in client also have to be updated.

**Comment by jason-ha** [comment]
Replaced by #19239

**Pull request closed without merging**
