### PR TITLE
build: Update dependencies on `tinylicious`

### PR DESCRIPTION
**Pull request by Josmithr**

### CODE REVIEW

**Review by ChumpChief — APPROVED** [review]

**Comment by anthony-murphy** [comment]
@Josmithr and @ChumpChief  i don't think this change is safe:
https://unpkg.com/tinylicious@0.4.89251/package.json
https://unpkg.com/tinylicious@0.4.94771/package.json

this bump of tinylicious is not semver compatible with the previous version, there is a major version bump of the sever packages. I don't know what the impact will be, but it could cause problems

**Comment by anthony-murphy** [comment]
I think this will cause dependency issue for int package consumers of client

**Comment by Josmithr** [comment]
> I think this will cause dependency issue for int package consumers of client

Oof, okay. I'll get this reverted out.

Curious though, how is tinylicious versioned? In theory it should have received a minor version bump if we expected updating it to break consumers. Do we need to updated any guidance for our versioning of tinylicious?

**Comment by anthony-murphy** [comment]
short answer is it is not. there is work to get this sorted out, but its so far unscheduled

**Pull request merged**
