### PR TITLE
[bump] common-utils: 2.0.0 => 3.0.0 (major)

### PR DESCRIPTION
**Pull request by tylerbutler**
Bumps common-utils from 2.0.0 to 3.0.0.

Also updates the common-definitions and eslint config dependencies to the latest releases.

### CODE REVIEW

**Comment by curtisman** [comment]
Should we do bump in 'main'?  Some partners has direct dependencies on `common-utils`, and they will have to bump their references for `common-utils` to 2.0 to avoid package duplication?

**Comment by tylerbutler** [comment]
> Should we do bump in 'main'?  Some partners has direct dependencies on `common-utils`, and they will have to bump their references for `common-utils` to 2.0 to avoid package duplication?  I don't know if that is going to be easy or not, but it would cause more work for a minor bump with our partners.

Independent packages are all worked on in main. Partners shouldn't be affected until we integrate the 2.0 common-utils into client.

I haven't released common-utils 1.2 that contains all the deprecations. I was going to wait until 2.0 is also ready to release and release them both at the same time. But I could also bump to 2.0 with the deprecations, and then release 3.0 with these removals.

**Comment by tylerbutler** [comment]
> I haven't released common-utils 1.2 that contains all the deprecations. I was going to wait until 2.0 is also ready to release and release them both at the same time. But I could also bump to 2.0 with the deprecations, and then release 3.0 with these removals.

For maximum safety, I'll bump common-utils to 2.0 and release it with the deprecations. That will mean this PR should bump to 3.0, so marking as a draft until the other steps are done.

**Comment by curtisman** [comment]
Sorry,  I mistaken that we are bumping the dependencies of common-utils.  Disregard my comment.

**Comment by tylerbutler** [comment]
> For maximum safety, I'll bump common-utils to 2.0 and release it with the deprecations. That will mean this PR should bump to 3.0, so marking as a draft until the other steps are done.

This will ensure that partners with a dependency on `^1.1.0` don't automatically pick up a minor release with deprecations.

**Review by zhenmichael — APPROVED** [review]

**Pull request merged**
