### PR TITLE
improvement(tree): explicit internal paths

### PR DESCRIPTION
**Pull request by jason-ha**
explicit paths to support moduleResolution node16+ with tsc

import/no-internal-modules fully disabled (lots of internal module paths already that weren't caught)

### CODE REVIEW

**Review by tylerbutler — APPROVED** [review]
Changes look good to me. The CI failure can be resolved by building fluid-framework locally and checking in the result.

**Comment by anthony-murphy** [comment]
i don't think you want to do this. it will remove all strong typing the from js imports.

**Comment by jason-ha** [comment]
> i don't think you want to do this. it will remove all strong typing the from js imports.

Eh? Please explain. What magic do we have going on? (Explicit paths are just explicit paths of what they should resolve to using common `node` rules.)

**Comment by tylerbutler** [comment]
> > i don't think you want to do this. it will remove all strong typing the from js imports.
> 
> Eh? Please explain. What magic do we have going on? (Explicit paths are just explicit paths of what they should resolve to using common `node` rules.)

[Relevant section](https://www.typescriptlang.org/docs/handbook/modules/reference.html#file-extension-substitution) from the TypeScript docs:

> For any module specifier that would, according to the moduleResolution algorithm specified, trigger a lookup of a JavaScript file in the runtime or bundler, TypeScript will first try to find a TypeScript implementation file or type declaration file with the same name and analagous file extension.
> ...
> Note that this behavior is independent of the actual module specifier written in the import. This means that TypeScript can resolve to a .ts or .d.ts file even if the module specifier explicitly uses a .js file extension:
>
> ```ts
> import x from "./mod.js";
> // Runtime lookup: "./mod.js"
> // TypeScript lookup #1: "./mod.ts"
> // TypeScript lookup #2: "./mod.d.ts"
> // TypeScript lookup #3: "./mod.js"
> ```

**Pull request merged**
