### PR TITLE
Update React to 17

### PR DESCRIPTION
**Pull request by CraigMacomber**
## Description

Update from React 16 to 17.

## Reviewer Guidance

Suggestions on what needs testing or how this could break consumers would be great.

Feedback on if the change to BREAKING.md is correct and sufficient would also be helpful.

## Does this introduce a breaking change?

> If this introduces a breaking change, please describe the impact and migration path for existing applications below.
> See [Breaking-vs-Non-breaking-Changes](https://github.com/microsoft/FluidFramework/wiki/Breaking-vs-Non-breaking-Changes) for details.
> If there are no breaking changes, delete this section.

This mainly impacts examples, but the following published packages use React as well:

1. @fluidframework/view-adapters
2. @fluid-tools/webpack-fluid-loader
3. @fluid-experimental/react-inputs
4. @fluid-experimental/property-inspector-table

The only known user of any of these packages outside this repo is Autodesk using Property-Inspector-Table: They contributed some fixes to it, and have given the ok to go ahead with this change.

If you know of anyone else who may be impacted, please let me know.

## Other information or known dependencies

Internal work item: https://dev.azure.com/fluidframework/internal/_workitems/edit/1101

### CODE REVIEW

**Comment by CraigMacomber** [comment]
I'm going to manually test a few more examples before I'm ready to merge this, but all the ones I have tried so far seem to be working fine.

**Comment by CraigMacomber** [comment]
I have manually tested 10 of the impacted examples comparing the before and after and all of them seem fine. All tests are passing. I think this change should be ok.

**Comment by ssimic2** [comment]
Few notes:

https://github.com/microsoft/FluidFramework/wiki/Breaking-vs-Non-breaking-Changes#consuming-major-changes-from-other-ff-packages should be a definitive guideline on what breaking changes are. There, we call out that consuming new major FF releases should be considered a breaking change, and we should probably expand that to include new major releases of ANY package (same reasoning as with FF packages - semantics etc). That would resonate well with 3rd tenet listed there: stay on the safe side. Generally speaking, we should be free to make (reasonable) breaking changes on any major release as long as we communicate them clearly. And you did so in Breaking.

Normally I would encourage you to explore communicating better patterns available with newer library version, but I remember 17 being more of a "stepping stone" : https://reactjs.org/blog/2020/08/10/react-v17-rc.html. I guess that makes this upgrade safer.

As for testing, I would leave to the package/library consuming the React to ensure they have valid unit tests. React is a view-only library so jest unit tests should be sufficient. I see that some of the packages either have them, or they used them in limited way (observing functional behavior only). Jest provides snapshots as well, fairly cheap way to ensure presentational aspect of react component has not changed. Anyways, it sounds like you did some manual testing, that's probably the best option you have on hand for this PR.

I have not reviewed property-inspector-table, but it looks like you have that covered.

**Review by ssimic2 — APPROVED** [review]

**Comment by CraigMacomber** [comment]
> As for testing, I would leave to the package/library consuming the React to ensure they have valid unit tests. React is a view-only library so jest unit tests should be sufficient. I see that some of the packages either have them, or they used them in limited way (observing functional behavior only). Jest provides snapshots as well, fairly cheap way to ensure presentational aspect of react component has not changed. Anyways, it sounds like you did some manual testing, that's probably the best option you have on hand for this PR.

Several of our examples do not have any tests, and I have broken them despite CI passing when updating dependencies in the past (ex: webpack), so I like to do at least some manual testing when working on the examples.

**Comment by ssimic2** [comment]
> > As for testing, I would leave to the package/library consuming the React to ensure they have valid unit tests. React is a view-only library so jest unit tests should be sufficient. I see that some of the packages either have them, or they used them in limited way (observing functional behavior only). Jest provides snapshots as well, fairly cheap way to ensure presentational aspect of react component has not changed. Anyways, it sounds like you did some manual testing, that's probably the best option you have on hand for this PR.
> 
> Several of our examples do not have any tests, and I have broken them despite CI passing when updating dependencies in the past (ex: webpack), so I like to do at least some manual testing when working on the examples.

I meant to write "I see that some of the packages either do NOT have them, or they used them in limited way (observing functional behavior only)"

**Pull request merged**
