### PR TITLE
build: Bundle packages from which API members are re-exported in azure packages to their roll-ups

### PR DESCRIPTION
**Pull request by Josmithr**
Also add missing API re-exports for completeness.

This PR utilizes API-Extractor's [bundledpackages](https://api-extractor.com/pages/configs/api-extractor_json/#bundledpackages) feature to directly include re-exported members from the specified packages in the type rollups and API reports, as well as in the generated documentation for the package. This allows us to get a more complete look at the API surface of each of the packages, and will ensure that generated documentation is published for everything exposed through the package's entrypoint.

### CODE REVIEW

**Comment by Josmithr** [comment]
Putting this up as a draft for now to get opinions. Personally, I think this makes it easier to reason about the actual API surface of the packages, rather than just the local (non-re-exported) portions.

Additionally, it makes breaking changes the cross package boundaries a bit more evident. If package b is re-exporting a member from package a, it will now be more clear that package b's API surface was broken when breaking changes are made in a.

**Comment by curtisman** [comment]
I loved it.   A follow up problem to be solve is how to organize those re-exports, as they are all mix together and no categorization of the APIs.  I believe this option might have been enabled before @tylerbutler?

**Comment by tylerbutler** [comment]
Nice! I did not know about this api-extractor feature! How does it change the JSON output? Are the bundled items included in the JSON?

**Comment by tylerbutler** [comment]
> It appears that (at least) our api-documenter fork does not support the `canonicalReference` property links. So this change breaks our current API docs build. If we like this pattern, we will need to schedule some work to add support.

@Josmithr It might be worth just upgrading the related dependencies in our custom fork and see if that resolves it.

**Comment by Josmithr** [comment]
> ```json
>  "@fluidframework/azure-service-utils
> ```

Actually, it looks like I misinterpreted what was going on. I was able to get a local build of the docs running correctly. And the end result is pretty nice. I was able to remove some of our custom `memberCombineInstructions` entries, and we still get the docs we want in the output via the bundle feature.

**Comment by Josmithr** [comment]
> > It appears that (at least) our api-documenter fork does not support the `canonicalReference` property links. So this change breaks our current API docs build. If we like this pattern, we will need to schedule some work to add support.
> 
> @Josmithr It might be worth just upgrading the related dependencies in our custom fork and see if that resolves it.

Actually, it looks like I misinterpreted what was going on. I was able to get a local build of the docs running correctly. And the end result is pretty nice. I was able to remove some of our custom `memberCombineInstructions` entries, and we still get the docs we want in the output via the bundle feature.

**Comment by Josmithr** [comment]
The failing build has revealed another potential issue with this scheme. Namely, if API-Extractor can't locally resolve links, etc. expressed in packages whose members are being re-exported, then it will fail in the local package. Since package-wise upstream fixes won't be seen immediately (without bumping package versions), we can get into an unfortunate state.

See the change I made in tokens.ts for an example of where this goes wrong. Since azure-client doesn't re-export `RouterliciousDocumentServiceFactory`, the tsdoc link in ITokenProvider (which is re-exported by azure-client) fails to resolve.


If we could make upstream changes immediately (as I attempted without realizing the change crossed release-group boundaries), then this might not be a substantial issue. But with our current release process, this is problematic.

**Pull request closed without merging**
