### PR TITLE
Fix build error due to incorrect file formatting

### PR DESCRIPTION
**Pull request by tylerbutler**
"Prettier mad. Prettier annnngry!"

### CODE REVIEW

**Comment by tylerbutler** [comment]
@Abe27342 FYI.

**Review by DLehenbauer — APPROVED** [review]
Thanks, Tyler!

**Comment by Abe27342** [comment]
Thanks!

Looks like this mistake was in the original tree DDS addition. Is it understood how this made it past the PR gating? I can look into it if not.

**Comment by tylerbutler** [comment]
It's strange... Maybe it was introduced in a merge through the GitHub UI? I checked the lint logs you linked and the task did indeed run and pass. 😕 

One idea is to check the exact commit that was checked out in that CI build and compare it to the PR commits. I don't have time to do that at the moment but I can look into it next week if you don't get to it before then.

**Comment by Abe27342** [comment]
Oh, hm. Looks like it has to do with some of the collaboration between Daniel and I. Specifically the [commit log](https://github.com/microsoft/FluidFramework/pull/4821/commits) shows some red builds before the one that passes checks.

Disclaimer: my github use up to this point has been primarily recreational, and teams I've worked on have primarily used branching workflows (rather than forks). So could easily be some bad usage on my part, here. Would love to be educated if so :).

Is this just some consequence

**Comment by Abe27342** [comment]
Whew. Nothing extremely odd. Turns out lerna ends up editing those lines in the versioning step (which causes the format check to succeed!).

Given we're going to expect pretty different `package.json`s due to script/tooling differences (and some amount of version misalignment), I think just ignoring package.json for formatting and converting it to 2-space indentation (fluid conventions) is reasonable.

**Comment by Abe27342** [comment]
I opened #4888 to address that.

**Pull request merged**
