### PR TITLE
tools(client+build-tools): update Biome to 1.8.3

### PR DESCRIPTION
**Pull request by jason-ha**
Need 1.8 version to get support from Biome
Changes:
1. Remove production dependency in @fluid-example/bubblebench-shared-tree
2. Update versions to ~1.8.3 (and set config to want ~)
3. Handle deprecations
   a. Replace "javascript.formatter.trailingComma" with "...trailingCommas"
   b. Replace cli argument `--apply` with `--write`
4. Apply formatting updates
5. Add Biome to npm-package-json-script-dep
6. Remove unused `--formatter-enabled=true` from commands
7. Add missing biome devDeps in build-tools

### CODE REVIEW

**Review by Abe27342 — APPROVED** [review]

**Review by anthony-murphy — APPROVED** [review]

**Comment by tylerbutler** [comment]
Can you make sure to include any changes from https://github.com/microsoft/FluidFramework/pull/21483 that aren't in this?

**Comment by tylerbutler** [comment]
Also what "support from Biome" do we need?

**Comment by tylerbutler** [comment]
> Can you make sure to include any changes from #21483 that aren't in this?

In particular, the --formatter-enabled flag is no longer needed and we should use tilde deps instead of caret.

**Review by tylerbutler — CHANGES_REQUESTED** [review]
Please pull in the other changes from https://github.com/microsoft/FluidFramework/pull/21483 before merge.

**Comment by jason-ha** [comment]
> Also what "support from Biome" do we need?
https://github.com/biomejs/biome-vscode/issues/261

Our local post: https://teams.microsoft.com/l/message/19:50292e8934024fc19d6ca2080dd7681e@thread.skype/1720462866165?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9ce27575-2f82-4689-abdb-bcff07e8063b&parentMessageId=1718668863290&teamName=Fluid%20Framework&channelName=Dev&createdTime=1720462866165

**Comment by jason-ha** [comment]
> Please pull in the other changes from #21483 before merge.

I think I got them all now.

**Review by tylerbutler — APPROVED** [review]
Looks good. Thanks for doing this.

**Pull request merged**
