### PR TITLE
Minimize set of loader options considered for stress test matrix

### PR DESCRIPTION
**Pull request by ChumpChief**
This PR removes most of the loader configurations from the stress test, many of which were obsolete/deprecated/had no effect.  Also switches over to the recommended non-deprecated `ILoaderOptions` from container-definitions instead of container-loader.

Since generatePairwiseOptions doesn't generate every combination, eliminating noise from the options matrix seems like generally a good practice.  This makes it more likely we'll get interesting combos with 3+ properties (though in this case we don't really have that many interesting properties left).

A quick survey of their current state in `main`:

```ts
cache: booleanCases, // Loader hasn't supported caching in a while, has no effect
client: [undefined],
provideScopeLoader: booleanCases, // Doesn't actually have any meaningful effect
maxClientLeaveWaitTime: numberCases, // numberCases === [undefined], not sure why we export this really
summarizeProtocolTree: [undefined],
enableOfflineLoad: booleanCases, // Deprecated (in favor of using MC), but can technically still have an effect
enableOfflineSnapshotRefresh: booleanCases, // Has no effect, only controllable via MC
snapshotRefreshTimeoutMs: [undefined, 60 * 5 * 1000 /* 5min */], // Has no effect, only controllable via MC
```

[AB#12911](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/12911)

### CODE REVIEW

**Review by alexvy86 — APPROVED** [review]
Reasoning seems fine to me. But I'd definitely wait for @anthony-murphy or @dannimad's input though, since the experimental options were added pretty recently. If it was an oversight adding them to stress tests because they don't actually have any effect, off with them; but if that was a bug and they should be exercised, we might want a different version of this change.

**Comment by ChumpChief** [comment]
> Reasoning seems fine to me. But I'd definitely wait for @anthony-murphy or @dannimad's input though, since the experimental options were added pretty recently. If it was an oversight adding them to stress tests because they don't actually have any effect, off with them; but if that was a bug and they should be exercised, we might want a different version of this change.

@dannimad Based on my read, these settings would need to be in a new config matrix for `generateConfigurations` rather than `generateLoaderOptions`.  Currently there's no default matrix (only overrides), but you could add one if you want.

**Review by anthony-murphy — CHANGES_REQUESTED** [review]
i don't believe we should not test things that are deprecated. many of our deprecations are false, and are still in active use, so we should continue to test them. When the work is done to actually remove the deprecated thing these will get removed as well.

**Comment by ChumpChief** [comment]
> i don't believe we should not test things that are deprecated. many of our deprecations are false, and are still in active use, so we should continue to test them. When the work is done to actually remove the deprecated thing these will get removed as well.

Of the settings currently under test, `enableOfflineLoad` is the only deprecated one that still actually does anything - this one I left unchanged for that reason.  Happy to have a conversation about any of the other settings though, which ones are you interested in?

**Comment by anthony-murphy** [comment]
> > i don't believe we should not test things that are deprecated. many of our deprecations are false, and are still in active use, so we should continue to test them. When the work is done to actually remove the deprecated thing these will get removed as well.
> 
> Of the settings currently under test, `enableOfflineLoad` is the only deprecated one that still actually does anything - this one I left unchanged for that reason. Happy to have a conversation about any of the other settings though, which ones are you interested in?

I'm not particularly interested in any of them, i just don't think deprecation is a signal that its safe to do anything in generally. I'd rather see work don't to clean up the deprecation completely, rather than piecemeal removal, which can introduce bugs if we get something wrong.

**Comment by ChumpChief** [comment]
> > Reasoning seems fine to me. But I'd definitely wait for @anthony-murphy or @dannimad's input though, since the experimental options were added pretty recently. If it was an oversight adding them to stress tests because they don't actually have any effect, off with them; but if that was a bug and they should be exercised, we might want a different version of this change.
> 
> @dannimad Based on my read, these settings would need to be in a new config matrix for `generateConfigurations` rather than `generateLoaderOptions`. Currently there's no default matrix (only overrides), but you could add one if you want.

Verified that these options currently have no effect.  Pushed one last commit to demonstrate the potential fix if you're interested @dannimad, verified it works as expected.  Closing per @anthony-murphy 's request.

**Pull request closed without merging**
