### PR TITLE
Split IQuorum interface into client members vs proposal interfaces

### PR DESCRIPTION
**Pull request by ChumpChief**
Aligns with bullet 4 from #6274

Splitting the `IQuorum` interface into its two responsibilities, of maintaining the client list vs. proposals.  Idea would be to permit usage of the proposal side only from within `Container`, making `getQuorum()` return an `IQuorumClients` rather than the full `IQuorum`.

An alternate approach, perhaps:  just drop the proposal interfaces from `IQuorum` since the `Container` can just work with the `Quorum` anyway.

### CODE REVIEW

**Comment by vladsud** [comment]
Should we move it out of protocol definitions first (into container definitions)?
If alternative is viable, should we consider / implement it?

**Comment by vladsud** [comment]
Just to make sure - did you link repos to ensure that client actually builds with these changes when they get consumed?

**Review by vladsud — APPROVED** [review]

**Comment by ChumpChief** [comment]
> Should we move it out of protocol definitions first (into container definitions)?

I'm not sure about this, since it would introduce a dependency from the server to container-definitions.  This kind of feels like something we should avoid.  In any case, I don't think this change makes that move any harder.

> If alternative is viable, should we consider / implement it?

I elected not to yet for simplicity, since the option in this PR is non-breaking-change and it's easy to drop `IQuorumProposals` from `IQuorum` as a further step.  I think this approach also makes staging a bit easier, since it we can aggressively convert usage of `IQuorum` to `IQuorumClients` and instruct customers to cast (e.g. `container.getQuorum() as unknown as IQuorum`) if they need time migrating.

> Just to make sure - did you link repos to ensure that client actually builds with these changes when they get consumed?

I actually had some trouble with symlink:full -- it wasn't actually linking like it was supposed to.  I did ensure that protocol-base built properly with the change just by copying the build product in to node_modules.  I'll try dropping it in a few other locations for more spot checking (also, if you have any idea what's going on with symlink:full I'd love to get that working).

**Comment by ChumpChief** [comment]
> I think this approach also makes staging a bit easier, since it we can aggressively convert usage of `IQuorum` to `IQuorumClients` and instruct customers to cast (e.g. `container.getQuorum() as unknown as IQuorum`) if they need time migrating.

@alpaix relevant to #6462, I see that one remaining reason why a customer would need access to the proposals (and therefore need to cast as quoted above after we hide the proposal interfaces) is to read the approved code details (since we can't understand where `container.codeDetails` is coming from).  Fluid app is doing this.

I could imagine providing a `container.approvedCodeDetails` or `container.specifiedCodeDetails` for this purpose, or perhaps there's another direction you'd prefer.

**Comment by alpaix** [comment]
So `IQuorumMembers` now duplicates `IAudience`. Is it intentional? Quorum implies some consensus mechanism. If we're planning to hide the actual proposals should we deprecate quorum members API altogether?

**Comment by ChumpChief** [comment]
> So `IQuorumMembers` now duplicates `IAudience`. Is it intentional? Quorum implies some consensus mechanism, it's not clear how quorum members interface contributes to the consensus. If we're planning to hide the actual proposals should we deprecate quorum members API altogether?

The interfaces are  slightly different (`ISequencedClient` rather than `IClient`) but yes quite close.  And also agree that it's odd for proposals+members to be merged since the membership isn't directly about consensus -- which is definitely part of the motivation for this interface division.  If we were to build it again perhaps the membership portion would stand alone and the proposal portion would build on top of that membership.  Quorum membership is currently used in a variety of scenarios though, so I'm not ready to make dramatic changes on that side yet.

Ultimately there probably should only be one construct answering the question "who's connected" rather than the separate `IQuorum` and `IAudience` we have today.  @heliocliu has been doing some thinking about the future of the audience, which I suspect will involve deprecating at least one interface as you mention.

**Review by alpaix — APPROVED** [review]

**Comment by ChumpChief** [comment]
symlink:full still doesn't work for me but I verified client packages build correctly with the build outputs of protocol-definitions and protocol-base copied in to node_modules.

**Comment by vladsud** [comment]
>> Should we move it out of protocol definitions first (into container definitions)?
> I'm not sure about this, since it would introduce a dependency from the server to container-definitions. This kind of feels like something we should avoid. In any case, I don't think this change makes that move any harder.

Server has zero dependency on IQuorum. Only on Quorum class (and only on part of it). Or to be exact - QuorumProxy has a dependency, and it does not belong in server as well.

**Comment by ChumpChief** [comment]
> Server has zero dependency on IQuorum. Only on Quorum class (and only on part of it). Or to be exact - QuorumProxy has a dependency, and it does not belong in server as well.

I was counting protocol-base as part of server.  Or even if you don't -- my feeling is that there probably should not be a chain of dependencies upstream from the server that hits container.  Today I think that's true (server -> protocol-base -> protocol-definitions) but if we move `IQuorum` I think it's not (server -> protocol-base -> container-definitions).

Maybe core-interfaces, or common-definitions would be an appropriate place?  Not sure I like those either exactly.

**Comment by vladsud** [comment]
I do not follow :) If you move IQuorum and proxy impl out of server implementation completely, then server would have zero dependency on IQuorum - there is no need for protocol-base to depend on container-definitions.
This can be done by duct typing (i.e. Quorum class stays on the server but implement IQuorum indirectly without declaring it), or better - Quorum class is broken into two parts - the "core" that stays on the server (the minimal needed by server), and the client class (that derives from "core" and implements IQuorum) that lives in loader layer.

container-definitions is the right layers for it, as that's one of the interfaces that loader exposes to container runtime.

**Comment by ChumpChief** [comment]
Whether the interface implementation is explicit or duck-typed, it doesn't matter -- a change in that interface breaks the implementation, so protocol-base becomes implicitly dependent on container-definitions if not explicitly.

I can imagine a world where we continue to break up the `Quorum` and maybe some resulting piece of that makes sense to move, so maybe after we've done that break-up would be an appropriate time for the move.

**Pull request merged**
