### PR TITLE
build(client): Upgrade syncpack and simplify config

### PR DESCRIPTION
**Pull request by tylerbutler**
Unfortunately, version 12 of syncpack has a dependency with a Node20 requirement, so this won't pass CI right now.

### CODE REVIEW

**Comment by tylerbutler** [comment]
Closing since I have other stuff to do. Someone else can do this if they want in the future.

**Comment by JamieMason** [comment]
@tylerbutler I'll take a look at downgrading some of syncpack's dependencies which have higher node engines – they were only really bumped as a bit of housekeeping, there's no concrete need to be on the latest versions. I'll see if I can do that to broaden Node support.

**Comment by tylerbutler** [comment]
> @tylerbutler I'll take a look at downgrading some of syncpack's dependencies which have higher node engines – they were only really bumped as a bit of housekeeping, there's no concrete need to be on the latest versions. I'll see if I can do that to broaden Node support.

@JamieMason Certainly appreciated, but don't go to any great lengths. I noticed the node req dropped to 18.18 in syncpack 13, and our CI is only a little below that. Truly we should be running the latest 18.x - once that upgrade is done we should be unblocked. That said, I would welcome reduced requirements :) and you no doubt have other users that would benefit.

**Comment by tylerbutler** [comment]
@JamieMason Separately, thanks for the awesome tool and great documentation. You've steadily improved it over the months and the comprehensive docs really help with onboarding. It's always exciting to pick up a new release and see features that greatly simplify things for you.

**Comment by JamieMason** [comment]
Hey @tylerbutler, FYI there's an alpha preview of a Rust rewrite available at [14.0.0-alpha.1](https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.1) now. I've been developing it against the FluidFramework repository so you should hopefully be in a good starting point 🤞

**Comment by tylerbutler** [comment]
> Hey @tylerbutler, FYI there's an alpha preview of a Rust rewrite available at [14.0.0-alpha.1](https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.1) now. I've been developing it against the FluidFramework repository so you should hopefully be in a good starting point 🤞

@JamieMason I had a chance to try this today, and it seems to hang, at least with the config I have. You should be able to reproduce it on the [syncpack-config branch](https://github.com/tylerbutler/FluidFramework/tree/syncpack-config) on my fork. I'm happy to file an issue if it's helpful. Not sure what other info to collect.

**Comment by JamieMason** [comment]
Thanks @tylerbutler, which OS are you using?

**Comment by tylerbutler** [comment]
@JamieMason I've tested on Ubuntu 20.04 and mac OS Sequoia ARM. Same behavior on both. I can try Windows 11 if it's helpful. I also tried node 18.20 and node 20.18 when I briefly forgot it was now written in rust. :) If you've been testing with this repo, would you mind sharing the config you've been testing with?

**Pull request closed without merging**
