### PR TITLE
(protocol-base): move scribeHelper to services-client

### PR DESCRIPTION
**Pull request by sonalideshpandemsft**
The functionality related to scribe, blobs, quorum, and some git functions can be found in the `@fluidframework/protocol-base` package.

The `scribeHelper` is only used in the server release group. I have moved `scribeHelper` to the `@fluidframework/server-services-client` package. Ideally, the `scribeHelper` should be placed in `@fluidframework/server-lambdas#scribe`. However, due to cyclic workspace dependencies between lambdas and test-utils, this arrangement is not feasible.

The end goal is to: either move the protocol-base package to the client release group or eliminate the package entirely by appropriately relocating the interfaces, functions, and classes within the codebase.

### CODE REVIEW

**Comment by ssimic2** [comment]
@sonalideshpandemsft I would suggest in these PRs to start calling our principles/tenets behind this move. For example it can be direction of dependencies, or clarification of package use, or it could be "full decoupling" of client server with no shared dependencies. It will help establish reasoning behind any future changes.

**Review by ChumpChief — COMMENTED** [review]
Overall seems good!  Too bad about the test dependency.

Unless/until it can be moved to the lambdas, I think it might be better moved to either server-services-shared or server-services-utils, since we're explicitly saying it shouldn't be used on the client.  Maybe get someone from a server team's opinion?

**Comment by znewton** [comment]
@ChumpChief server-lambdas explicitly cannot depend on sever-services-utils nor server-services-shared. Lambdas have to be isomorphic, and utils/shared are _not_ isomorphic. services-client is where isomorphic utils go.

**Review by znewton — APPROVED** [review]

**Comment by ChumpChief** [comment]
> @ChumpChief server-lambdas explicitly cannot depend on sever-services-utils nor server-services-shared. Lambdas have to be isomorphic, and utils/shared are _not_ isomorphic. services-client is where isomorphic utils go.

Ah, is this isomorphic requirement for local-server?

**Comment by tylerbutler** [comment]
> @ChumpChief server-lambdas explicitly cannot depend on sever-services-utils nor server-services-shared. Lambdas have to be isomorphic, and utils/shared are _not_ isomorphic. services-client is where isomorphic utils go.

@znewton Is there anything in the build or CI enforcing this?

**Comment by ssimic2** [comment]
> @ChumpChief server-lambdas explicitly cannot depend on sever-services-utils nor server-services-shared. Lambdas have to be isomorphic, and utils/shared are _not_ isomorphic. services-client is where isomorphic utils go.

"@fluidframework/server-services-client" -> Fluid server package that contains isomorphic implementations of utilities for communicating with Fluid services that is **shared** between clients and server.... scribeHelper is server-only util? Should there be a better landing place?

**Review by znewton — APPROVED** [review]

**Comment by znewton** [comment]
> > @ChumpChief server-lambdas explicitly cannot depend on sever-services-utils nor server-services-shared. Lambdas have to be isomorphic, and utils/shared are _not_ isomorphic. services-client is where isomorphic utils go.
> 
> "@fluidframework/server-services-client" -> Fluid server package that contains isomorphic implementations of utilities for communicating with Fluid services that is **shared** between clients and server.... scribeHelper is server-only util? Should there be a better landing place?

it's "server"-only, but "server" includes `local-server` which runs in the browser. The description you quoted should probably say "browser and Node.js" instead of "client and server", or something to that effect if we want to be particular about semantics of "client/server"

**Review by ChumpChief — APPROVED** [review]

**Pull request merged**
