### PR TITLE
Deprecate `createSubComponent` for a singular `createComponent` call in IComponentContext

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #1016 

- Removed the createSubComponent method in IComponentContext.
- Updated the signature of createComponent in IComponentContext. The new signature is:
  `public async createComponent(pkg: string, props?: any, id?: string): Promise<IComponentRuntime>`
- createComponent will try to find the component entry in the sub-registry. If that fails, it will try to find the component in the global registry. If one of these passes, it proceeds to create the component from the corresponding registry, else it throws an error.
- createComponent cannot be called with a package path anymore. To do that, createComponent or _createComponentWithProps in IHostRuntime has to be called which looks for the packagePath based off the global registry.
- Also added unit tests that simulate subcomponent creation via creating a LocalComponentContext and calling realize() on it.

### CODE REVIEW

**Review by skylerjokiel — APPROVED** [review]
Super excited about this change! 🕺

**Review by skylerjokiel — APPROVED** [review]
Added a small nit but looks good! :)

**Review by anthony-murphy — APPROVED** [review]
:shipit:

**Review by skylerjokiel — APPROVED** [review]
🎪

**Pull request merged**
