### PR TITLE
Fix contents parsing of messages for fetch tool.

### LINKED ISSUE #3804: fetch-tool is broken for "rawmessage" and other options
## Describe the bug
The fluid-fetch tool is failing with an error on multiple options.  

### To Reproduce
1. `npm i` and `npm run build:fast` in the repo
2. Fetch keys from tools/getKeys following the readme instructions
3. Navigate to packages/tools/fetch-tool/bin. 
4. Run the tool on a fluidpreview document with the option --dump:rawmessage.  Note this also repros with stat options.
5. See the error below.
 
```
ERROR: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.strict(innerContents.type !== undefined)

    at Object.unpackRuntimeMessage (C:\git\FluidFramework\packages\runtime\container-runtime\dist\containerRuntime.js:76:22)
    at processOp (C:\git\FluidFramework\packages\tools\fetch-tool\dist\fluidAnalyzeMessages.js:420:52)
    at DataStructureAnalyzer.processOp (C:\git\FluidFramework\packages\tools\fetch-tool\dist\fluidAnalyzeMessages.js:183:13)
    at Object.printMessageStats (C:\git\FluidFramework\packages\tools\fetch-tool\dist\fluidAnalyzeMessages.js:386:30)
    at async fluidFetchOneFile (C:\git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetch.js:32:5)
generatedMessage: true
code: "ERR_ASSERTION"
actual: false
expected: true
operator: "=="
```

### Expected behavior
Successful fetch

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/3804

The contents maybe jsonified. So check that and parse before doing any operation on it.

### CODE REVIEW

**Comment by heliocliu** [comment]
Is this path just not used in regular document flow?  All the recent docs I pulled with the fetch-tool have the stringified json contents, so it seems weird that this is only an issue for fetch-tool (and if only fetch-tool uses it, it should probably be refactored I guess)

**Review by heliocliu — APPROVED** [review]

**Comment by vladsud** [comment]
It feels like this is an issue in fetch tool only, and should be addressed there, not here.
Can you please provide a bit more info if you believe this is the right place for a fix?

**Comment by curtisman** [comment]
If this change is really needed, then many things would have been broken.   I think something else is happening here. I'd like to understand why we encounter this problem in the fetch tool and not other places first.

**Review by curtisman — CHANGES_REQUESTED** [review]
If this change is really needed, then many things would have been broken. I think something else is happening here. I'd like to understand why we encounter this problem in the fetch tool and not other places first.

**Review by arinwt — APPROVED** [review]

**Review by arinwt — CHANGES_REQUESTED** [review]
Like others said, need to identify why/if this only happens with fetch-tool.  Probably the message object is being mutated unexpectedly.

**Comment by jatgarg** [comment]
Yes, I thought the same but it is ODSP antiques. In normal flow, the messages that we receive on top of snapshot are ISeqDocMessages where this is always object type and therefore we never face this problem. For fetch tool, the messages are fetched through deltastorage, they are op type ISequencedDeltaOpMessage in which these contents are of type string(they are jsonified). So we only get this problem in fetch tool.

**Review by arinwt — APPROVED** [review]
So my understanding is this _could_ happen in prod as well?

**Comment by jatgarg** [comment]
> So my understanding is this _could_ happen in prod as well?

yes. It is just that it never happens currently. But if it will this path, then yes.

**Comment by jatgarg** [comment]
> @jatgarg, it feels like (based on your description) that we should rather fix delta storage pipeline to always return ops in same format.

No, that returns ops in same format: ISequencedDocumentMessage. The ops returned by server when made a get request are of type: ISequencedDeltaOpMessage. In that format the contents are stingified. We are not going to change the inner contents of each message. So this change seems the correct change.

**Comment by vladsud** [comment]
It still does not compute to me :)

It's same ISequencedDocumentMessage in both places, no?
```
export interface ISequencedDeltaOpMessage {
    op: api.ISequencedDocumentMessage;
    sequenceNumber: number;
}
```
And only ISequencedDocumentMessage is exposed from SPO driver, ISequencedDeltaOpMessage is internal implementation of the driver.

In existing shipping product (using SPO), ops come from 3 sources:
1. delta storage (we catch up that way after tab was not active or computer was offline)
2. delta connection (executed all the time)
3. TreesLatest (exposed through delta storage API, also executed all the time).

All 3 return same format - the product works today as is!

So leaving fetch tool for a second, where do you see stringified content today?

BTW, this needs to be addressed - we should be strict and allow only one type on the wire:

export interface IDeltaStorageGetResponse {
    value: api.ISequencedDocumentMessage[] | ISequencedDeltaOpMessage[];
}

**Comment by jatgarg** [comment]
I was wrong. With some more debugging, I found that the parsing of message contents was happening in delta manager and so that is why we were not hitting this in normal flow. For fetch tool, when we analyze fetched messages for stats etc, we use unpackRuntimeMessage which check the contents but we don't go through delta manager path because we are just analyzing the messages and that is why we skip the parsing of contents. So now I have added the same check in fetch tool to parse the contents before analyzing them.

**Comment by vladsud** [comment]
Super! Should we move this logic from delta manager into driver? That way other tools / workflows would not need to know about that specific.

**Comment by jatgarg** [comment]
> Super! Should we move this logic from delta manager into driver? That way other tools / workflows would not need to know about that specific.

I think no. Reasons:
1.) Delta manager is one stringifying the contents so it should have this responsibility too.
2.) In driver ops can come through many sources(Trees latest, delta storage, socket, initial messages), so needs to be added at multiple places while in delta manager it should be added at one place.
3.) In driver too, it should then be added to different drivers. So I guess in tools too it does not need to be added to all of them like it need to be added in this one just because it was a special case(where were using an exported independent api which required the input in a certain way).

**Review by curtisman — APPROVED** [review]
:shipit:

**Pull request merged**
