### PR TITLE
Deprecate summarizer node from runtime-utils and move to container-runtime

### PR DESCRIPTION
**Pull request by ChumpChief**
Since the summarizerNode stuff lives in runtime-utils but must be consumed by container-runtime, it has to be a public API surface today.  However, with no other consumers (and presumably being an implementation detail that we don't want random customers trying to use) it's better to live directly in container-runtime.

This change deprecates it in its current home of runtime-utils (to be then deleted in `next`) ~~and moves it to container-runtime (where it will not be exported)~~ EDIT: The move will be performed in the `next` branch.  I also closed off and/or deleted unused exports in the process.

### CODE REVIEW

**Comment by ChumpChief** [comment]
For visibility - to avoid the repo-policy issue, I'll change this to only deprecate (not duplicate) and then plan to do the move entirely in `next`.

**Comment by agarwal-navin** [comment]
What about the ISummarizerNode and other interfaces which are in runtime-defintions. Are you planning to move them to container-runtime-definitions too?

**Comment by agarwal-navin** [comment]
Note that summarizer node is used in data store runtime as well (although not directly)

**Comment by ChumpChief** [comment]
> What about the ISummarizerNode and other interfaces which are in runtime-defintions. Are you planning to move them to container-runtime-definitions too?

I've not considered yet - I'm coming at this primarily from a perspective of "where can we reduce public API surface" rather than "what's the best home for this interface".  As currently defined, it looks like runtime-definitions is still the correct home for those interfaces but I'll consider it.

**Review by agarwal-navin — APPROVED** [review]

**Pull request merged**
