### PR TITLE
Remove fluid-framework dependencies from client packages

### PR DESCRIPTION
**Pull request by ChumpChief**
The `fluid-framework` package is intended for consumption by 3rd party app developers.  Although it conveniently has some contents that the client packages need, it's not the package's intent.  Removing the dependency removes the temptation to add packages to `fluid-framework` to support client authors (who have pretty divergent requirements from a 3rd party app developer).

### CODE REVIEW

**Comment by curtisman** [comment]
Can we enforce this in layer check?

**Review by micahgodbolt — APPROVED** [review]

**Comment by ChumpChief** [comment]
> Can we enforce this in layer check?

I'll probably take a look at this in a followup - since everything lives in the packages/framework/ directory (clients, aqueduct, and uberpackage) it's a little messy to split up.  I think we should probably do a little directory reorganization here so framework isn't a catch-all, which will also make layer-checking easier.

**Comment by curtisman** [comment]
@ChumpChief  layer check allows you to specify layer for a specific package (which take precedent to the `dir`, so you don't have to split the packages in different directory in order to be in the different layers if you don't want to.

**Comment by ChumpChief** [comment]
> @ChumpChief layer check allows you to specify layer for a specific package (which take precedent to the `dir`, so you don't have to split the packages in different directory in order to be in the different layers if you don't want to.

I started off doing this but it kind of felt like if I have to specify layer manually for each package then maybe our directory organization is not great and should be thought about a bit more.  I can do this though as a temporary measure, will update the PR.

**Comment by ChumpChief** [comment]
Updated layer-check to add a layer for the UberPackage and one for the ServiceClients -- making the ServiceClients non-"dev" seemed accurate and required to make them complain about UberPackage dependencies.

**Pull request merged**
