### PR TITLE
build(client): Use tilde interdependency ranges

### PR DESCRIPTION
**Pull request by tylerbutler**
Updates the client release group to use tilde (`~`) dependency ranges for dependencies within the release group. This was previously verified to work in the build-tools release group (see #15121).

First I updated the dependencies to be tilde-equivalent using the following command:

```shell
flub bump client --exact 2.0.0-internal.4.1.0 --exactDepType "~"
```

Then I updated the pipeline to use tilde instead of caret.

### CODE REVIEW

**Review by anthony-murphy — APPROVED** [review]
I like it. it strikes a good balance by still giving examples of how to construct references. One thing i would like to see is clear and concise documentation about how consumers should reference us (still ^). This can be done as follow up, but overall communication will be key here to ensues consumers do as we say, and not as we do with a change like this.

**Comment by tylerbutler** [comment]
> I like it. it strikes a good balance by still giving examples of how to construct references. One thing i would like to see is clear and concise documentation about how consumers should reference us (still ^). This can be done as follow up, but overall communication will be key here to ensues consumers do as we say, and not as we do with a change like this.

See here in the readme: https://github.com/microsoft/FluidFramework#using-fluid-framework-libraries

Happy to make updates if needed.

**Comment by anthony-murphy** [comment]
> > I like it. it strikes a good balance by still giving examples of how to construct references. One thing i would like to see is clear and concise documentation about how consumers should reference us (still ^). This can be done as follow up, but overall communication will be key here to ensues consumers do as we say, and not as we do with a change like this.
> 
> See here in the readme: https://github.com/microsoft/FluidFramework#using-fluid-framework-libraries
> 
> Happy to make updates if needed.

its a good start. i think we want it in every packages readme, so it also appears on npm, probably needs to go into some templete: https://www.npmjs.com/package/@fluidframework/aqueduct

**Comment by tylerbutler** [comment]
> its a good start. i think we want it in every packages readme, so it also appears on npm, probably needs to go into some template: [npmjs.com/package/@fluidframework/aqueduct](https://www.npmjs.com/package/@fluidframework/aqueduct)

Ahh, that's easy enough thanks to awesome work that @Josmithr has spearheaded! I'll follow up with another PR.

**Pull request merged**
