### PR TITLE
Switch client build to pool with better machines

### PR DESCRIPTION
**Pull request by justus-camp**
## Description
A while back I requested larger machines to speed up our build and dropped the task while waiting for it to be approved. The pool has been allocated but hasn't been hooked up yet. 

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

### CODE REVIEW

**Comment by alexvy86** [comment]
We should update the image used by the agents in the new pool (look at Settings -> Pool -> Images in the left pane in the Azure portal for NewLarge VS Large).

One other thing that might not matter (as far as I can tell) for the Build - client packages pipeline **but** could matter for others, is the Azure region change. We have some Azure resources in WestUS2 that some test runs leverage; for example if we move the e2e tests pipeline to NewLarge, we'd have agents running in WestUS3 making network requests to resources in WestUS2 and that means a cost increase for inbound/outbound network traffic between regions. Could we recreate NewLarge in WestUS2 to be safe?

**Comment by justus-camp** [comment]
Finally looped back around to this now that we have the image building properly. Looks like we save a good amount of CI time!

**Comment by curtisman** [comment]
Should we switch all the pool to use the new Pool?   Alternatively, should we just update the Agent size of the exist pool instead? Is it possible?

**Review by curtisman — APPROVED** [review]

**Comment by alexvy86** [comment]
I'll just point out again the potential issue of additional cross-region network traffic between the build agents (now on WestUS3) and our azure resources already living in WestUS2, and its related cost. Off the top of my head I wouldn't expect it to be incredibly big, but we should monitor.

**Pull request merged**
