### PR TITLE
Refactor: compareArray() -> coreutils

### PR DESCRIPTION
**Pull request by DLehenbauer**
@anthony-murphy - Prior to the holiday, we discussed migrating generic zero-dependency util functions into a 'core-utils' package.  I grabbed the first one (compareArrays) during my commute this week.

In the process, I realized there is going to be some unanticipated tax, as I didn't feel good about committing without fixing the missing test coverage.

I then saw that our unicorn lint plugin was rewriting for-loops as for-of loops with destructuring, which I suspected was a perf regression, so I also ended up benchmarking (verdict: we should disable that rule).  However, Array.every(..) ties for first place.

### CODE REVIEW

**Comment by tylerbutler** [comment]
@DLehenbauer great find about that lint rule! @Josmithr FYI. We should probably be more cautious about other unicorn rules.

**Comment by DLehenbauer** [comment]
FYI - PR to disable `unicorn/no-for-loop` here:
https://github.com/microsoft/FluidFramework/pulls

In this benchmark, the regression was ~2x and noisy, which usually indicates transient allocations, which makes me suspect that V8 is heap allocating an Array object to return the [element, index] pair (unverified educated guess).

**Review by anthony-murphy — APPROVED** [review]
awesome!

**Pull request merged**
