### PR TITLE
Move @types deps to devDeps

### PR DESCRIPTION
**Pull request by jason-ha**
- just remove `@types/node` from `monaco` as unused

### CODE REVIEW

**Comment by tylerbutler** [comment]
> @types/* packages are not imported as they only contain typescript metadata and thus are not required for production. Downstream dependents should not have to download those packages.

While this is usually true, there are legitimate reasons to distribute types of those types are part of the exported API. I encourage waiting to merge this until you can verify that's not the case for these.

**Comment by CraigMacomber** [comment]
I don't think "@types/* packages are not imported" is true. TypeScript supports importing types (with "import" statements), and we redistribute packages which contain types (in the form of d.ts files) which import and possible reexport other types. (example of someone else making this same argument: https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies ).

If we do not reexport these types in our public API, it might be ok to do this change. Do we have any tooling in place that verifies this is the case?

**Comment by jason-ha** [comment]
> If we do not reexport these types in our public API, it might be ok to do this change. Do we have any tooling in place that verifies this is the case?

There is no tooling in place. I can confirm that common-utils has public (deprecated) types that use `events` and therefore `@types/events` needs to be available.

**Comment by jason-ha** [comment]
> While this is usually true, there are legitimate reasons to distribute types of those types are part of the exported API. I encourage waiting to merge this until you can verify that's not the case for these.

It is true and weird for at least node. It is funny to have a production dependency on @types for end product that has no typescript. This is a case for peerDevDependency that doesn't exist. So much nicer when things are packaged together.

I came to this observing an update to FluidExamples. The repo was moved to node 18+, but node 16 dependencies remain from `server-memory-orderer` and `server-services-core`. There is no node 16 in FluidExamples anymore even for `server-memory-orderer` and `server-services-core` - they are using node 18+ and have no say on that dependency. Well, they can have a say if they list node engines, but they don't. I hope they don't have any node dependent exports. ...

api-extractor actually does a pretty decent job here of capturing dependencies, but I don't see reports for those. `node` type dependent types probably are hard to spot and don't think will shine through api-extractor. I am curious to know how those in `dependencies` landed there.

I'll walk back most and straight-up remove `@types/node` from examples/data-objects/monaco/package.json as it doesn't appear to be needed. At least builds fine without it. Unchanged will be experimenta/*/examples are those two are apps without APIs (that I see).

I don't know what should be done for `@types/node` `dependencies` in `routerlicious`.

**Review by tylerbutler — APPROVED** [review]
Looks like there's a merge conflict in the lockfile, but other than that looks good.

**Pull request merged**
