### PR TITLE
build: Use file: dependencies for shared eslint config 

### PR DESCRIPTION
**Pull request by tylerbutler**
Updates the client, build-tools, and common packages to depend on the shared eslint config as a `file:` dep.

This change would enable us to more quickly adopt lint config changes, and stop publishing the config since it's really only intended for our use.

Because the shared config is an independent package, any other package or release group in the repo can use the same approach in follow up PRs.

I also bumped the eslint version used everywhere and bumped eslint-config-fluid from 2.0.0 to 3.0.0 since bumping the lint version constitutes a breaking change in the lint config. Might split this out into a separate change but I want to test it in CI together.

### CODE REVIEW

**Comment by ChumpChief** [comment]
I have kind of mixed feelings with this - a similar relative-path approach has bitten us a couple times with prettier (e.g. [here](https://github.com/microsoft/FluidFramework/pull/15349#discussion_r1180673353) and [here](https://github.com/microsoft/FluidFramework/pull/15355)) resulting in quiet failures that were hard to detect.  I do like the idea of not requiring a package release for an update, but is there anything we can do to avoid the relative paths?

**Comment by alexvy86** [comment]
> I have kind of mixed feelings with this - a similar relative-path approach has bitten us a couple times with prettier (e.g. [here](https://github.com/microsoft/FluidFramework/pull/15349#discussion_r1180673353) and [here](https://github.com/microsoft/FluidFramework/pull/15355)) resulting in quiet failures that were hard to detect. I do like the idea of not requiring a package release for an update, but is there anything we can do to avoid the relative paths?

In this case it would certainly be caught during `pnpm i`, right? A dependency pointing to a folder that doesn't exist would complain loudly?

**Comment by Josmithr** [comment]
> > I have kind of mixed feelings with this - a similar relative-path approach has bitten us a couple times with prettier (e.g. [here](https://github.com/microsoft/FluidFramework/pull/15349#discussion_r1180673353) and [here](https://github.com/microsoft/FluidFramework/pull/15355)) resulting in quiet failures that were hard to detect. I do like the idea of not requiring a package release for an update, but is there anything we can do to avoid the relative paths?
> 
> In this case it would certainly be caught during `pnpm i`, right? A dependency pointing to a folder that doesn't exist would complain loudly?

Personally, I think this is exploding at `pnpm i` time is sufficient to take on the relative file path cost. That said, does pnpm have anything for this? Or would leveraging pnpm require us to have everything under a single parent workspace?

Either way, I think this change is an improvement and am for it. Just wondering if we might have our eyes set on something a bit nicer long term.

**Comment by alexvy86** [comment]
I'm overall in favor of the change too. One caveat I just read is that `file: ... ` [won't install the dependency's own dependencies](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#local-paths) during `(p)npm install`. Doesn't look like it matters for `eslint-config-fluid` in particular, but either we keep it as a static-file-only package, or update our docs to require a manual `pnpm i` there if it becomes necessary at some point. If we want to keep it static-file-only, I'd update its README to reflect that.

Not sure what workflows is that package's `print-config` bit used in.

**Comment by tylerbutler** [comment]
> That said, does pnpm have anything for this? Or would leveraging pnpm require us to have everything under a single parent workspace?

Workspaces are the only way to get pnpm to manage the relationship for you. I do like the idea of a single workspace, but we would need a lot more infra to do it, and it would take us further into custom tooling.

> One caveat I just read is that file: ...  [won't install the dependency's own dependencies](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#local-paths) during (p)npm install. Doesn't look like it matters for eslint-config-fluid

This is the biggest problem. It means that the root of the release group needs to have the eslint package's dependencies (like it used to before we started using the `require` workaround) or strange things will happen. We could maybe do something really janky with a preinstall script - have the preinstall run install in the eslint package root. Reeaaallllly hacky.

**Pull request closed without merging**
