### PR TITLE
Integrate main to next

### PR DESCRIPTION
**Pull request by heliocliu**

### CODE REVIEW

**Review by sonalivdeshpande — APPROVED** [review]
:shipit:

**Comment by markfields** [comment]
@heliocliu is this the periodic and boring "FI" to keep `next` up to date with non-breaking changes going into `main`?  Is there anything to look for in terms of reviewing, or it's just a formality?

**Comment by markfields** [comment]
Ouch, merge conflicts already

**Comment by heliocliu** [comment]
@markfields Yup, and it's mostly a formality and for getting some eyes on merge conflicts.  Sonali is working on automating this 🙂

@anthony-murphy I resolved the merge conflicts in `packages/dds/merge-tree/src/mergeTree.ts` for you here fyi.  The conflict was the more mechanical changes Matt had for updating the eslint config so it should be pretty low risk for screw up on my part

**Review by anthony-murphy — APPROVED** [review]

**Comment by anthony-murphy** [comment]
@sdeshpande3 and @heliocliu for the automation, are we planning one big PR like? or something more granular, like a change-by-change cherry pick? it could work out to be basically the same thing if we run it in CI, as i wouldn't expect each CI to cover only a small number of changes, but i do worry if there is a backup for some reason we could end up with HUGE PR's that are hard to get in.

**Comment by heliocliu** [comment]
> @sdeshpande3 and @heliocliu for the automation, are we planning one big PR like this? or something more granular, like a change-by-change cherry pick? it could work out to be basically the same thing if we run it in CI, as i would expect each CI to cover only a small number of changes, but i do worry if there is a backup for some reason we could end up with HUGE PR's that are hard to get in.

Goal is definitely a single-change granularity.

**Pull request merged**
