### PR TITLE
Remove deep cloning in Quorum, and lodash dependency

### PR DESCRIPTION
**Pull request by ChumpChief**
We have relatively few usages of lodash in the client bundles, so I was curious if we could potentially eliminate its usage (checking one of our examples, eliminating lodash entirely would save ~21kb in the packed bundle).  The most annoying usage is in the Quorum in protocol-base, but it doesn't appear to really be crucial there.

Both members and proposals are not directly modifiable without catastrophe -- attempting to do so will taint the next snapshot at minimum if not cause bigger problems more immediately.  So I don't think there's a risk of the snapshot caches seeing a "too-live" version of the data or else it would be blowing up already today.  The important thing is to make sure the set itself doesn't change, which is sufficiently protected already via `Array.from()`.

And on the flip side, the `snapshot()` methods are not customer-facing and `getApprovalData()` is deprecated.  Neither is visible in the client packages in normal usage (hidden within the `Container`, no direct public access - someone would have to be directly using the protocol-base package for their own purposes). I don't think there's realistic risk that someone is currently calling these and expecting to get a deep clone back that they can then modify safely.  Also consider that we're inconsistent in usage of `deepClone` here - e.g. we don't `deepClone` the `proposalsSnapshotCache`, nor the values returned from `.get()`.

Given that the original purpose of the snapshot caches was to avoid the deep clones for COGS reasons, this change probably has some theoretical COGS benefits as well.  We could also probably consider getting rid of the snapshot caching logic altogether if we're not deep cloning anymore, but I don't think it hurts anything here and would still have some minor benefit.

### CODE REVIEW

**Review by tylerbutler — APPROVED** [review]
I don't know enough about quorum to comment on the soundness of the change there, but no public API change + bundle size reduction makes me happy. That said, we'll need a server release to benefit from this, right?

**Comment by ChumpChief** [comment]
> I don't know enough about quorum to comment on the soundness of the change there, but no public API change + bundle size reduction makes me happy. That said, we'll need a server release to benefit from this, right?

Yep - that's what I meant by this one being the most annoying one :-P There are a couple uses in the client packages to iron out before we can eliminate the dependency entirely but I think they're probably manageable.

**Comment by ChumpChief** [comment]
@vladsud @GaryWilber checking if you have any feedback on this before merge?

**Comment by GaryWilber** [comment]
@ChumpChief There's a part of scribe that [gets the current protocol op handler state](https://github.com/microsoft/FluidFramework/blob/6a8538e7d826894a6e8d20ba6085e9669bae725a/server/routerlicious/packages/lambdas/src/scribe/lambda.ts#L207) and it's expecting that the state will not change from any subsequent changes to the protocolHandler. Since it will no longer deep clone, could the following `this.processFromPending(value.operation.referenceSequenceNumber);` line cause the state in `prevState.protocolState` to change?

**Comment by ChumpChief** [comment]
No - message processing only alters the quorum contents (and thereby the snapshot/protocol state) in a [limited set of ways](https://github.com/microsoft/FluidFramework/blob/main/server/routerlicious/packages/protocol-base/src/protocol.ts#L114):
1. A new proposal is added in response to `MessageType.Propose`
2. A new value is committed by MSN updating (`updateMinimumSequenceNumber`)
3. A `QuorumClients` member is added or removed in response to `MessageType.ClientJoin` or `MessageType.ClientLeave`

These are all safe to _not_ deep clone for the same reasons - namely:
1. The collection of each that the snapshot holds will still be a shallow clone (via `Array.from()`), so newly added/deleted members of each won't affect the members in the snapshot.
2. We only permit adding/removing from each (no modification API), and when doing the add/remove we always create a brand new object to set into the collection (even internally, we never modify an existing object).

**Comment by vladsud** [comment]
Is lodash/cloneDeep really 21Kb after minification?
My take here - it's very hard to avoid having a need to do deep cloning, sooner or later we will need it. If it's so expensive, should we roll out our own, maybe more limited (i.e. that works only on subset of types)?
The alternative I see - starting to use more broadly Readonly<>, as well as define and use deep-readonly modifiers.

I want to avoid the need for discussions like above, at least reduce them to only small set of places where it really matters (for perf reasons),and stick with defaults that are result in substantially more cases of developers writing correct code.
I have not looked at the specific segment of the code, but even if it's correct today - will it stay correct in the future if new developer makes some benign change? How do we protect against errors?

**Comment by vladsud** [comment]
That said, @GaryWilber, if you have concerns (or even have to ask that question), does it mean that we are missing test case to cover it? Should it be added as part of this or follow up change?

**Comment by ChumpChief** [comment]
> Is lodash/cloneDeep really 21Kb after minification?

This was just from a quick `npm run webpack` on one of our examples (I think I used schema-upgrade), with the experiment of this change + also removing the lodash usages in the other client packages.  That pack script does include inline source mapping so some of the gains should probably be discounted as source map reduction -- percentage-wise, it was ~1.8% of the total bundle.

I notice that cloneDeep uses [baseClone](https://github.com/lodash/lodash/blob/master/.internal/baseClone.js) which has many further dependencies, I think these just add up.

> My take here - it's very hard to avoid having a need to do deep cloning, sooner or later we will need it. If it's so expensive, should we roll out our own, maybe more limited (i.e. that works only on subset of types)?

I agree with these points, and I don't think I'd promote a blanket ban.  Here it seems advantageous since it's in a core package that every client must use/load and it serves no benefit, but I care less about the usage in e.g. PropertyDDS since clients have to opt-in to that DDS anyway (and if a more efficient option is available they can choose that instead).

> That said, @GaryWilber, if you have concerns (or even have to ask that question), does it mean that we are missing test case to cover it? Should it be added as part of this or follow up change?

Good idea, I'll do this.  Historically the Quorum hasn't been tested, the tests we have now are just what I added when I was refactoring the relevant potions.  I can add a test that proves durability of the snapshot as the Quorum is modified in the ways mentioned above.

**Review by GaryWilber — APPROVED** [review]
Thanks for adding those tests. Looks good from a server-side perspective.

**Pull request merged**
