### PR TITLE
Change GC Version semantics to inequality

### PR DESCRIPTION
**Pull request by markfields**
## Description

When deploying a change to the current GC Version, a document may have collaborators with different values - hence the Running Summarizer could jump between these, the "current" GC Version may fluctuate up and down.

In the current code, every time that happens fullTree will be used for GC.  We can avoid this thrashing by switching the semantics to inequality, so fullTree is only used if the persisted value is strictly less than the current value.

### CODE REVIEW

**Comment by agarwal-navin** [comment]
The general idea behind the GC version in summary is that it tells you what GC version was used to generate the GC data in the summary.
Using inequality breaks that invariant because a summary can contain GC data that was written using two (or multiple) different versions. It makes it hard to reason about the GC data in the summary.

Re-writing GC data on version change keeps things simple - If GC version in summary is N, this is what it means about the GC data. For example, the GC data cannot be trusted, the GC data was written with x funtionality, etc.

**Comment by agarwal-navin** [comment]
As far as thrashing is concerned, I don't think its a big deal - fullTree will be used only for the first summary in a summarizer, subsequent summaries will be incremental. So, even if the summarizer keeps flip-flopping between versions (which I don't think is a common scenario), it won't be expensive.
Another point is the fullTree is not that expensive in most cases. Fun fact - We used to always do a full summary of all DDSes in summary for a long time and no one cared. This PR stopped doing this recently - https://github.com/microsoft/FluidFramework/pull/10215

**Comment by markfields** [comment]
> Using inequality breaks that invariant because a summary can contain GC data that was written using two (or multiple) different versions.

Sold

**Comment by markfields** [comment]
Tests are included in #14657

**Pull request closed without merging**
