### PR TITLE
Backport: Remove IDocumentAttributes.term and ISequenceDocumentMessage.term (#14959)

### PR DESCRIPTION
**Pull request by ChumpChief**
Breaking changes outside of the client release group should go into `main`, so this change backports the change from PR #14959).

Since the client changes are non-breaking, we can just backport the whole thing.

I think it is correct to retain the same changeset for this change, let me know if that's incorrect.

Labeling do-not-merge-in-next since it's already present in next.

### CODE REVIEW

**Comment by ChumpChief** [comment]
PR for snapshot test data update: https://github.com/microsoft/FluidFrameworkTestData/pull/59

**Comment by anthony-murphy** [comment]
won't this just create a merge nightmare when this merges back to next? whats the advantage to expidite it?

**Comment by ChumpChief** [comment]
> won't this just create a merge nightmare when this merges back to next? whats the advantage to expidite it?

I think the label I added prevents it merging back to next.  There's a Teams thread re: server changes policy that's motivating this.

**Comment by anthony-murphy** [comment]
> > won't this just create a merge nightmare when this merges back to next? whats the advantage to expidite it?
> 
> I think the label I added prevents it merging back to next. There's a Teams thread re: server changes policy that's motivating this.

i think the label is almost worse, as it will push the merge conflict to the next main next merge. i don't think the server discussion really matters, all not doing in in main will do is delay the changes

**Comment by anthony-murphy** [comment]
> > won't this just create a merge nightmare when this merges back to next? whats the advantage to expidite it?
> 
> I think the label I added prevents it merging back to next. There's a Teams thread re: server changes policy that's motivating this.

i think the label is almost worse, as it will push the merge conflict to the next main next merge. i don't think the server discussion really matters, all not doing in in main will do is delay the changes

**Comment by ChumpChief** [comment]
Original change was reverted - I'm going to instead redo the original against main, so no porting needed.

**Pull request closed without merging**
