### PR TITLE
Move webpack-fluid-loader to @fluid-example scope and remove yo fluid generator

### LINKED ISSUE #6914: Move webpack-fluid-loader into @fluid-example/example-utils
`webpack-fluid-loader` isn't really meant for production use but rather as a tool to load example data-objects.  We should consider moving it under the `@fluid-example` scope to communicate this more clearly.

`@fluid-example/example-utils` is a good fit, since the `ContainerViewRuntimeFactory` that's already there is designed with the `webpack-fluid-loader` in mind -- it specifically produces container runtimes that `webpack-fluid-loader` knows how to load and render default views for.

### PR DESCRIPTION
**Pull request by ChumpChief**
Fixes #6914 

This change moves webpack-fluid-loader under the `@fluid-example` scope (as it is only intended for use in internal examples) and removes the yo fluid generator which depends upon it (this generator previously served the purpose of tutorializing and aiding in getting started with fluid, which has since been replaced by guidance [here](https://fluidframework.com/docs/start/quick-start/)).  The build/bump tools are also subsequently updated for this change.

### CODE REVIEW

**Comment by DLehenbauer** [comment]
@ChumpChief - I recently added the `@fluid-tools` scope "for useful tools that we publish publicly, but primarily support for our own scenarios."

Might be a fit for 'webpack-fluid-loader'?

**Comment by tylerbutler** [comment]
@ChumpChief @DLehenbauer Can you double-check that the information in the wiki is correct? https://github.com/microsoft/FluidFramework/wiki/npm-package-scopes

**Comment by ChumpChief** [comment]
@DLehenbauer thanks for the pointer, I hadn't seen that.  It might be ok, though all of our documentation and current efforts are moving away from this sort of hosting -- I'd kind of prefer to be more aggressive about suppressing non-recommended hosting methods.  I started a Teams thread to see how folks feel about the removal of yo fluid, and if we have consensus on removing that then I don't think we have a motivating reason to publish webpack-fluid-loader.

**Comment by ChumpChief** [comment]
Based on feedback, closing this PR and opened #6956 to move WFL to the tools scope instead.

**Pull request closed without merging**
