### PR TITLE
docs(app-insights-logger): Mark exports as `@beta` in preparation for upcoming 2.0 beta

### PR DESCRIPTION
**Pull request by Josmithr**
Only required tag changes within the package.

AB#6598

### CODE REVIEW

**Review by alexvy86 — COMMENTED** [review]
I feel tempted to mark these as @alpha; although as we discussed, that feels a bit at odds with "you can use this logger for your production apps". Thoughts?

**Comment by Josmithr** [comment]
> I feel tempted to mark these as @Alpha; although as we discussed, that feels a bit at odds with "you can use this logger for your production apps". Thoughts?

The plan is to make this package available as a part of the 1st beta release candidate. All of those packages, which are intended to become public with 2.0, are being marked as `@public`. That way consumers don't have to import members from the release candidate packages using `/beta`.

**Review by alexvy86 — APPROVED** [review]
> That way consumers don't have to import members from the release candidate packages using `/beta`.
> 
> We can still make breaking changes to the APIs between now and the official 2.0 release.

Oh right, import paths... yeah, @public seems fine for now.

**Comment by Josmithr** [comment]
> > That way consumers don't have to import members from the release candidate packages using `/beta`.
> > We can still make breaking changes to the APIs between now and the official 2.0 release.
> 
> Oh right, import paths... yeah, @public seems fine for now.

Per an offline discussion with @rohandubal and @kashms, we actually are going to tag these APIs as `@beta` after all. This matches the intended tagging plan for `odsp-client`.

**Review by alexvy86 — APPROVED** [review]
🚀 
image

**Pull request merged**
