### PR TITLE
[main > server/2.0] Better error handling in broadcast signal in Alfred

### PR DESCRIPTION
**Pull request by ghoshkaj**
Port `fix (server): Better error handling in broadcast signal in Alfred #17540` to server/release/2.0.0 branch in order to create a new release patch.

### CODE REVIEW

**Review by alexvy86 — APPROVED** [review]
@tylerbutler hopefully getting ahead of some feedback: the breaking changes here are specifically around the new API @ghoshkaj has been working on and isn't yet used anywhere (the interface that breaks didn't exist before the new endpoint was added). The endpoint also expects its payload in a slightly different format. So, yes, technically breaking, but the API they're affecting could still be considered experimental/alpha (even if not explicitly marked as such). I'm inclined to release these as a patch to server 2.0 instead of going to 3.0. If you feel different let's chat.

**Comment by tylerbutler** [comment]
> @tylerbutler hopefully getting ahead of some feedback: the breaking changes here are specifically around the new API @ghoshkaj has been working on and isn't yet used anywhere (the interface that breaks didn't exist before the new endpoint was added). The endpoint also expects its payload in a slightly different format. So, yes, technically breaking, but the API they're affecting could still be considered experimental/alpha (even if not explicitly marked as such). I'm inclined to release these as a patch to server 2.0 instead of going to 3.0. If you feel different let's chat.

When do you think this new API will be fully tested and ready? Can we test it through some other means so we don't have to release patches?

I guess I don't have practical objections but these sorts of changes just feel wrong to me in patches. Are these alpha/beta APIs? Once we have the alpha/beta API pipeline work done (very close), could these APIs be marked as such so they're trimmed from the public API if they're not ready to be public?

**Comment by ghoshkaj** [comment]
> When do you think this new API will be fully tested and ready? Can we test it through some other means so we don't have to release patches?

By adding the unit tests now we have gotten to testing it as fully as we can without being able to use tinylcious. The reason that these changes have been difficult is because we don't have the tribal knowledge and the infrastructure isn't set up to make it easy to test. There is some work being done to put tinylicious into the same release group as routerlicious which will streamline this effort going forward. But in general, the whole server code is an area that is a bit of a wild west and we're learning as we're going.

> I guess I don't have practical objections but these sorts of changes just feel wrong to me in patches. Are these alpha/beta APIs? Once we have the alpha/beta API pipeline work done (very close), could these APIs be marked as such so they're trimmed from the public API if they're not ready to be public?

The whole point of mainlining this is so that they become part of the public API. I agree that they should have been alpha up to now, but that is not a concept I've seen being used so far in server releases. Is it there already?

**Comment by tylerbutler** [comment]
> I agree that they should have been alpha up to now, but that is not a concept I've seen being used so far in server releases. Is it there already?

Not yet, but it's coming soon (mostly #17460 and #17459).

**Comment by tylerbutler** [comment]
>But yes, we can release as 3.0.0.

I'm not suggesting that. Really, my concern is based on the fact that we don't do server releases often, and needing so many in a short period of time triggers my spidey sense.

**Comment by tylerbutler** [comment]
> The reason that these changes have been difficult is because we don't have the tribal knowledge and the infrastructure isn't set up to make it easy to test. There is some work being done to put tinylicious into the same release group as routerlicious which will streamline this effort going forward. But in general, the whole server code is an area that is a bit of a wild west and we're learning as we're going.

I'd love to be involved in discussions about how to test things like this. The release group boundary should NEVER be a blocker to test something locally. There are usually ways to publish packages locally and test things end to end, even with changes that span tinylicious, server, and client. Sometimes they're not cheaper than publishing releases, but they often are. But that's for the future, I'm not trying to redesign how this is/should be tested.

**Comment by alexvy86** [comment]
> Once we have the alpha/beta API pipeline work done (very close), could these APIs be marked as such so they're trimmed from the public API if they're not ready to be public?

Not sure that applies to new endpoints being exposed in a server 😄 . For that scenario, maybe having an /api/v1/experimental path for them to live under until they graduate, could be an option?

**Comment by tylerbutler** [comment]
> @tylerbutler can I go ahead and merge a kick off a release for this branch this time?

Merge but please ask the on-call release driver to do the release. Server releases need to be done by the release drivers.

**Pull request merged**
