### PR TITLE
feat(eslint-config-fluid): Re-enable `unicorn/prefer-node-protocol` rule now that the repo has been updated beyond Node.js v16

### PR DESCRIPTION
**Pull request by Josmithr**
Rule was previously disabled due to incompatibilities. Now that the repo has been update beyond Node.js v16, it is safe to reenable.

Rule documentation: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md

### CODE REVIEW

**Comment by alexvy86** [comment]
I'm in favor but I suspect it's could be controversial 😄

**Comment by alexvy86** [comment]
Interesting question: would it affect bundle size?

**Comment by CraigMacomber** [comment]
> Interesting question: would it affect bundle size?

Generally, code we care about bundle size for is running in the browser, and shouldn't be importing node modules, so it should not matter.

**Comment by CraigMacomber** [comment]
We already use this pattern in several places, and we don't have a large number of node imports which could be impacted, so this seems like a good and not too impactful change.

It will mostly impact test code importing node's assert library, but as --fix should clean that up, I think it ok: that will be a rather large diff though, and we might want to pre-migrate code to it to reduce the burden of updating to our updated linter settings.

**Review by CraigMacomber — APPROVED** [review]

**Comment by ghoshkaj** [comment]
>  we might want to pre-migrate code to it to reduce the burden of updating to our updated linter settings

Just to clarify what "pre-migrate code to the new linter setting" means -- we mean run this setting with --fix and merge those changes in prior to merging in this PR that actually updates the linter setting right?

**Comment by Josmithr** [comment]
> > we might want to pre-migrate code to it to reduce the burden of updating to our updated linter settings
> 
> Just to clarify what "pre-migrate code to the new linter setting" means -- we mean run this setting with --fix and merge those changes in prior to merging in this PR that actually updates the linter setting right?

Yeah, that's right. Pre-fix as many violations as we can before actually enabling enforcement of the new rule. Makes the PR adding enforcement much smaller and easier to accomplish.

**Comment by Josmithr** [comment]
> We already use this pattern in several places, and we don't have a large number of node imports (other than test asserts) which could be impacted, so this seems like a good and not too impactful change.
> 
> It will mostly impact test code importing node's assert library, but as --fix should clean that up, I think it ok: that will be a rather large diff though, and we might want to pre-migrate code to it to reduce the burden of updating to our updated linter settings.

We appear to have a number of rule changes that have not been pre-fixed. Rather than try to filter down to just this rule change and fix here, I'm going to do a larger PR that attempts to pre-fix violations for the next release of our config.

**Comment by Josmithr** [comment]
> We appear to have a number of rule changes that have not been pre-fixed (I'm sure I contributed to this). Rather than try to filter down to just this rule change and fix here, I'm going to do a larger PR that attempts to pre-fix violations for the next release of our config.

Actually, it looks like I was mistaken. I had to rebuild some things. After that, the majority of the issues were indeed for this new rule. PR pre-applying fixes is here: #17363

**Pull request merged**
