### PR TITLE
build: Set packageManager field in all packages

### PR DESCRIPTION
**Pull request by tylerbutler**
## Description

I noticed that when running `pnpm i` from a package within a release group, node would get confused about the version of pnpm to use. It would use 8, which would upgrade the lockfile format. It was pretty obvious when I investigated, but it sort of happens silently then you notice the effect in the lockfiles.

This change addresses the problem by setting the `packageManager` field in each package's package.json so that node consistently uses the correct version.

I also upgraded to the latest available 7.x version of pnpm.

## Approach

To upgrade pnpm, I neededto determine the sha512 hash of the package. I did that with the following commands:

```shell
$ wget $(npm view pnpm@7.32.3 dist.tarball)
$ shasum --algorithm=512 pnpm-7.32.3.tgz
c28d73f0d82a6c4712a40b91aa43d7397e119b16f35e5e75fe9b7e8fd4f2fc6dfbb68bb3ffac3473a958bbafa7888b79ec384ad122537378089a3a2a19b9900e  pnpm-7.32.3.tgz
```

To upsert the field, I installed [npe](https://www.npmjs.com/package/npe) globally and ran these commands in the root of the repo:

```shell
pnpm exec flub exec -a -- "npe packageManager pnpm@7.32.3+sha512.c28d73f0d82a6c4712a40b91aa43d7397e119b16f35e5e75fe9b7e8fd4f2fc6dfbb68bb3ffac3473a958bbafa7888b79ec384ad122537378089a3a2a19b9900e"
pnpm exec flub exec -a --releaseGroupRoots -- "npe packageManager pnpm@7.32.3+sha512.c28d73f0d82a6c4712a40b91aa43d7397e119b16f35e5e75fe9b7e8fd4f2fc6dfbb68bb3ffac3473a958bbafa7888b79ec384ad122537378089a3a2a19b9900e"
pnpm run policy-check:fix
pnpm run format:changed
```

### CODE REVIEW

**Comment by alexvy86** [comment]
Did you do manual cleanup after running `npe`? I'm just curious why tools/telemetry-generator didn't get its package.json updated (which is fine since it hasn't moved to pnpm).

**Comment by tylerbutler** [comment]
> ```shell
> pnpm exec flub exec -a -- "npe packageManager pnpm@7.32.2+sha512.3dfa2c1386fc91e58756b3becf877e9dc20840af72a5301d453ae4da2a19db00cdd08f4bfa66a9cc9565755aac65dcbbbda93232dc5f927376727e708c449bbe"
> ```

Looks like that project isn't in the fluid-build config, so none of the build tools know about it:

https://github.com/microsoft/FluidFramework/blob/5a956cd09f1e4be7354f053f83eef49ec9ee0f57/fluidBuild.config.cjs#L30-L36

We can update that but it should be a separate PR.

**Comment by CraigMacomber** [comment]
Given that npm install knowns about workspaces, is it necessary (and useful) to have this in the packages withing workspaces or do we just need this at the workspace roots and independent packages?

**Comment by CraigMacomber** [comment]
For me, even without this change, corepack seems to select our chosen pnpm version inside the inner packages within our workspaces. Which package did you observe this issue in?

**Comment by tylerbutler** [comment]
Craig and I chatted offline, and tried to repro the behavior that I was trying to fix. We can't repro, so I've moved this to a draft for now. If we don't have problems in the next month or so this PR will expire and we can ignore.

**Comment by tylerbutler** [comment]
Closing since we no longer think this is needed.

**Pull request closed without merging**
