### PR TITLE
Add script to download and unzip documentation build artifacts

### LINKED ISSUE #3582: Add script to download and unzip api docs
While we don't want to force everyone to download the API docs, we should make them easier to install if they're trying to build the entire docs site. 

We need to add a script to the /docs/package.json to download https://fluidframework.blob.core.windows.net/api-extractor-json/latest.tar.gz and then unzip it to the /_api-extractor-temp folder.

Then update /docs/README.md to include those instructions

### PR DESCRIPTION
**Pull request by tylerbutler**
Fixes #3582.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
This is awesome. I was thinking about this last night and wondered if there was a simple CLI way to download and unpack assets,  and yes there is!

**Comment by micahgodbolt** [comment]
Can you add a quick line in the readme about 'if you need the API docs run X'

**Comment by micahgodbolt** [comment]
running the download script updates the playground.html file. I assume we don't want to check this change in?

image

**Comment by micahgodbolt** [comment]
Also, extra bonus for pulling in the playground too!

**Review by micahgodbolt — APPROVED** [review]
Everything works great except for the modification to the playground.html file. Do we need to .gitignore that file? Or can we add this script without modifying the file?

**Comment by tylerbutler** [comment]
> Everything works great except for the modification to the playground.html file. Do we need to .gitignore that file? Or can we add this script without modifying the file?

I addressed this by updating the script to add `git update-index --assume-unchanged layouts/page/playground.html`

> Can you add a quick line in the readme about 'if you need the API docs run X'

Added.

**Pull request merged**
