### PR TITLE
Update deps (minor) on server release group in the client release group

### PR DESCRIPTION
**Pull request by tylerbutler**
Updated the following:

  client (release group)

Dependencies on server updated:

  @fluidframework/gitresources: 1.0.0-1.0.0-175213
  @fluidframework/server-kafka-orderer: 1.0.0-175213
  @fluidframework/server-lambdas: 1.0.0-175213
  @fluidframework/server-lambdas-driver: 1.0.0-175213
  @fluidframework/server-local-server: 1.0.0-175213
  @fluidframework/server-memory-orderer: 1.0.0-175213
  @fluidframework/protocol-base: 1.0.0-175213
  @fluidframework/server-routerlicious: 1.0.0-175213
  @fluidframework/server-routerlicious-base: 1.0.0-175213
  @fluidframework/server-services: 1.0.0-175213
  @fluidframework/server-services-client: 1.0.0-175213
  @fluidframework/server-services-core: 1.0.0-175213
  @fluidframework/server-services-ordering-kafkanode: 1.0.0-175213
  @fluidframework/server-services-ordering-rdkafka: 1.0.0-175213
  @fluidframework/server-services-ordering-zookeeper: 1.0.0-175213
  @fluidframework/server-services-shared: 1.0.0-175213
  @fluidframework/server-services-telemetry: 1.0.0-175213
  @fluidframework/server-services-utils: 1.0.0-175213
  @fluidframework/server-test-utils: 1.0.0-175213

### CODE REVIEW

**Review by NicholasCouri — APPROVED** [review]

**Review by NicholasCouri — COMMENTED** [review]
We just need to rename the buildhierarchy calls or we will have build problems, I think

**Comment by tylerbutler** [comment]
@NicholasCouri I'm still not sure we should merge this, since it requires us changing client code to use the wrong name. We can merge this, but it's not required. We could instead prerelease another build and integrate that build, with the correct API name. Or go straight to releasing 1.0. Your call. I don't mind doing these extra steps for the experience, I just want to be clear what's necessary vs not. I won't be online much tomorrow, so ping the release engineers if anything can't wait until Friday.

**Comment by NicholasCouri** [comment]
> @NicholasCouri I'm still not sure we should merge this, since it requires us changing client code to use the wrong name. We can merge this, but it's not required. We could instead prerelease another build and integrate that build, with the correct API name. Or go straight to releasing 1.0. Your call. I don't mind doing these extra steps for the experience, I just want to be clear what's necessary vs not. I won't be online much tomorrow, so ping the release engineers if anything can't wait until Friday.

I'm ok either way. I can publish a new prerelease.

**Comment by tylerbutler** [comment]
@NicholasCouri I'm merging since the tests pass; I think we will need to update tinylicious before we release 6.0, but we can do that in separate commits.

**Comment by tylerbutler** [comment]
Related PR bumping tinylicious: #16380

**Pull request merged**
