### PR TITLE
Mark Experimental Packages Internal

### PR DESCRIPTION
**Pull request by anthony-murphy**
For our next major version Fluid Framework will be using explicit release tagging, and d.ts rollups to support public, beta, alpha, and internal. In preparation for that we are tagging everything internal to start, and then will carve out our other releases. Marking everything internal serves 2 purposes. 1) tags are inconsistently applied today, and it is easier to carve out a consistent set for each release type, rather than finding and fixing each miss application 2) which supports 1, inconsistent tags make tooling very hard and error prone to rollout, by making everything internal we have a consistent surface to enable our tooling upon, and this tooling will be used to inform our official carve outs.

related: 
https://github.com/microsoft/FluidFramework/pull/18409
https://github.com/microsoft/FluidFramework/pull/18408
https://github.com/microsoft/FluidFramework/pull/18411
https://github.com/microsoft/FluidFramework/pull/18412
https://github.com/microsoft/FluidFramework/pull/18410
https://github.com/microsoft/FluidFramework/pull/18413

### CODE REVIEW

**Review by Josmithr — COMMENTED** [review]
Changes look good to me from a mechanical perspective. I'd like to get confirmation from someone on the tree team, though, that we aren't going to break anything with the temporary change to `@internal` in `tree2`. Also want to make sure we aren't disrupting our partners with tag changes in the PropertyDDS packages.

@CraigMacomber I'm hoping you can offer some insight here.

**Comment by CraigMacomber** [comment]
> Changes look good to me from a mechanical perspective. I'd like to get confirmation from someone on the tree team, though, that we aren't going to break anything with the temporary change to `@internal` in `tree2`. Also want to make sure we aren't disrupting our partners with tag changes in the PropertyDDS packages.
> 
> @CraigMacomber I'm hoping you can offer some insight here.

If marking APIs in our experimental packages internal instead of alpha prevents third parties from being able to use them when they pick up the next release, that would be problematic. Additionally, we are in the process of landing https://github.com/microsoft/FluidFramework/pull/18524 to allow tree2 to differentiate its MVP API surface (which we plan to bug bash next week) from its unstable API surface, which is used by some third parties for prototyping/testing purposes for things after the MVP timeframe.

If `@internal` does not break third parties outside the repo yet, then we could adopt it for the things currently marked `@alpha`, but we still need a way to separate the two API levels with different tags.

tree2 currently does not have any APIs which we expect to be repo scoped (which I think is how we intend to use `@internal` long term), so renaming our alpha apis to internal doesn't lose any existing separation of APIs, but after https://github.com/microsoft/FluidFramework/pull/18524 lands, renaming both alpha and beta to the same thing would be lossy.

**Comment by CraigMacomber** [comment]
Most experimental packages are leaf packages which exist to let people try them and provide feedback (if they are internal only, they aren't published and arn't relevant here). Thus internal doesn't really make sense for them (their repo-internal APIs arn't package exported for the most part). "alpha" seems more logical.

**Comment by anthony-murphy** [comment]
> Most experimental packages are leaf packages which exist to let people try them and provide feedback (if they are internal only, they aren't published and arn't relevant here). Thus internal doesn't really make sense for them (their repo-internal APIs arn't package exported for the most part). "alpha" seems more logical.

@CraigMacomber  internal is just an intermediate state so that we can turn on validation that ensures all transitive dependencies within and between packages have compatible tagging. its pretty hard to get right manually, but we can skip tree2 if you think you can do it yourself.

**Comment by CraigMacomber** [comment]
> > Most experimental packages are leaf packages which exist to let people try them and provide feedback (if they are internal only, they aren't published and arn't relevant here). Thus internal doesn't really make sense for them (their repo-internal APIs arn't package exported for the most part). "alpha" seems more logical.
> 
> @CraigMacomber internal is just an intermediate state so that we can turn on validation that ensures all transitive dependencies within and between packages have compatible tagging. its pretty hard to get right manually, but we can skip tree2 if you think you can do it yourself.

Now that https://github.com/microsoft/FluidFramework/pull/18524 has landed, as long as internal isn't hidden in published packages, you should be fine to make all tree2's alpha APIs internal if you want, but ideally leave the beta ones alone for now if thats practical.

If that means opting tree2 out of automatic re-export validation, I think that would be good. We can fix that once IChannelFactory and IFluidHandle are stabilized or less type leaking alternatives are provided (that should be everything it reexports).

We can ensure its properly integrated into the repo wide release tagging validation before it becomes non-experimental to ensure it doesn't accidently imply satiability of other fluid types before we are ready.

**Review by Josmithr — APPROVED** [review]

**Pull request merged**
