### PR TITLE
Integrate latest prerelease of eslint-config-fluid throughout the repo and fix up errors

### PR DESCRIPTION
**Pull request by ChumpChief**
This includes the reenabling of many rules, so there are lots of fixups.

When there was any real risk of breakage I opted to disable the rule rather than make a risky change.  This was particularly true for the PropertyDDS packages, which are unique in that they never had the full set of eslint rules run against them before -- I enabled the prior limited set in #9192, which was during the period that the broader set of rules was disabled.  So don't be worried that I'm going disable-heavy on them, this is still the most linting they've seen.

### CODE REVIEW

**Comment by ChumpChief** [comment]
@heliocliu would also like your thoughts on whether I should also plan to follow up with a PR targeting `next`, since this is probably gonna be nasty to merge as the branches diverge.

**Comment by tylerbutler** [comment]
> @heliocliu would also like your thoughts on whether I should also plan to follow up with a PR targeting `next`, since this is probably gonna be nasty to merge as the branches diverge.

We'll always want to be able to make these sorts of changes, right? So whatever we do here we will likely repeat in the future for similar changes (e.g. moving packages to the strict config).

**Comment by heliocliu** [comment]
> @heliocliu would also like your thoughts on whether I should also plan to follow up with a PR targeting `next`, since this is probably gonna be nasty to merge as the branches diverge.

I'll be taking care of integrating changes from main to next until the automation is ready so you shouldn't need to worry about that.  Given how early we are into this I doubt there will be any conflicts when bringing this over.  In the future, the tooling should open a PR for you to resolve conflicts and merge to next if there are any

**Review by tylerbutler — APPROVED** [review]
:shipit:

**Pull request merged**
