### PR TITLE
Experiment: Replace lerna with yarn2 workspaces

### PR DESCRIPTION
**Pull request by tylerbutler**
**Note:** closely related to PR #4593.

This draft PR is an experiment of replacing our custom fluid-build tool and lerna with [yarn2
workspaces](https://yarnpkg.com/features/workspaces) and [lage](https://microsoft.github.io/lage/).

**Note:** using lage here is incidental. Fluid-build already paralellizes things efficiently, but I didn't have time to
make code changes to fluid-build.

We can decide on package manager vs "task runner" independently, including updating fluid-build as needed.

I do not intend to merge this in; I am sharing it in case anyone else is investigating speeding up the repo init
experience.

## Goals of the experiment:

- Speed up installation/bootstrapping of a new Fluid repo clone.
- Speed up experimentation with new packages or mass package upgrades (no lengthy lerna bootstrap step to change deps).
- Save disk space when using multiple Fluid repo clones.
- Determine what, if anything, doesn't work in this setup.

## How to try it

1. Install yarn globally: `npm i -g yarn`.
1. Run `yarn install`.
1. Use `yarn lage l-build` to run a build using lage.

Note that the **build will fail.** Likely with an error like this:

```
ERR! [@fluidframework/container-loader tsc] ERROR DETECTED
ERR! started
ERR! Running C:\Users\tylerbu\AppData\Local\Temp\xfs-a2e3f87a\yarn.EXE run tsc
ERR! src/container.ts:1210:26 - error TS2554: Expected 9 arguments, but got 8.
ERR!
ERR! 1210         const protocol = new ProtocolOpHandler(
ERR!                               ~~~~~~~~~~~~~~~~~~~~~~
ERR! 1211             attributes.minimumSequenceNumber,
ERR!      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERR!  ...
ERR! 1217             (key, value) => this.submitMessage(MessageType.Propose, { key, value }),
ERR!      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERR! 1218             (sequenceNumber) => this.submitMessage(MessageType.Reject, sequenceNumber));
ERR!      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERR!
ERR!   ../../../server/routerlicious/packages/protocol-base/dist/protocol.d.ts:24:299
ERR!     24     constructor(branchId: string, minimumSequenceNumber: number, sequenceNumber: number, term: number | undefined, members: [string, ISequencedClient][], proposals: [number, ISequencedProposal, string[]][], values: [string, ICommittedProposal][], sendProposal: (key: string, value: any) => number, sendReject: (sequenceNumber: number) => void);
ERR!


       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERR!     An argument for 'sendReject' was not provided.
ERR!
ERR!
ERR! Found 1 error.
ERR!
ERR! failed
```

That's the current state.

I got much further in the compilation progress, but things regressed somehow over the past few days. One thing to try is using yarn to build just the server packages first:

```
cd server/routerlicious
yarn workspaces foreach --topological-dev --parallel --verbose --interlaced run build:compile
```

Then go back to the root and try `yarn lage l-build` again. It might get further. You can also try building using yarn itself from the root of the repo:

```
yarn workspaces foreach --topological-dev --parallel --verbose --interlaced run tsc
```

## Workspace structure

Yarn supports nested workspaces to some extent, so it actually supports our repo structure pretty well already. Here's
the root workspace config:

```json
  "workspaces": [
    "packages/*/*",
    "examples/**",
    "server/historian/",
    "server/routerlicious/",
    "common/"
  ]
```

The last three entries are also _worktrees_ (more at
<https://yarnpkg.com/features/workspaces#how-to-declare-a-worktree>), and define subpaths that they encompass.

You can list all the workspaces using `yarn workspaces list`.

## Features

Yarn v2 seems particularly well suited to monorepo management. It will determine, based on the version numbers in
package dependencies, whether to install a package from npm or use the one in the repo. You can also [explicitly
define][1] these relationships and say I _always_ want the workspace version.

It also has some very nice interactive package management features. Try going to a non-React package in the repo and
typing `yarn add react-dom`. You can select from versions influenced by what is already used in the repo. You can also
try `yarn upgrade-interactive`.

It can help [deduplicate packages][2] within the repo: `yarn dedupe --check`

There are also things I haven't fully explored, like the [release workflows][3] and [constraints][4], but they look very
useful from a monorepo management perspective.

[1]: https://yarnpkg.com/features/workspaces#workspace-ranges-workspace
[2]: https://yarnpkg.com/cli/dedupe
[3]: https://yarnpkg.com/features/release-workflow
[4]: https://yarnpkg.com/features/constraints

### Known issues and caveats

Caching doesn't work. See https://github.com/microsoft/lage/issues/129 and https://github.com/microsoft/workspace-tools/issues/36.

### CODE REVIEW

**Comment by tylerbutler** [comment]
@znewton I've heard you might be interested in this.

**Comment by znewton** [comment]
We just successfully switched from Lerna+NPM to Yarn2+Lage in our project. So far, my favorite part is that lerna-package-lock.json and package-lock.json are now simply yarn.lock. Also, Lage seems to cover all our simple monorepo task needs that were previously provided by Lerna. 

However, my least favorite part is that our Azure DevOps pipeline installs tend to take a while. I'm going to look into [ADO Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsyarn) here soon, but I'm wondering if you've had any experience with speeding up Yarn installs both locally and in CI/CD?

**Comment by tylerbutler** [comment]
> We just successfully switched from Lerna+NPM to Yarn2+Lage in our project. So far, my favorite part is that lerna-package-lock.json and package-lock.json are now simply yarn.lock. Also, Lage seems to cover all our simple monorepo task needs that were previously provided by Lerna.
> 
> However, my least favorite part is that our Azure DevOps pipeline installs tend to take a while. I'm going to look into [ADO Pipeline Caching](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsyarn) here soon, but I'm wondering if you've had any experience with speeding up Yarn installs both locally and in CI/CD?

I haven't tried anything in CI yet, but locally, multiple installs are sped up by using the [global cache](https://yarnpkg.com/configuration/yarnrc#enableGlobalCache) (I've ignore the macOS warning - perhaps configuring a shared cache location manually would be a better approach).

For the best per we could investigate [zero-installs](https://yarnpkg.com/features/zero-installs) but I don't fully understand how they work and haven't experimented yet.

**Comment by znewton** [comment]
Looks like NPM 7 has workspace support: https://docs.npmjs.com/cli/v7/using-npm/workspaces
Could using NPM 7 Workspaces simplify the work here?


Also looks like Lerna v4.0.0 uses NPM 7 workspaces, although there's an open issue (lerna/lerna#2841) indicating that Lerna 4 is not usable right now.

**Comment by znewton** [comment]
Also, in FRS we're using `nodeLinker: node-modules` to avoid finickiness with PnP. What's your reasoning for using PnP and have you seen benefits?

**Comment by tylerbutler** [comment]
> Also, in FRS we're using `nodeLinker: node-modules` to avoid finickiness with PnP. What's your reasoning for using PnP and have you seen benefits?

My reasoning was that the point is to speed things up as much as possible, and PnP provides dramatic speed improvements in the not-very-scientific testing I've done. Using the node-linker didn't provide any speed advantages.

npm 7 workspaces are interesting, but IMO they're not quite ready for use in a repo like ours atm. I have done some preliminary testing and ran into issues but haven't had time to dig into them.

npm 7 _does_ seem to be faster in general than 6, regardless of workspaces.

**Comment by merceyz** [comment]
> It can help deduplicate packages within the repo: yarn workspaces foreach dedupe --check (it's kind of slow...)

That's because it runs on the whole Project so you're doing the same checks every time. `yarn dedupe --check` would be enough

**Comment by tylerbutler** [comment]
> > It can help deduplicate packages within the repo: yarn workspaces foreach dedupe --check (it's kind of slow...)
> 
> That's because it runs on the whole Project so you're doing the same checks every time. `yarn dedupe --check` would be enough

Ahhh, good point! I've updated this info in the issue. Thanks!

**Pull request closed without merging**
