### PR TITLE
build: Tag asserts

### PR DESCRIPTION
**Pull request by tylerbutler**
Tag asserts for the upcoming minor release (internal 6.4.0).

### CODE REVIEW

**Review by dannimad — APPROVED** [review]

**Comment by DLehenbauer** [comment]
@tylerbutler - Noticed you hit a failure in SharedTree tests.  It passed locally, and I see there was a recent checkin, so I restarted your job.

**Comment by tylerbutler** [comment]
> @tylerbutler - Noticed you hit a failure in SharedTree tests. It passed locally, and I see there was a recent checkin, so I restarted your job.

@DLehenbauer Thank you!

**Comment by tylerbutler** [comment]
Thanks for the review, @dannimad!

**Pull request merged**
