### PR TITLE
Revert `sharingLinkToRedeem` property in release/0.52

### PR DESCRIPTION
**Pull request by sonalivdeshpande**
This PR aims to restore the deprecated `sharingLinkToRedeem` property in release/0.52. The deprecated property was removed from the `IOdspResolvedUrl` interface and the alternative was `shareLinkInfo.sharingLinkToRedeem`.

### CODE REVIEW

**Comment by agarwal-navin** [comment]
Let's hold on to this change until we know for sure what is causing the issue - https://github.com/microsoft/FluidFramework/issues/8250

**Comment by agarwal-navin** [comment]
Can you add in the description the PR that added the change that you are reverting.

**Comment by agarwal-navin** [comment]
Can you make this change in main first and then patch it to 0.52

**Comment by sdeshpande3** [comment]
> Can you make this change in main first and then patch it to 0.52

PR to retore the property in main: https://github.com/microsoft/FluidFramework/pull/8406#issue-787333839

**Review by jatgarg — APPROVED** [review]

**Pull request merged**
