### PR TITLE
Wait for container connection before submitting ops

### PR DESCRIPTION
**Pull request by kian-thompson**
We are seeing a large number of "SubmitMessageWithNoConnection" errors for some tests. Some waits have been added to see if the flakiness is fixed.

[AB#7808](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/7808)

### CODE REVIEW

**Comment by agarwal-navin** [comment]
> We are seeing a large number of "" errors for some tests. Some waits have been added to see if the flakiness is fixed.
> 
> [AB#7808](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/7808)

What's the error the tests are hitting? This says "". Typo?

**Comment by vladsud** [comment]
@kian-thompson , while changes do not look problematic, I do not think they will fix the problem.
If you deal with DDSs, then DDSs (and runtime) will not send ops in disconnected state.

It will fix it only if test actually hacks things around and reaches directly to Loader layer to send ops.
Is that actually what you see / we are fixing?
I glanced at couple tests and I do not see that.

**Comment by anthony-murphy** [comment]
looking at the emission site of the error, and the data we collect, i think adding the stack would be useful to get an idea of where the offending submit is coming from, which should provide a better idea of how to fix it. So do something like:
```
			const eventName = "SubmitMessageWithNoConnection";
			this.mc.logger.sendErrorEvent(
				{
					eventName,
					type,
				},
				new LoggingError(eventName),
			);
```

**Comment by kian-thompson** [comment]
Closed for https://github.com/microsoft/FluidFramework/pull/20820

**Pull request closed without merging**
