### PR TITLE
Handle out of storage error from driver and make the container loadable

### PR DESCRIPTION
**Pull request by jatgarg**
## Description

Handle DriverErrorType.outOfStorage error from driver and load the container in readonly mode. Currently there is no handling and when the join session throws this error, the container will get closed. With this we use NoDeltaStream object as connection and load the container in read mode, so that it loads properly. We also notify the that the container is "readonly" through the event on delta manager so that apps can listen to this and show any UX etc. The app can listen to

```
container.deltaManager.on("readonly", (readonly?: boolean, readonlyConnectionReason?: { text: string, error?: IErrorBase}) => {
           // error?.errorType will be equal to DriverErrorType.outOfStorage in this case
          // App logic
 }
```

### CODE REVIEW

**Review by AndreiZe — APPROVED** [review]
LGTM

**Comment by agarwal-navin** [comment]
@sonalideshpandemsft @jatgarg @tylerbutler How come CI didn't run for this PR? This is causing a build break in this PR - https://github.com/microsoft/FluidFramework/pull/17156

**Comment by jatgarg** [comment]
I see the CI ran and passed too.

**Comment by agarwal-navin** [comment]
Huh, it doesn't show me that the CI ran in this PR.

**Comment by agarwal-navin** [comment]
Okay, I see it in "checks" tab but it doesn't show in the home page. Anyway, not sure why CI passed. It should have failed because of this PR - https://github.com/microsoft/FluidFramework/pull/16977. Maybe because of merge or something not sure (although Tyler's PR was merged 4 days ago and this one yesterday)

**Pull request merged**
