### PR TITLE
Add getEntries to the PromiseCache implementation.

### PR DESCRIPTION
**Pull request by NicholasCouri**

### CODE REVIEW

**Comment by markfields** [comment]
@NicholasCouri can you spell out the plan from here?  I kind of want to see how this will be used, so we can iterate on it before it gets locked in.

You can follow [these instructions](https://github.com/microsoft/FluidFramework/wiki/Compatibility-and-Versioning#testing-boundary-cross-changes-locally) to symlink dependencies on your local repo to be able to code against this without having a new version of common-utils published.  @andre4i or I can walk you through it if you run into trouble (I guarantee you will, I always do haha)

**Comment by markfields** [comment]
While you're making changes here, you might want to proactively prepare to fix the bug Vlad mentioned about the timers not being cleared when the container closes.  Maybe `PromiseCache` should implement `IDisposable` and on dispose clear all timers or something.  And maybe reach out to Vlad in case he has other concerns with the implementation.

I think it would also be nice to rename `GarbageCollector`, because we have a whole massive feature area about GC of stuff in the runtime, and it's a little confusing having this little utility on the side that's named this way.

**Comment by NicholasCouri** [comment]
I was actually planning on filing a new issue to address the timers not being cleared. Is that what you would normally do ?  In this new issue I could also add the renaming of the GarbageCollector. 🙂

I will hold of on both as your suggestion on the other PR seems reasonable as well.

________________________________

**Comment by markfields** [comment]
The reason I'm suggesting front-loading is to avoid multiple common-utils bumps because they are somewhat painful to consume.  But the priority of fixing the bug Vlad thought of may be low, so I understand if you just want to do the least effort to resolve the duplicate code.  But if you plan to come back to the other bug yourself while you're touching this area, I'd suggest doing the changes here now.

**Pull request closed without merging**
