### PR TITLE
Update Babel versions for security warning

### PR DESCRIPTION
**Pull request by ChumpChief**
Addresses https://github.com/microsoft/FluidFramework/security/dependabot/792

Updated our direct babel dependencies to most-recent (past affected version number `< 7.23.2`). The istanbul-instrumenter-loader dependency also pulled in the offending package and is apparently unused anyway, so removed it.

### CODE REVIEW

**Review by alexvy86 — APPROVED** [review]
LGTM

**Review by tylerbutler — CHANGES_REQUESTED** [review]
I want to review the lock file changes in more detail before signing off. I don't think you did anything wrong; I've just learned that pnpm can sometimes make unnecessary changes and need more time to review.

**Comment by tylerbutler** [comment]
Oh nvm, this was merged. Carry on.

**Comment by alexvy86** [comment]
FWIW I did try to look at it in detail, but didn't go line-by-line. My "sampling" didn't reveal anything concerning.

**Comment by ChumpChief** [comment]
> FWIW I did try to look at it in detail, but didn't go line-by-line. My "sampling" didn't reveal anything concerning.

Same, I was scanning as I made various changes to the package.jsons (mostly to watch and see the offending dependency go away).  I didn't see anything surprising offhand.

**Pull request merged**
