### PR TITLE
chore: Stop including unnecessary files in published packages (packages/dds)

### PR DESCRIPTION
**Pull request by alexvy86**
## Description

Start of moving to `package.json`'s `files` property to determine the exact files that get into published packages. This PR only applies the change to the 14 packages within `packages/dds`, which have few changes in the final files that get published and are easy to analyze.

A whitelisting approach is more robust against including files by mistake and would make it more obvious if we missed adding something that is necessary. My plan is to move the whole repo to this approach if there are no objections.

## Reviewer Guidance

The contents of `package.json`'s `files` is the same in all the updated packages:

```json
"files": [
  "dist/**",
  "!dist/test/**",
  "lib/**",
  "src/**",
  "!src/test/**"
],
```

- Feedback welcome on reasons why we should _not_ do this, or why we should keep some of the affected files. E.g. there's an argument that might suggest we keep `tsconfig.*.json`, to allow consumers to re-compile the packages from the source code (which we include already) for a different target (CommonJS/ESM, es6/es2017/es2020/etc). Do we even want to make this a possibility? I don't expect we'd support it.

Below are diffs showing the files that stopped being published for each package. The following are common for almost all packages:
```
.eslintrc.js
.mocharc.js
CHANGELOG.md
api-extractor.json
prettier.config.cjs
tsconfig.esnext.json
tsconfig.json
```

Some diffs show files that don't really go into the published package but ended up here as part of the packing process when run locally several times (e.g. `map.test-files.tar` for `@fluidframework/map` or `matrix.test-files.tar` for `@fluidframework/matrix`).

Some packages do show other files that were being included but seem ok to not include, like the `bench/` folder for `@fluidframework/matrix` and `@fluidframework/shared-object-base`, or the `docs/` and `.vscode/` folders for `@fluidframework/merge-tree` and `@fluidframework/sequence`. `@fluid-internal/test-dds-utils` is a bit of an outlier in its changes but they also look correct.

fluid-experimental-pact-map
fluidframework-cell
fluidframework-counter
fluidframework-ink
fluidframework-map
fluidframework-matrix
fluidframework-merge-tree
fluidframework-ordered-collection
fluidframework-register-collection
fluidframework-sequence
fluidframework-shared-object-base
fluidframework-shared-summary-block
fluidframework-task-manager
fluid-internal-test-dds-utils

[AB#4135](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4135)

### CODE REVIEW

**Comment by tylerbutler** [comment]
> Feedback welcome on reasons why we should not do this, or why we should keep some of the affected files.

My main concern with this change is that it can be a "timebomb" that detonates only at package publish time, which is when the stakes are highest.

Most developers don't think about what's in the published package when they're making changes, and the current approach protects against mistakes of that kind.

That said, one thing we could do to make this safer is add a simpler way for people to verify that the contents of the package is whey expect, and a build step that breaks if anything's added but not published.

It may be a controversial option, but I like build steps that force acknowledgement of a "side effect" to a change. Type tests are an example of this.

**Comment by alexvy86** [comment]
> My main concern with this change is that it can be a "timebomb" that detonates only at package publish time, which is when the stakes are highest.
> Most developers don't think about what's in the published package when they're making changes, and the current approach protects against mistakes of that kind.

True. It goes both ways somewhat (with different degrees of impact to each side, granted). In #15560 I discovered that `@fluidframework/aqueduct` and `@fluidframework/data-object-base` are 50% and 200% bloated because of the inclusion of a file that doesn't need to be in the package. It doesn't impact the bundle size for a webapp and arguably our package size isn't _as_ critical for a Node app, so not the end of the world, but I still consider it an error on our part.

That said, I agree that if we're not thinking about what's in the published package, it's (potentially much) worse to fail to include something functional VS failing to notice something unnecessary sneaked in. Case in point, we just had to deal with issues because `@fluentui/react` and its related packages [recently published borked versions that stopped including important folders that were there before](https://github.com/microsoft/fluentui/issues/27732). But that seems like a low probability thing for our packages given how homogeneous they are; most of them just need to keep publishing `dist/`, `lib/`, and `src/` (with the tests excluded). The few that do something "special" regarding the files they need to include seem to be our internal tooling ones like mocha-test-setup or eslint-build-config.

I guess part of my motivation is that I think we _should_ start being more deliberate about what goes in the published packages; make it second nature. And our standard setup for a package probably has us covered in 99% of cases already, so to me the risk feels relatively low.

> That said, one thing we could do to make this safer is add a simpler way for people to verify that the contents of the package is what they expect, and a build step that breaks if anything's added but not published.
> It may be a controversial opinion, but I like build steps that force acknowledgement of a "side effect" to a change. Type tests are an example of this.

I don't have anything against the approach in general, but I'm trying to think of how it applies here and don't like the result. Feels like we have to maintain an explicit list of either the exact files (not globs, or we risk edge cases where we miss something) that we want in there or the exact files we don't want in there, and both options feel... unwieldy.

**Comment by Josmithr** [comment]
I echo @tylerbutler's general concerns. If we do miss something, we likely won't discover it until we're customers try using our newly published package versions.

> > That said, one thing we could do to make this safer is add a simpler way for people to verify that the contents of the package is what they expect, and a build step that breaks if anything's added but not published.
> > It may be a controversial opinion, but I like build steps that force acknowledgement of a "side effect" to a change. Type tests are an example of this.
> 
> I don't have anything against the approach in general, but I'm trying to think of how it applies here and don't like the result. Feels like we have to maintain an explicit list of either the exact files (not globs, or we risk edge cases where we miss something) that we want in there or the exact files we don't want in there, and both options feel... unwieldy.

It would be nice to at least have a utility that generates a report of what files would be published given a package's config (post build). That way devs could easily audit any changes they make to the config. This would be useful in either world (`npmIgnore` or `files`). CI enforcement would be nice, but as @alexvy86 noted, it likely amounts to maintaining an explicit list of files, which would likely not scale well. But just having a utility to generate a report that we could include in PR descriptions when making publish config changes would be useful.

**Comment by alexvy86** [comment]
I opened #15573 which addresses some of the concerns here (and in the related PRs) but sticking to our current `.npmignore` approach (except two packages because they already use `files`; we can debate separately if we should change that).

**Pull request closed without merging**
