### PR TITLE
release notes for minor 7.4

### PR DESCRIPTION
**Pull request by dannimad**
As part of preparation for next 7.4.0 minor release.

### CODE REVIEW

**Comment by dannimad** [comment]
I believe they are removed when generating the changelogs as I see happening here https://github.com/microsoft/FluidFramework/pull/18020/files

**Comment by dannimad** [comment]
Should we anticipate to that and manually removed change sets?

**Comment by tylerbutler** [comment]
I'll push some updates to this PR to reword things according to our guidelines and reorder them.

**Comment by CraigMacomber** [comment]
> Should we anticipate to that and manually removed change sets? This is in anticipation of 7.4 and I believe we shouldn't expect/allow more changesets after this change and before the release. Maybe this rule works well for minor releases but not so much for major.

I didn't realize our process involved duplicating this information across release notes and change logs. Given that, I guess we just follow the process, and try and keep them in sync. I do think it would be good to fix our process so if someone makes a changeset in-between we don't end up with it in the changelog and not the release notes though.

Maybe we will want to adjust our process in the future: A properly atomic way to do it is on the release branch then merge that back into main

**Review by tylerbutler — APPROVED** [review]

**Pull request merged**
