### PR TITLE
Add flub setInterdependencyRange

### PR DESCRIPTION
**Pull request by CraigMacomber**
## Description

Adds new command to flub `setInterdependencyRange` intended for use by release pipeline to replace its use of flub bump.

Also cleans up some related code in flub bump.

Once this is adopted, dependency modification support can be removed from `flub bump`, simplifying its responsibilities.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

### CODE REVIEW

**Comment by tylerbutler** [comment]
Can you explain the problems that these changes are intended to address?

**Comment by tylerbutler** [comment]
Thanks, that makes sense. I think what confused me is the removal of the step in ci that sets the versions. It makes sense to separate the functions, but the set version step still needs to be run I think.

I'll look more closely at the changes tomorrow. I likely missed something.

High level I wonder if changing the default interdependency range to "don't change the range" be a smaller and simpler change? Perhaps that doesn't charge the larger debt goals though.

**Comment by CraigMacomber** [comment]
> Thanks, that makes sense. I think what confused me is the removal of the step in ci that sets the versions. It makes sense to separate the functions, but the set version step still needs to be run I think.

This does not make any CI changes (yet), but I think you are right about it missing something.

For all normal releases, setting the version during publish is unnecessary since it's done during the version bump before the branch is forked, but I think prerelease builds still need to set it since they lack such a version bump. Having them use the version bump command for that part of the change (to mirror how its done for regular releases) seems like it would make sense.

That said, I still think separating the logic for those two changes is cleaner, since we already rewrite the package.json twice using different approaches for each. 

> I'll look more closely at the changes tomorrow. I likely missed something.
> 
> High level I wonder if changing the default interdependency range to "don't change the range" be a smaller and simpler change? Perhaps that doesn't charge the larger debt goals though.

Refactoring bump to make the package.json updates in a single pass, and having the tool have optional flags for setting the version and for setting the dependency ranges would be another relatively clean way to refactor this.

Having a single utility for editing package.json files with lots of flags for optional edits to perform, but does nothing by default might be a nice design to unify several of our tools (dependency updating tools, version bump, type test configuration) into one much simpler and much more performant utility.

then we could do something like this if a user wanted to change both at once, but could also change either one:

`flub editPackage -g client --version=2.4.4 --interdependencySchema="workspace:~"`

I think that could make sense and be much easier to understand.

Currently we have "bump" able to do things that don't sound like version bumping (like setting the version to a prerelease version, or replacing workspace ranges), and having it do those things unconditionally (you need to request them be set to their current value to not modify them): I find that very confusing (for example its why I thought the publish tooling didn't need the version change, since its very hard to tell why a script is using bump from its invocation since you can't easily tell which of its changes are intended to no-op) and hard to use (easy to accidently not no-op things you don't want to change, like how flub release broke the dependency ranges when just tiring to bump the versions).

**Comment by tylerbutler** [comment]
> That said, I still think separating the logic for those two changes is cleaner, since we already rewrite the package.json twice using different approaches for each.

I agree. "Bump" as a command is one of the earliest we made and it inherited some weirdness from our early processes, and then has ballooned in capabilities over time. From where we stand now, I think a separate "modify the interdep ranges" command makes clear sense. Your other suggestions are also reasonable to me, but I am a fan of this overall approach - smaller focused commands that can be combined if needed.

**Comment by tylerbutler** [comment]
Also - Oclif has good support for aliases now, so renaming commands is possible and straightforward. With that in mind, perhaps bump should be renamed to e.g. modify:version? Separate from everything else, bump doesn't seem like the best verb.

**Pull request closed without merging**
