### PR TITLE
docs(tree): improve docs for move destination index argument

### PR DESCRIPTION
**Pull request by yann-achard-MS**
## Description

Most users of the move APIs have reported confusion about its semantics. While a better API is desirable, it will take some time to arrive (and the current API will remain available for back-compat), so this PR attempts to clarify the semantics of the existing API.

## Breaking Changes

None

## Reviewer Guidance

The doc changes are the same across all 4 versions of this method, so reviewing one should be sufficient.

### CODE REVIEW

**Review by kian-thompson — APPROVED** [review]

**Review by alexvy86 — APPROVED** [review]
It's a great improvement! I think I'd still mention explicitly that `destinationIndex` refers to the spaces _between_ the array items, while the `sourceIndex` refers to the items themselves. At least for me that makes things a lot clearer once I grasp it. If we have good terminology to differentiate them, I might also use it to further distinguish the arguments.

ChatGPT suggests:
> For the index that refers to the "spaces between items," you could use terms that emphasize the position between elements. Here are a few suggestions:
> - ItemIndex and GapIndex
> - ElementIndex and SlotIndex
> - ItemIndex and PositionIndex
> - ElementIndex and InsertionPoint
> - ItemIndex and Breakpoint
> - ElementIndex and DividerIndex

I'm not in love with any of them, but maybe something along the lines of insertion point. "Slot" and "position" to me still could refer to the items themselves.

**Comment by Josmithr** [comment]
> It's a great improvement! I think I'd still mention explicitly that `destinationIndex` refers to the spaces _between_ the array items, while the `sourceIndex` refers to the items themselves. At least for me that makes things a lot clearer once I grasp it. If we have good terminology to differentiate them, I might also use it to further distinguish the arguments.
> 
> ChatGPT suggests:
> 
> > For the index that refers to the "spaces between items," you could use terms that emphasize the position between elements. Here are a few suggestions:
> > 
> > * ItemIndex and GapIndex
> > * ElementIndex and SlotIndex
> > * ItemIndex and PositionIndex
> > * ElementIndex and InsertionPoint
> > * ItemIndex and Breakpoint
> > * ElementIndex and DividerIndex
> 
> I'm not in love with any of them, but maybe something along the lines of insertion point. "Slot" and "position" to me still could refer to the items themselves.

What terminology does merge-tree use? Presumably we'd want to align that that.

**Comment by noencke** [comment]
> > It's a great improvement! I think I'd still mention explicitly that `destinationIndex` refers to the spaces _between_ the array items, while the `sourceIndex` refers to the items themselves. At least for me that makes things a lot clearer once I grasp it. If we have good terminology to differentiate them, I might also use it to further distinguish the arguments.
> > ChatGPT suggests:
> > > For the index that refers to the "spaces between items," you could use terms that emphasize the position between elements. Here are a few suggestions:
> > > 
> > > * ItemIndex and GapIndex
> > > * ElementIndex and SlotIndex
> > > * ItemIndex and PositionIndex
> > > * ElementIndex and InsertionPoint
> > > * ItemIndex and Breakpoint
> > > * ElementIndex and DividerIndex
> > 
> > 
> > I'm not in love with any of them, but maybe something along the lines of insertion point. "Slot" and "position" to me still could refer to the items themselves.
> 
> What terminology does merge-tree use? Presumably we'd want to align that that.

InIndex

**Comment by yann-achard-MS** [comment]
> > > It's a great improvement! I think I'd still mention explicitly that `destinationIndex` refers to the spaces _between_ the array items, while the `sourceIndex` refers to the items themselves. At least for me that makes things a lot clearer once I grasp it. If we have good terminology to differentiate them, I might also use it to further distinguish the arguments.
> > > ChatGPT suggests:
> > > > For the index that refers to the "spaces between items," you could use terms that emphasize the position between elements. Here are a few suggestions:
> > > > 
> > > > * ItemIndex and GapIndex
> > > > * ElementIndex and SlotIndex
> > > > * ItemIndex and PositionIndex
> > > > * ElementIndex and InsertionPoint
> > > > * ItemIndex and Breakpoint
> > > > * ElementIndex and DividerIndex
> > > 
> > > 
> > > I'm not in love with any of them, but maybe something along the lines of insertion point. "Slot" and "position" to me still could refer to the items themselves.
> > 
> > 
> > What terminology does merge-tree use? Presumably we'd want to align that that.
> 
> InIndex

I liked the idea of matching merge-tree terminology before Noah helpfully told us what it is. 🤔
See also the conversation [here](https://teams.microsoft.com/l/message/19:UeM7wzqFgq-G3Ht1TUfsd3OTyJIf5fGm8f4uwfytZps1@thread.skype/1725466420864?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9ce27575-2f82-4689-abdb-bcff07e8063b&parentMessageId=1725466420864&teamName=Fluid%20Framework&channelName=Shared%20Tree%20Users&createdTime=1725466420864&ngc=true&allowXTenantAccess=true).

**Comment by noencke** [comment]
> > > > It's a great improvement! I think I'd still mention explicitly that `destinationIndex` refers to the spaces _between_ the array items, while the `sourceIndex` refers to the items themselves. At least for me that makes things a lot clearer once I grasp it. If we have good terminology to differentiate them, I might also use it to further distinguish the arguments.
> > > > ChatGPT suggests:
> > > > > For the index that refers to the "spaces between items," you could use terms that emphasize the position between elements. Here are a few suggestions:
> > > > > 
> > > > > * ItemIndex and GapIndex
> > > > > * ElementIndex and SlotIndex
> > > > > * ItemIndex and PositionIndex
> > > > > * ElementIndex and InsertionPoint
> > > > > * ItemIndex and Breakpoint
> > > > > * ElementIndex and DividerIndex
> > > > 
> > > > 
> > > > I'm not in love with any of them, but maybe something along the lines of insertion point. "Slot" and "position" to me still could refer to the items themselves.
> > > 
> > > 
> > > What terminology does merge-tree use? Presumably we'd want to align that that.
> > 
> > 
> > InIndex
> 
> I liked the idea of matching merge-tree terminology before Noah helpfully told us what it is. 🤔 See also the conversation [here](https://teams.microsoft.com/l/message/19:UeM7wzqFgq-G3Ht1TUfsd3OTyJIf5fGm8f4uwfytZps1@thread.skype/1725466420864?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=9ce27575-2f82-4689-abdb-bcff07e8063b&parentMessageId=1725466420864&teamName=Fluid%20Framework&channelName=Shared%20Tree%20Users&createdTime=1725466420864&ngc=true&allowXTenantAccess=true).

I was actually trying to reply to an earlier message, not that one, and then I typed the wrong thing anyway, and then I clicked "close with comment" by accident when trying to cancel my comment, which actually closed your PR, and so I gave up and closed the web page, I am bad at github sorry for the confusion

**Review by noencke — APPROVED** [review]

**Review by alexvy86 — APPROVED** [review]

**Pull request merged**
