### PR TITLE
Policy-Check: Allow package-lock.json with no dependencies

### PR DESCRIPTION
**Pull request by DLehenbauer**
@tylerbutler - the reason NPM v7 has been slipping through policy-check is that we hadn't yet deployed a version of the build-tools that contains my update.

I went to manually deploy these this morning and found that I first need to make a tweak to my regex.  Our repo now contains a generated 'package-lock.json' that has no dependencies (and therefore no trailing comma after '"lockFileVersion": 1').

### CODE REVIEW

**Review by anthony-murphy — APPROVED** [review]

**Comment by DLehenbauer** [comment]
Thanks, @anthony-murphy !

**Comment by tylerbutler** [comment]
Nice -- thanks for the fix @DLehenbauer!

**Comment by tylerbutler** [comment]
Let me know if you'd like me to do the version bump dance for you. I know it's annoying. :)

**Comment by DLehenbauer** [comment]
I'd already kicked off the pipeline, but I appreciate the offer.  Might take you up on it next time.  :-)

**Pull request merged**
