### PR TITLE
Deprecate Interval APIs intended to be internal

### PR DESCRIPTION
**Pull request by Abe27342**
## Description

inheritdoc doesn't copy release tags. This marks functions implementing an internal method in `Interval` and `SequenceInterval` deprecated, so we can mark them internal in a future release.

Ideally we would clean up API surface here; exporting the classes isn't great in the first place and there's not a strong reason we need to.

### CODE REVIEW

**Comment by Abe27342** [comment]
i'm open to doing a proper breaking change notification for this. main reason I didn't is I think it's unlikely we'll actually change these APIs. the main reason I wanted to mark these is `addProperties` looks plausibly like an intended public API. But it doesn't submit any ops.

**Comment by alexvy86** [comment]
I lean towards yes announced breaking change, even when I agree it's improbable that someone is using them.

**Comment by Abe27342** [comment]
> I lean towards yes announced breaking change, even when I agree it's improbable that someone is using them.

Fair enough. not too much extra effort and would be a decent amount of pain for consumers if my assumption is wrong. updated to deprecate all the APIs instead.

**Review by alexvy86 — APPROVED** [review]

**Review by ChumpChief — APPROVED** [review]
Love to see it :)

Agree you might as well include a BREAKING.md announcement if you're already going through the trouble of deprecate-in-main-remove-in-next.

**Pull request merged**
