### PR TITLE
Refactor demo application to support creating of new container

### LINKED ISSUE #10025: Make data migration demo "cycle" the exported data back into a new container running the same container code

### PR DESCRIPTION
**Pull request by alpaix**
Refactor of the schema upgrade demo application to make it capable of creating new containers and applying migration logic.

Resolves #10025

### CODE REVIEW

**Comment by ChumpChief** [comment]
Couple thoughts on initial look:

1. Let's keep the stop/extract/create flow away from the view as best we can -- two reasons for this:
    1. We need to demonstrate to customers that this flow is not dependent on a view framework like React
    2. It seems reasonable that some customers may want to run this flow using an agent or other headless client
2. Let's retain the view of the imported data source separate from the exported data -- this way it's easier for the user to compare the in/out data.

**Comment by alpaix** [comment]
@ChumpChief  I addressed your feedback. Please take a look.

**Comment by ChumpChief** [comment]
Just gave the demo a try, seems there are maybe some bugs in the state transitions?  I'm seeing the new container button doesn't always seem to work esp. after page refresh.  Will take a closer look as well but wanted to let you know early.

**Comment by alpaix** [comment]
It might take some time for the kill bit to process messages. I noticed a delay of a few seconds. The UI in its current state doesn't provide any visual feedback on a long operation.

**Comment by alpaix** [comment]
Link to AB#302

**Review by ChumpChief — APPROVED** [review]
Thanks for investigating the issue -- let's go ahead with this for now and we can iterate on the UI on further changes.

**Pull request merged**
