### PR TITLE
fix(ci): Update stage dependencies for accurate telemetry reporting

### PR DESCRIPTION
**Pull request by alexvy86**
## Description

This PR updates the stage dependencies for the stage that uploads pipeline telemetry to Kusto, so it runs after the stages that publish npm packages (if they exist).

This addresses an issue where failures in the stages that publish npm packages do not create IcM incidents because the telemetry reported them as "in progress" when the telemetry-reporting stage ran, and didn't see them fail once they completed.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

[This run](https://dev.azure.com/fluidframework/internal/_build/results?buildId=221710&view=results) (msft internal) for this test branch (plus a small update to the condition that enables the telemetry-reporting stage, so it would show up for a manually triggered run) shows things looking as expected.

### CODE REVIEW

**Review by WayneFerrao — APPROVED** [review]
Looks great! 
NIT: Maybe update the PR name/commit to "Update stage dependencies for accurate telemetry reporting"

**Comment by alexvy86** [comment]
I'll wait until the 8.0 release is cut and main is unlocked, to merge this. Just in case something funky could happen in scenarios that I cannot test with a test/ branch.

**Pull request merged**
