### PR TITLE
tools: Simplify app startup scripts and remove tsfmt scripts and dependency

### PR DESCRIPTION
**Pull request by Josmithr**
Updates the `start` pattern to not require running `tinylicious` in a separate terminal.

Also removes `typescript-formatter` scripts and dependency, which are obsolete with `prettier`.

### CODE REVIEW

**Comment by ChumpChief** [comment]
I believe we've had issues in the past with keeping the version of tinylicious up to date -- maybe consider using npx for this script (this is what we do in [FluidExamples](https://github.com/microsoft/FluidExamples))

**Comment by Josmithr** [comment]
> I believe we've had issues in the past with keeping the version of tinylicious up to date -- maybe consider using npx for this script (this is what we do in [FluidExamples](https://github.com/microsoft/FluidExamples))

Happy to make that change, but there are other packages already directly depending on tinylicious this way. We may need to clean that up?

**Review by tylerbutler — COMMENTED** [review]
Could you update the external-controller example in azure at the same time?

**Comment by Josmithr** [comment]
> Could you update the external-controller example in azure at the same time?

I think I would rather do it as a separate PR, but I am happy to make the same changes there as soon as this goes in :)

**Review by tylerbutler — APPROVED** [review]

**Pull request merged**
