### PR TITLE
New serialized data format in testdata

### PR DESCRIPTION
**Pull request by dannimad**
New try to test new detached format added in testdata repo. See https://github.com/microsoft/FluidFramework/pull/18829 for more info

### CODE REVIEW

**Comment by anthony-murphy** [comment]
can you verify the new test data in running in a test, basically just look it up in the CI pipeline output, maybe add a link here if possible.

**Comment by dannimad** [comment]
there are the new tests that use new serialized container data format. Links coming from passing CI pipeline:
Rehydrate container from newSerializedContainer.json and check contents before attach
https://dev.azure.com/fluidframework/public/_build/results?buildId=231355&view=ms.vss-test-web.build-test-results-tab&runId=5125622&resultId=100004&paneView=debug

Rehydrate container from newSerializedContainer.json round trip serialize/deserialize
https://dev.azure.com/fluidframework/public/_build/results?buildId=231355&view=ms.vss-test-web.build-test-results-tab&runId=5125622&resultId=100005&paneView=debug

**Review by anthony-murphy — COMMENTED** [review]
Looks good. Approving, but you need to commit the test data first or you will break CI. If you provide a link from here, i'll approve that to.

**Comment by dannimad** [comment]
test data repo PR: https://github.com/microsoft/FluidFrameworkTestData/pull/64

**Review by anthony-murphy — APPROVED** [review]

**Pull request merged**
