### PR TITLE
Rename generateSummary to submitSummary

### PR DESCRIPTION
**Pull request by arinwt**
In ContainerRuntime, I think generateSummary is a misleading name, since it also uploads it to storage and posts the summarize op. I propose renaming it to submitSummary.

Also added more detailed comments above it.

### CODE REVIEW

**Review by markfields — COMMENTED** [review]
This seems sensible, but I'm curious about the value of the churn. Like, is there something else you want to refer to as "generate summary" and want to avoid confusion?  Also, it looks like you're not updating the event name in telemetry, which is nice for the short term (queries/aggregation won't be broken), but would it be worth aligning everywhere with the new nomenclature?

**Comment by arinwt** [comment]
I was just thinking readability since right now this function isn't really exposed much or used outside of our code.

Yeah for the event name I kinda went back and forth.. What do you think?

**Comment by markfields** [comment]
Cool. Since this is mostly internal implementation details, sounds like a good change. And if there's not some critical distinction between generate and submit nomenclature, then I agree with leaving telemetry as-is.

**Review by markfields — APPROVED** [review]
🎂 LGTM

**Pull request merged**
