### PR TITLE
Remove container creation in load flow for container

### PR DESCRIPTION
**Pull request by jatgarg**
1.) Remove creation of container in loader.resolve/container.load. Only use this flow for loading of an existing container.
2.) For creation of container only use loader.createDetached() flow.

### CODE REVIEW

**Comment by jatgarg** [comment]
I think I need to handle this first: https://github.com/microsoft/FluidFramework/issues/4049. Here we we will load from oldest snapshot when loaderheader.version === null.

**Comment by tylerbutler** [comment]
@jatgarg Is this PR still relevant?

**Comment by jatgarg** [comment]
Closing it with new PR.

**Comment by agarwal-navin** [comment]
Can you link the new PR here?

**Comment by jatgarg** [comment]
Yes, in process of opening one.

**Comment by jatgarg** [comment]
This PR removes Loader version as null. https://github.com/microsoft/FluidFramework/pull/6358
We have kept some legacy path in container.load() mostly for testing purposes like snapshot tests.

**Pull request closed without merging**
