### PR TITLE
Prepare for protocol-definitions 2.0.0 typing changes in client

### PR DESCRIPTION
**Pull request by ChumpChief**
Similar to #15380, #15382, and #15401. Counterpart to #16317 (which was for server).  [AB#4933](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4933)

Similar to #16317, this prefers to cast and make no changes to generated code in most places, rather than introduce typeguards or other checks.  It is also safe to merge in `main` immediately, since it's simply now asserting the assumed types explicitly.

In general, clientId is always casted back to `string` for now.  Several of these should really be capable of handling `null` too, but in most cases this change would end up crossing a public API surface at some point and need to go in `next`.  Others should be protected against ever getting a `null`.

`contents` gets a wide variety of casts depending on whose contents we're talking about.  I hesitate to establish formal interfaces for these as many of them are inappropriate accesses anyway (see below).

These casts end up being really ugly in a lot of places, but that's great!  Because this helps highlight a few trends that I noticed while doing the fixup:
* Using secret knowledge to unpack and even mutate `contents` from places that are not the owners of the format - secretly making the format a semi-public API surface to worry about
* Failing to use strong typing on `contents` even from places that are the owners of the format
* Op sniffing, e.g. watching ops on the DeltaManager directly rather than normal routing
* Spaghetti-types, in particular ISequencedDocumentMessage.  We should cut these up at the layer boundaries - i.e. maybe ISequencedDocumentMessage should describe specifically the format of the message handed from the DeltaManager to the ContainerRuntime, but should not then carry through to the data stores and instead be repackaged into an even-more-strongly-typed interface (e.g. maybe ContainerRuntime should guarantee non-null clientId to datastores).

In any case, these casting warts are easy to spot and attack, so I think it's healthy to call them out explicitly here as a first step.  I'm super-excited to get these out of "any" status.  I also added some TODOs for the places I was particularly concerned about to draw attention.

When ingesting protocol-definitions 2.0.0 there are a number of `// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion` that we'll just remove relating to making clientId nullable.

### CODE REVIEW

**Comment by anthony-murphy** [comment]
My only worry with introducing so much casting is that it may appear to be a pattern that should be used, rather than a pattern that should not be used. Not sure if we can do anything about that. Maybe we can also file some bugs, maybe under tech debt to at least have some tracking around clean up in this area.

**Comment by ChumpChief** [comment]
> My only worry with introducing so much casting is that it may appear to be a pattern that should be used, rather than a pattern that should not be used. Not sure if we can do anything about that. Maybe we can also file some bugs, maybe under tech debt to at least have some tracking around clean up in this area.

I could add more TODO type comments if you like, and happy to open bugs - I don't think folks will go look at the bug database when deciding whether to replicate a pattern though, so I think any deterrent needs to live next to the code.

**Comment by anthony-murphy** [comment]
> > My only worry with introducing so much casting is that it may appear to be a pattern that should be used, rather than a pattern that should not be used. Not sure if we can do anything about that. Maybe we can also file some bugs, maybe under tech debt to at least have some tracking around clean up in this area.
> 
> I could add more TODO type comments if you like, and happy to open bugs - I don't think folks will go look at the bug database when deciding whether to replicate a pattern though, so I think any deterrent needs to live next to the code.

agreed. i also don't love a bunch of TODO comments, especially if they linger. ideally, we can just get the work scheduled soonish.

**Review by anthony-murphy — APPROVED** [review]
please wait for @kian-thompson and/or @andre4i  to take a look as they are actively working in the area, so should be aware this is coming.

**Comment by ChumpChief** [comment]
Opened AB#4934 and a number of tasks under it to track the followups from this PR.

**Review by kian-thompson — APPROVED** [review]
Looks good to me.
I remember there were some thoughts on whether we should change the `contents` type to simply be a `string` on these interfaces since that's technically what we send and receive from service (though I'm not sure if this was the case in the past). This is something that can definitely be done later but figured it's worth calling out.

**Comment by ChumpChief** [comment]
> I remember there were some thoughts on whether we should change the contents type to simply be a string on these interfaces since that's technically what we send and receive from service

That's a great point - one of the tasks I opened was about splitting the ISequencedDocumentMessage interface on layer boundary (in part because of ownership of the contents format, and related to the spaghetti-types problem I mention in the description).
* From the service's perspective, it should probably treat the contents as `unknown` (i.e. don't try to inspect them, make no assumptions about their contents)
* From the deltaManager's perspective, maybe a string?
* From the containerRuntime's perspective, the contents should probably be an IEnvelope?

I'll add some notes to that task on this point.

**Comment by ChumpChief** [comment]
Merging now to avoid further conflicts, but please do let me know if you want any followups @andre4i

**Pull request merged**
