### PR TITLE
SharedString: Move to ECMAScript Private Fields

### PR DESCRIPTION
**Pull request by anthony-murphy**
This change moves most usages of private member properties to use ECMAScript Private Fields. This brings stronger isolation to our classes and further reduces our available surface area for typescript and javascript users:
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#ecmascript-private-fields
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

### CODE REVIEW

**Comment by christiango** [comment]
Are there any breaking change docs we need to update? Ideally folks shouldn't have been depending on typecasts to access private members, but surely some folks have been so it might be nice to give a "heads up" in the upgrade docs.

**Comment by christiango** [comment]
Any eslint rules we can add to nudge developers in the private field direction instead of the typescript private methods/properties?

**Comment by christiango** [comment]
One thing to keep an eye on is the bundle size impact since I believe Typescript transpiles this into something pretty verbose when the target is not esnext (though maybe it is also available in earlier targets)

**Comment by christiango** [comment]
I'll be going on vacation momentarily so don't block on me here. I like the direction of the change, my only concern would be how much bloat this adds to downstream consumers. Would be good to double check our bundle analysis both for this PR and on the corresponding package bump for the internal product repo.

**Comment by anthony-murphy** [comment]
I'm hoping this won't break anything, and it's pretty hard to know if we do. I think the best way to find out what breaks is to try and see. I will add a breaking note to that effect.

I looked briefly for an eslint rule, but didn't see one. its a good idea.

bundle size is a good call out.

**Comment by tylerbutler** [comment]
Regarding linting, use the [no-restricted-syntax](https://eslint.org/docs/rules/no-restricted-syntax) rule.

**Comment by tylerbutler** [comment]
Also relevant: https://github.com/typescript-eslint/typescript-eslint/issues/1391

**Comment by anthony-murphy** [comment]
looks like this has some unintuitive interactions with things like Object.create. closing this for now.

**Comment by pleath** [comment]
I'm curious...what are the interactions with Object.create that are problematic?

**Comment by anthony-murphy** [comment]
basically, it fails, as the created object can't access the private members of the original type, even via it's public methods, so things like the share string interceptors fail to work at all.

**Comment by anthony-murphy** [comment]
we can probably still use them in specific instances, but can't just wholesale enable them, and need to be cognizant of the limitations which are non-obvious

**Comment by pleath** [comment]
Got it. Thanks.

**Pull request closed without merging**
