### PR TITLE
Make test slightly more robust

### PR DESCRIPTION
**Pull request by alexvy86**
## Description

While working on #10711 this test started to fail when I used low defaults in the new functionality from the linked PR. I confirmed that an entry written to the logger by that functionality (entry with index 1 below) was throwing off the test logic here:

image

image

It'd be ideal if we looked at something else in the test validation, but this change at least will make it less likely that other things that write to the logger cause issues here.

### CODE REVIEW

**Review by CraigMacomber — APPROVED** [review]

**Comment by alexvy86** [comment]
@CraigMacomber this works but I had seconds thoughts and think I found a better approach for this file in general; if you agree I can do that in this PR before merging. Some tests use [this pattern](https://github.com/microsoft/FluidFramework/blob/c2b6d9f32897eee35114dbc433a80d0db8801bd7/experimental/dds/tree/src/test/utilities/SharedTreeTests.ts#L1132) where the custom logger itself ignores specific kinds of messages. Instead of specifying which ones to ignore, I think all custom loggers in this file could use `isSharedTreeEvent()` to filter out events not generated by this DDS, and the tests would only see the ones they need for validation. Thoughts?

**Comment by Abe27342** [comment]
@alexvy86 that change seems like a good idea to me (Craig wanted someone with more context to advise).

**Comment by alexvy86** [comment]
Alright, I'll push it here in the next few days for one last check.

**Comment by alexvy86** [comment]
@CraigMacomber @Abe27342 any additional comments? I ended up needing the filter for event name containing `IdCompressor` because those are also tree events, so some tests still needed to ignore them.

**Comment by Abe27342** [comment]
> @CraigMacomber @Abe27342 any additional comments? I ended up needing the filter for event name containing `IdCompressor` because those are also tree events, so some tests still needed to ignore them.

Looks good to me!

**Pull request merged**
