### PR TITLE
Remove `containerPath` from `DriverPreCheckInfo`

### LINKED ISSUE #8548: Refactor `DriverPreCheckInfo` and remove the deprecated `DriverPreCheckInfo.containerPath`
The `containerPath` property has been deprecated and is planned to be removed. Making it an optional property in the `DriverPreCheckInfo` interface will make it easier to transition away from in partner repos and the FluidFramework repo.

Steps:
- [x] Remove `containerPath` from `DriverPreCheckInfo`. Publish `driver-definitions` as pre-release.
- [ ] Consume pre-release `driver-definitions` in `odsp-driver` and remove `containerPath` from `checkUrl()`.

Context: #4169 https://github.com/microsoft/FluidFramework/pull/8555

### PR DESCRIPTION
**Pull request by scottn12**
This PR removes the deprecated `containerPath` property from `DriverPreCheckInfo` in `driver-definitions`. A follow up PR will be done later to update any APIs which use `DriverPreCheckInfo`.

### CODE REVIEW

**Comment by scottn12** [comment]
@leeviana @cbub @ssimic2 There are two changes that affect our partner repo in this PR. First, `DriverPreCheckInfo` was moved, so any imports of the interface must be adjusted accordingly. Additionally, we have deprecated `checkUrl()`. For some context you can check https://github.com/microsoft/FluidFramework/pull/8555#discussion_r780835579, but to summarize, it appears this API gives false negatives and is easily replaced. You can use `getLocatorFromOdspUrl()` to get all of the data returned from `checkUrl()`. Additionally, we can add in a separate boolean check function if necessary. Please let me know your thoughts on this.

**Comment by leeviana** [comment]
@scottn12 The idea with checkUrl was to get away from a ODSP specific method for this data and check and instead call something that all drivers would theoretically implement. We have currently have a very strong need for the checkUrl check to be added to the IUrlResolver interface so that we can call it without any specific knowledge of the resolver we're using. Cristian Gherghina was actually going to make this change in the Framework repo.

If this is what you meant by add in a separate boolean check function, please do so, that would help a lot :)

Also driver precheck info was specifically checked into driver-definitions instead of odsp-driver as it should not be driver specific, this check/need should be generic to all resolvers.

**Comment by leeviana** [comment]
Here's the PR where we discussed putting it in driver-definitions: https://github.com/microsoft/FluidFramework/pull/4674

**Comment by vladsud** [comment]
I do not have full history here, but I'd encourage against static functions or "every driver should have X" type of directions.
Driver package can be used for multiple storages (R11S driver can be used for FRS and R11S stack).
Plus single stack can have different service points (ODC / ODB) with different structure of everything. And same entry point can support multiple types of URIs.

Putting something on URI resolvers is fine, as URI resolver uniquely identifies service/end-point/type of URIs it supports.

**Comment by ssimic2** [comment]
> @scottn12 The idea with checkUrl was to get away from a ODSP specific method for this data and check and instead call something that all drivers would theoretically implement. We have currently have a very strong need for the checkUrl check to be added to the IUrlResolver interface so that we can call it without any specific knowledge of the resolver we're using. Cristian Gherghina was actually going to make this change in the Framework repo.
> 
> If this is what you meant by add in a separate boolean check function, please do so, that would help a lot :)
> 
> Also driver precheck info was specifically checked into driver-definitions instead of odsp-driver as it should not be driver specific, this check/need should be generic to all resolvers.

@leeviana could you please take a look at the comment here: https://github.com/microsoft/FluidFramework/pull/8555#discussion_r780835579. One of the discussions here is about where `checkUrl` functionality is exposed. The other one (within that comment) is about existing `checkUrl` not making much sense if it gives false positives, as well as false negatives. Looking at implementation it doesn't seem as if that was intentional?

@scottn12 this latter convo we can maybe take care of as a separate ticket and focus work here around original removal of `containerPath`.

**Comment by ssimic2** [comment]
@scottn12 @leeviana suggestion here is let's focus the ticket on removing deprecated field.

If we can clarify now what the correct behavior for boolean check would be, let's move that change in and deprecate `checkUrl`. Id imagine that would be `canResolve` on `IUrlResolver` ?  If we cannot (it needs more considerations), lets open a separate ticket for this work. Either way, if we are removing `DriverPreCheckInfo`, it does not matter where it is currently defined.

**Comment by leeviana** [comment]
If checkUrl has a bug that's a separate issue and we can fix that with logic. And as stated, it's not intended to be 100% accurate otherwise we'd just call UrlResolver.resolve and see if it works (for example a file could have been deleted and our check wouldn't work). I'm also fine with splitting the logic since there are two driver URL specific pieces of information we want here, so we could add a checkUrlFormat: boolean method and a separate "parsePreCheckInfo" method to IUrlResolver if we want to keep the concerns split.

**Comment by scottn12** [comment]
Based on my conversation with Sasha and Leevi, this PR will be modified to simply remove the deprecated `containerPath` property from `DriverPreCheckInfo`. Once merged, we will run a pre-release for `driver-definitions` and use that pre-release to update `checkUrl` to not return any value for `containerPath`.

**Comment by ssimic2** [comment]
@scottn12 can you please document the bug (file issue) we discussed around `checkUrl` and create ticket that splits boolean check away from checkUrl (as we discussed with @leeviana). They probably need to be taken care of in that sequence.

**Review by ssimic2 — APPROVED** [review]

**Comment by scottn12** [comment]
> @scottn12 can you please document the bug (file issue) we discussed around `checkUrl` and create ticket that splits boolean check away from checkUrl (as we discussed with @leeviana). They probably need to be taken care of in that sequence.

@ssimic2, done here: https://github.com/microsoft/FluidFramework/issues/8904

**Pull request merged**
