### PR TITLE
fix(examples): Fix path to prettierignore so shared-tree-demo doesn't expect build output files to be prettier-ified

### PR DESCRIPTION
**Pull request by alexvy86**
## Description

Ran into complaints about files in lib/ needing `prettier`-fication when trying to build main. Noticed the path was missing one "up" section.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

### CODE REVIEW

**Review by tylerbutler — APPROVED** [review]
Great catch. I wonder how hard it would be to write a policy handler that checked scripts for relative-path-like strings and checked the files were there?

**Review by sonalideshpandemsft — APPROVED** [review]

**Comment by Josmithr** [comment]
Presumably this issue passed through CI initially because we run `lint` concurrently with `tsc`? I wonder if it might be a good idea to run them in sequence instead so we can catch issues like this?

**Comment by tylerbutler** [comment]
> Presumably this issue passed through CI initially because we run `lint` concurrently with `tsc`? I wonder if it might be a good idea to run them in sequence instead so we can catch issues like this?

Maybe, but that would slow down the build quite a bit I think.

**Comment by alexvy86** [comment]
> > Presumably this issue passed through CI initially because we run `lint` concurrently with `tsc`? I wonder if it might be a good idea to run them in sequence instead so we can catch issues like this?
> 
> Maybe, but that would slow down the build quite a bit I think.

I made a pretty unscientific test in a brand new codespace adding the "compile" task as dependency for the "prettier" one in `fluidBuild.config.cjs` and the change was insignificant (took less time, actually, but that must be noise; 594s vs 591s) and did fail with prettier flagging the lib/ files. I guess there's enough dependencies between other tasks that this bit doesn't move the needle too much.

**Pull request merged**
