### PR TITLE
Merge in next -- Stop using concrete protocol handler class (#10655)

### PR DESCRIPTION
**Pull request by sonalivdeshpande**
This commit was reverted in the previous integrate PR: https://github.com/microsoft/FluidFramework/commit/2d4f54e3ebcdf15cc55765de76645cbc62fcb0a9 as I was seeing some build failures. Opening this as a separate individual commit to fix any build issues.

### CODE REVIEW

**Review by andre4i — APPROVED** [review]
This looks ok. Please see my comment.

**Comment by sonalivdeshpande** [comment]
protocol-base is on ^0.1036.4000 in next. should I change that to ^0.1036.5000-0?

**Comment by andre4i** [comment]
See my PR in main: https://github.com/microsoft/FluidFramework/pull/10640/. However, I'm not sure how that would work with `next`. Because the client will pick the package built from `main` via the pipeline (I think) instead of the one from `next`, right?

**Comment by sonalivdeshpande** [comment]
yeah. do we need any prerelease against next for it to get consumed?

**Comment by andre4i** [comment]
Yes, but I believe that for `next`, the dependency version should be `0.1037.1000-0`, after a pre-release from next. cc @ssimic2

**Comment by ssimic2** [comment]
Yes. And hopefully main to next PR brought in needed changes to 0.1037.1000
on next

**Comment by sonalivdeshpande** [comment]
@andre4i -- should I work on pre-releasing and then bumping the protocol-base in next to 0.1037.1000-0?

**Comment by andre4i** [comment]
Hi @sonalivdeshpande, any updates on this?

**Comment by sonalivdeshpande** [comment]
> Hi @sonalivdeshpande, any updates on this?

I'll get this in by tomorrow. sorry for the delay

**Comment by andre4i** [comment]
Thanks, @sonalivdeshpande tomorrow is fine.

**Pull request merged**
