### PR TITLE
Fix op size telemetry when summarizing 

### PR DESCRIPTION
**Pull request by andre4i**
## Description

Will close [950](https://dev.azure.com/fluidframework/internal/_workitems/edit/950) by persisting the op count in the summary heuristic. I opted to use the existing op counters, so non-system op will be reported as non-runtime op, which only includes the summary op. .~When there's possible data loss, we won't report these new metrics~ I think we should anyway, but include a flag saying the data may be inaccurate. Also, some light refactoring and removal of the OpTracker.

## Does this introduce a breaking change?

Yes, it removes two fields from `IGeneratedSummaryStats` which trickles down to other interfaces. There is no migration path here, these are internal interfaces.

### CODE REVIEW

**Comment by NicholasCouri** [comment]
> 

Out of curiosity, why move this to a new file ? Do you expect it to be used anywhere else ? 

---
Refers to: packages/runtime/container-runtime/src/opProperties.ts:20 in 73238ea. [](commit_id = 73238eab11d6cde301891587a339da8d3095afe8, deletion_comment = False)

**Review by NicholasCouri — APPROVED** [review]
:shipit:

**Comment by andre4i** [comment]
@NicholasCouri didn't want to bloat the running summarizer. No strong feelings pro or against it, just didn't feel cohesive enough with the rest of the things happening in that file.

**Comment by andre4i** [comment]
Hi @sonalivdeshpande, can you help merge this? I don't have permissions.

**Pull request merged**
