### PR TITLE
Enable timeout ensureSynchronized everywhere (Solution #1)

### PR DESCRIPTION
**Pull request by curtisman**
Provide the mocha test timeout `LoaderContainerTracker` to limit how long to wait for `ensureSynchronized`.  Currently it is set to half of test time.  The purpose is to provide a better error message and stack if `ensureSynchronized` got stuck.

Also, change the behavior for `timeoutPromise`, when duration is <=0 or Infinity.  Instead of waiting for the default amount, it will now mean it won't timeout at all.   This is so that we can avoid timeout when debugging.

Fix [AB#2175](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/2175)

### CODE REVIEW

**Comment by vladsud** [comment]
Timeouts usually do not work :) Is the reason to add them - aid in debuggability where it's hard to figure out for developers why tests hang? Anything we can do to improve it without using timeouts? Like maybe mocha has some facility to run code when test fails and for code like that to provide extra info for easier debugging?

**Comment by curtisman** [comment]
@vladsud yes, this is here to aid in debuggability so that they know where it hangs.   mocha test has timeout, but when it does, it only kill the test. 
It doesn't give you any idea where it hangs, especially around promises.  

@anthony-murphy  added  the timeout concept for promises used in test.   I don't know if he has other alternatives.

**Comment by curtisman** [comment]
@vladsud @anthony-murphy Please also look at #12303, which instead of estimating using a half the timeout. #12303 will trap test run and calculate how long until the test would timeout and set the duration for promise wait just before that.

**Comment by curtisman** [comment]
Closing in favor of  #12303

**Pull request closed without merging**
