### PR TITLE
[bump] server: 3.0.0 => 3.1.0 (minor)

### PR DESCRIPTION
**Pull request by jatgarg**
## Description

Bump server minor 3.1.0

### CODE REVIEW

**Review by jason-ha — APPROVED** [review]
Interesting branch history, but the changes look okay to me.
It there a standard title/description that such changes should use?

**Comment by jatgarg** [comment]
> Interesting branch history, but the changes look okay to me. It there a standard title/description that such changes should use?

No. But the title is ok.

**Comment by jason-ha** [comment]
> > Interesting branch history, but the changes look okay to me. It there a standard title/description that such changes should use?
> 
> No. But the title is ok.

https://github.com/microsoft/FluidFramework/wiki/Commit-message-style#pr-template-content
but the page it lacking details. For this I would have expected:
`build(server): 3.0.0 => 3.1.0 (minor)`
or like Tyler uses
`[bump] server: 3.0.0 => 3.1.0 (minor)`

**Comment by tylerbutler** [comment]
@jatgarg server releases are always major releases. This should be a major bump, not minor.

**Comment by jason-ha** [comment]
> @jatgarg server releases are always major releases. This should be a major bump, not minor.

@tylerbutler, does it need to be at this point? (I am not saying it doesn't.) This is being done because there wasn't any bump after last release which means prereleases are versioned as if they predate the last major release. For that minor should be sufficient, yes?

**Pull request merged**
