### PR TITLE
Export GarbageCollector from common-utils

### LINKED ISSUE #4500: We have two implementations of GarbageCollector class for an in-memory cache
Can we rationalize this?

### PR DESCRIPTION
**Pull request by NicholasCouri**
In order to remove the GarbageCollector duplicated on odsp-driver, we need to first export the original GarbageCollector implementation from common-utils. The end goal is to fix #4500 once this change goes in.

### CODE REVIEW

**Comment by vladsud** [comment]
As far as I see, the only usage is in ODSP driver. If so, I want to question having it in common-utils - I think the better way is to simply delete from there.
Any chance you can glance at history and talk to people to see why it showed up here?
It's not really very generic, and I think implementation sucks (for example, there is no cancelation of timers, so it will keep large objects in memory long after container is closed), so I'm not sure I'd ever put it to some stand-alone "general usage" package outside FF, and common-utils is sort of that - common tools that are not directly related to FF and might in some future be their own packages/ implementations

**Comment by NicholasCouri** [comment]
I see - My goal was to simply remove the duplicate implementation from odspdriver and consume the one from common-utils instead.

PromiseCache currently consumes that GarbageCollector from common-utils and this PromiseCache gets consumed by the odsp-driver and routerlicious-host.

I will follow-up with Mark regarding the details around it as he initially added the class 2 years ago.

________________________________

**Comment by vladsud** [comment]
Maybe I did not do good tracing :) But please question direction :) If we collectively believe it belongs in common-utils, that's fine, just want to make sure we make data-driven choice.

**Comment by anthony-murphy** [comment]
common-utils is a very painful package for us. it should really be for code that is shared across client and server. if it is only used in the client packages, it would be better for it is live in a common place under packages. this may entail moving promise cache if server doesn't use it.

**Comment by NicholasCouri** [comment]
After talking to Mark and taking in consideration what Vlad and Antony mentioned, I will close this PR and will submit another with a better solution.

**Pull request closed without merging**
