### PR TITLE
feat(type-tests): return void from use function

### PR DESCRIPTION
**Pull request by connorskees**
this removes the implicit any return from the use_old functions. this is a necessary step to enable noImplicitAny in our test packages

### CODE REVIEW

**Comment by connorskees** [comment]
Relevant changes are to `build-tools/packages/build-tools/src/typeValidator/testGeneration.ts`

**Comment by tylerbutler** [comment]
Unfortunately you won't be able to make the build-tools change and the client change in a single PR since they're in different release groups. You'll have to make the build-tools change then we need to release and integrate it into client.

**Comment by connorskees** [comment]
> release and integrate it into client

Is it sufficient to just merge the changes into main and bump the dependency version in this PR, or is there a special release process that must be followed?

**Comment by connorskees** [comment]
Closing as this will be handled by a build-tools bump.

**Pull request closed without merging**
