### PR TITLE
Change how we handle exceptions in driver code: they become non-retryable

### PR DESCRIPTION
**Pull request by vladsud**
Issue https://github.com/microsoft/FluidFramework/issues/4946

All errors that come from storage go through translation where we explicitly assign canRetry property to error object that is thrown.
But if we do not go through that translation (like if code hit exception, like dereferencing undefined), then error object does not have that property and Loader layer will keep retrying.

Switching to fail-fast paradigm here to find these bugs and address them, but also not to retry forever.

@tanviraumi, I do not expect much problem for SPO workflows, but that might impact FRS as it's less mature stack. Any chance you can given you assessment on risk here?  We do some translation for socket errors (createNetworkError). But there is zero interpretation of errors for calls in IDocumentStorageService (like read, write, getVersions, etc.). This change will make ALL errors return from these APIs non-retryable and fail container. With or without this change, driver needs to start differentiating retryable vs. non-retryable errors. The only question imho here - is this PR too early and will cause some noise while we get the work done in r11s driver going?

That all said, we either do this change now or never :) I.e. I'd not want to do it once we actually ship (GA) existing workflows - it's a bit too much risk I'm willing to stomach.

### CODE REVIEW

**Comment by tanviraumi** [comment]
Adding @znewton as well since he is working on it.

It's a little early for us since we don't retry at all today. r11s driver needs to do some work first to differentiate between retry and non retryable calls. Its hard to give a timeline since we just started looking at this issue. So my recommendation would be to not check it in right now and let us get back to you.

**Comment by vladsud** [comment]
Thanks! Worth pointing out that this only changes today's logic when fetching ops - that's the only place where we check for this flag in FRS case. As for all other calls (reading tree/blobs) they had no retry logic till last week or so when Jatin put in RetriableDocumentStorageService. I guess I'm saying we were already in pretty bad shape here, and we are in not much better shape now retrying 404 for getVersions just results in infinite loop). So it feels like it does not make things more broken then they are already today for FRS.

Waiting a big is fine, but I do not want to flip it in March - that's too risky for existing projects. Do you have an ETA?

**Comment by tanviraumi** [comment]
Ah I see. I was guessing we were always retrying for a while. If we were not retrying anyways, feel free to check this in.

**Comment by vladsud** [comment]
Interesting, notice that it found bug in mock storage - we were unreferencing undefined, and that was completely unnoticed (as we would keep retrying fetching ops forever, but test did not care about ops).

**Review by jatgarg — APPROVED** [review]

**Pull request merged**
