### PR TITLE
Revert "Slide references from locally removed segments when resolving position"

### PR DESCRIPTION
**Pull request by alexvy86**
Reverts microsoft/FluidFramework#21536. Looks like it causes a test in the undo-redo package to consistently timeout when running with code coverage enabled, so it broke CI.

### CODE REVIEW

**Review by scarlettjlee — APPROVED** [review]

**Comment by titrindl** [comment]
@alexvy86 could you send me a link to the failing test?

**Comment by anthony-murphy** [comment]
@alexvy86 when we revert there should be a bug filed with the details around the reason/data for the revert and assigned to the original author.

**Comment by alexvy86** [comment]
Closing in favor of https://github.com/microsoft/FluidFramework/pull/21698

**Pull request closed without merging**
