### PR TITLE
1892 fluid-runner CSV telemetry (#12015)

### PR DESCRIPTION
**Pull request by kian-thompson**
[AB#1892](https://dev.azure.com/fluidframework/internal/_workitems/edit/1892)

Needed to unblock OASYS for the eDiscovery work

- Add support for choosing to export telemetry as a CSV
- Add support for adding additional properties to every telemetry entry

### CODE REVIEW

**Comment by tyler-cai-microsoft** [comment]
main PR: https://github.com/microsoft/FluidFramework/pull/12015

**Review by vladsud — APPROVED** [review]
I assume it's same code as in main, right?

**Comment by tyler-cai-microsoft** [comment]
We need to port this fix in as well don't we https://github.com/microsoft/FluidFramework/pull/12205 to merge this in

**Review by tyler-cai-microsoft — APPROVED** [review]

**Comment by agarwal-navin** [comment]
Closing this since it is patched to 1.2 which is the only one needed.

**Pull request closed without merging**
