### PR TITLE
docs(tree): Reorganize and fix links

### PR DESCRIPTION
**Pull request by jenn-le**
## Description

Reorganize docs into more general folders based on the status of the doc and rename them to snake case in order to make them consistent and easier to link to.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

The purpose of this reorganization is to rely less on folders for organization which can lead to links breaking when we want to reorganize docs in the future. This instead encourages organization using links and landing pages. A temporary landing page is added as the README for the docs folder to act as an example but doesn't actually establish any organization yet. Organizing using links in pages allows context about the relationship between links to be included and allows pages to be included in multiple categories/landing pages rather than just a single folder hierarchy. Changing these categories is also much easier and doesn't break links.

Future improvements:
- Publish the docs as a Github Pages website
- Include backlinks (links to pages that link to the current page) to improve connections between pages
- Split docs up into more atomic pages to increase linking and shared documentation
- Publish API docs as markdown
- Clean up the readmes in the submodule folders to be minimal and link to the corresponding page in the docs folder
- Add a linter to detect broken local links

### CODE REVIEW

**Comment by CraigMacomber** [comment]
Relying on manually added and maintained inks in pages for navigation can easily result in docs that arn't linked and thus lost. I suspect the link checker won't cover that. I'm not sure what would work well with our tooling, but some why to link to a collection of documentation files (a folder) that list them by name (like the folder view on github and other systems) might be viable. It also reduces merge conflicts when adding renaming and moving docs, and automatically keeps all the links up to date. File names and folders are quite good at what they do, and well integrated with tons of tooling (github, git, vscode, your OS etc): maybe there is a way we can leverage them?

Regarding:
> Clean up the readmes in the submodule folders to be minimal and link to the corresponding page in the docs folder

Folder readme's are special on github as they get displayed by default when you have the folder open on github.

Also I don't think links to them getting broken should be much of a concern: we probably shouldn't be linking those very often: as long as they move with the code they describe it should be fine: developers working in those directories should know how to find them, and I want to keep it real easy to create, remove, split and join these directories: they are an implementation detail and it changes somewhat often.

Generally splitting content into multiple parallel hierarchies (like we do for source vs test, and packages vs API reports) makes it harder to review (things don't get grouped properly), easier to missing updating something, and harder to find.

Also the intention behind the readmes in the source folders as they are providing documentation for developers working in those folders. Much of the content in the docs folder is aimed at users of the package. I think this separation by audience makes sense, and as the internal source folders are an implementation detail only exposed to developers of the package, I don't see why we would want to separate those details from the source they are detailing. Also since this implementation details have no requirements to be stable across major versions, using published versions of these docs instead of using the ones from the version of the source you are editing seems like a bad idea.

**Review by CraigMacomber — APPROVED** [review]

**Comment by jenn-le** [comment]
> Relying on manually added and maintained inks in pages for navigation can easily result in docs that arn't linked and thus lost. I suspect the link checker won't cover that. I'm not sure what would work well with our tooling, but some why to link to a collection of documentation files (a folder) that list them by name (like the folder view on github and other systems) might be viable. It also reduces merge conflicts when adding renaming and moving docs, and automatically keeps all the links up to date. File names and folders are quite good at what they do, and well integrated with tons of tooling (github, git, vscode, your OS etc): maybe there is a way we can leverage them?

I don't think lost docs should be a concern. Even if a doc is not linked to, it's still visible from the Github file view and can be found through search. I don't think the issue of discoverability is made any worse off than what we currently have with this change. I think it'll generally be a net gain as long as we're mindful about adding links, even if it's just linking related pages to each other without adding anything to a landing page. I'm not sure what would be a good way to leverage folders but I think file names are still doing the same job. My worry with folders is that they have a tendency of silo-ing knowledge. If we have a page on repair data, it's kind of a toss up on whether it goes under undo or under transactions and if we pick one, the connection to the other is harder to find and we may end up duplicating docs (which we do in some places currently). It's even weirder to find if it has its own folder (like it currently does). On the other hand, if we're linking to repair data from both pages, they get to share documentation and include context on how repair data is used by undo or transactions.

> 
> Regarding:
> 
> > Clean up the readmes in the submodule folders to be minimal and link to the corresponding page in the docs folder
> 
> Folder readme's are special on github as they get displayed by default when you have the folder open on github.
> 
> Also I don't think links to them getting broken should be much of a concern: we probably shouldn't be linking those very often: as long as they move with the code they describe it should be fine: developers working in those directories should know how to find them, and I want to keep it real easy to create, remove, split and join these directories: they are an implementation detail and it changes somewhat often.
> 
> Generally splitting content into multiple parallel hierarchies (like we do for source vs test, and packages vs API reports) makes it harder to review (things don't get grouped properly), easier to missing updating something, and harder to find.
> 
> Also the intention behind the readmes in the source folders as they are providing documentation for developers working in those folders. Much of the content in the docs folder is aimed at users of the package. I think this separation by audience makes sense, and as the internal source folders are an implementation detail only exposed to developers of the package, I don't see why we would want to separate those details from the source they are detailing. Also since this implementation details have no requirements to be stable across major versions, using published versions of these docs instead of using the ones from the version of the source you are editing seems like a bad idea.

I really like the point about different audiences but it currently doesn't feel like the docs folder is aimed at users of the package but more for people onboarding onto the team. This is prob something we should work on but for now, I think it makes sense to have the package READMEs for informing a user of a package the current state of the package and how to get started using vs the other docs for actually learning about how it fits in the architecture/design decisions. I think the point about splitting content into multiple parallel hierarchies is interesting though, maybe it'll be fine as long as we're very clear on what information the different kinds of docs should cover? 

I don't think there's anything terribly wrong with separating the docs from the source to make them easier to read. The plan is to publish the API doc comments within the docs folder as well so that we can link to them from the more general docs. This way doc updates can still happen next to code while making the docs themselves easier to find and reusable.

**Comment by CraigMacomber** [comment]
> I don't think lost docs should be a concern. Even if a doc is not linked to, it's still visible from the Github file view and can be found through search. I don't think the issue of discoverability is made any worse off than what we currently have with this change. I think it'll generally be a net gain as long as we're mindful about adding links, even if it's just linking related pages to each other without adding anything to a landing page. I'm not sure what would be a good way to leverage folders but I think file names are still doing the same job. My worry with folders is that they have a tendency of silo-ing knowledge. If we have a page on repair data, it's kind of a toss up on whether it goes under undo or under transactions and if we pick one, the connection to the other is harder to find and we may end up duplicating docs (which we do in some places currently). It's even weirder to find if it has its own folder (like it currently does). On the other hand, if we're linking to repair data from both pages, they get to share documentation and include context on how repair data is used by undo or transactions.

If our main intended way to consume these docs is via the github UI or via local tools browsing the files, then I don't think the list of links to all the docs you put in docs/readme.md is needed (its not adding much over the list of docs that would be displayed if you navigate to the docs folder if you got rid of the nested main directory)

If the main way to view it is via some published view that does not expose folders, like maybe some github pages thing, then there might be no way to find docs that arn't linked. Personally I'd prefer such a view to also have a way to embed a list of folder contents, but without such an approach, the list is redundent, and thus can be out of sync.

Supporting both has overhead (and some value), and I just want to make sure we arn't paying for that overhead if we don't need it.

> 
> > Regarding:
> > > Clean up the readmes in the submodule folders to be minimal and link to the corresponding page in the docs folder
> > 
> > 
> > Folder readme's are special on github as they get displayed by default when you have the folder open on github.
> > Also I don't think links to them getting broken should be much of a concern: we probably shouldn't be linking those very often: as long as they move with the code they describe it should be fine: developers working in those directories should know how to find them, and I want to keep it real easy to create, remove, split and join these directories: they are an implementation detail and it changes somewhat often.
> > Generally splitting content into multiple parallel hierarchies (like we do for source vs test, and packages vs API reports) makes it harder to review (things don't get grouped properly), easier to missing updating something, and harder to find.
> > Also the intention behind the readmes in the source folders as they are providing documentation for developers working in those folders. Much of the content in the docs folder is aimed at users of the package. I think this separation by audience makes sense, and as the internal source folders are an implementation detail only exposed to developers of the package, I don't see why we would want to separate those details from the source they are detailing. Also since this implementation details have no requirements to be stable across major versions, using published versions of these docs instead of using the ones from the version of the source you are editing seems like a bad idea.
> 
> I really like the point about different audiences but it currently doesn't feel like the docs folder is aimed at users of the package but more for people onboarding onto the team. This is prob something we should work on but for now, I think it makes sense to have the package READMEs for informing a user of a package the current state of the package and how to get started using vs the other docs for actually learning about how it fits in the architecture/design decisions. I think the point about splitting content into multiple parallel hierarchies is interesting though, maybe it'll be fine as long as we're very clear on what information the different kinds of docs should cover?

There is still some content in the docs directory indented for package developers that isn't suited for movement into the source tree (ex: design proposals which don't fit neatly into a specific source area, and package level conventions and dev practices): I think separating that from docs about the package (how to use it, status, goals, support lifecycle etc.) make sense,
and neither of those kinds of docs belong inside the source tree (as they don't apply to specific directories): maybe a subdirectory in /docs or a separate developer_docs vs user_docs folders?

However, the docs that do make sense in the source tree are entirely specific to developers (the shape of the source tree is an implementation detail. If we put all such content in the source tree then we should:

1. Have clear rules where things go: if its for developers of a specific directory, put it in there. if its for developers of the package, we have a place for that outside of /src for that, and if its for users of the package, we have a separate place for that (doc comments on package exported types + some subset of top level readme + subset of /docs)
2. Have a way to publish everything that for users of the package as part of releases without pulling in implementation details.

> 
> I don't think there's anything terribly wrong with separating the docs from the source to make them easier to read. The plan is to publish the API doc comments within the docs folder as well so that we can link to them from the more general docs. This way doc updates can still happen next to code while making the docs themselves easier to find and reusable.

I just want to caution against moving docs which are only relevant to developers of code in a specific directory out of that directory as a general pattern, which is how I interpret "Clean up the readmes in the submodule folders to be minimal...". If they contain information thats important to know for people not directly importing things from or working on that directory, then moving stuff out is fine, but as much as possible I'd like to avoid polluting package scoped documents with implementation details of parts of the package. I (subjectively) think that makes them harder to find, update and read.

It's easy to fail to notice file is missing tests because tests are separate, and this has been a problem for me in our code (I much prefer tooling (ex: rust test) that allows them to go together). I want to avoid this as much as possible for docs. Source level doc comments are excellent at this, and our directory readme's are as close as I could get for module/folder doc comments (again some other tools actually properly support module doc comments, like rust doc, but we are just trying to get close).

Overall this is all pretty subjective, and not that important to me: just explaining why I setup the readmes as I did. If we want a different pattern, its not a bid deal for me (I deal with our test setup for example despite it having the same issue.

**Comment by jenn-le** [comment]
> If our main intended way to consume these docs is via the github UI or via local tools browsing the files, then I don't think the list of links to all the docs you put in docs/readme.md is needed (its not adding much over the list of docs that would be displayed if you navigate to the docs folder if you got rid of the nested main directory)
> 
> If the main way to view it is via some published view that does not expose folders, like maybe some github pages thing, then there might be no way to find docs that arn't linked. Personally I'd prefer such a view to also have a way to embed a list of folder contents, but without such an approach, the list is redundent, and thus can be out of sync.
> 
> Supporting both has overhead (and some value), and I just want to make sure we arn't paying for that overhead if we don't need it.

Ah, I see. That list of links is just meant to be a temporary landing page, I agree it's very useless. I'm planning to make a lot of changes in separate PRs. Ideally, the github pages solution will have some kind of folder view and search functionality as well.

> There is still some content in the docs directory indented for package developers that isn't suited for movement into the source tree (ex: design proposals which don't fit neatly into a specific source area, and package level conventions and dev practices): I think separating that from docs about the package (how to use it, status, goals, support lifecycle etc.) make sense, and neither of those kinds of docs belong inside the source tree (as they don't apply to specific directories): maybe a subdirectory in /docs or a separate developer_docs vs user_docs folders?

I think a subdirectory in /docs makes sense. I actually originally had a /docs/design folder for this purpose but I wasn't quite sure what belonged under it so I would love some guidance on what you think belongs there (maybe in the next PR). 

> 
> However, the docs that do make sense in the source tree are entirely specific to developers (the shape of the source tree is an implementation detail. If we put all such content in the source tree then we should:
> 
> 1. Have clear rules where things go: if its for developers of a specific directory, put it in there. if its for developers of the package, we have a place for that outside of /src for that, and if its for users of the package, we have a separate place for that (doc comments on package exported types + some subset of top level readme + subset of /docs)
> 2. Have a way to publish everything that for users of the package as part of releases without pulling in implementation details.

Agreed, I think we'll definitely need specific guidelines. 

> I just want to caution against moving docs which are only relevant to developers of code in a specific directory out of that directory as a general pattern, which is how I interpret "Clean up the readmes in the submodule folders to be minimal...". If they contain information thats important to know for people not directly importing things from or working on that directory, then moving stuff out is fine, but as much as possible I'd like to avoid polluting package scoped documents with implementation details of parts of the package. I (subjectively) think that makes them harder to find, update and read.
> 
> It's easy to fail to notice file is missing tests because tests are separate, and this has been a problem for me in our code (I much prefer tooling (ex: rust test) that allows them to go together). I want to avoid this as much as possible for docs. Source level doc comments are excellent at this, and our directory readme's are as close as I could get for module/folder doc comments (again some other tools actually properly support module doc comments, like rust doc, but we are just trying to get close).
> 
> Overall this is all pretty subjective, and not that important to me: just explaining why I setup the readmes as I did. If we want a different pattern, its not a bid deal for me (I deal with our test setup for example despite it having the same issue.

I think that makes sense and it doesn't seem like we have any information that fits that category currently. In general, I think this is an argument for trying to put as much information as we can on the API docs, especially the ones that aren't package exported. We just need to tooling to make them easy to read. Even though the package readmes are closer to the source than the /docs folder, they're still typically overlooked during PRs.

**Pull request merged**
