### PR TITLE
Add scopeOverride to enable per-container-resolve customization of runtime initialization

### PR DESCRIPTION
**Pull request by ChumpChief**
Related: #13779 

Currently, the scope is set once (at Loader creation time).  However, it's possible hosts may want to pass different scope information on a per-resolve basis.  This is particularly true when the load is performed in a different context, e.g. a top-level container vs. loading a "guest" container as a sub-part of an experience.

Normally we recommend against using scope, but it does serve a purpose here of allowing hosts to pass objects to their container runtime at initialization time.  Since the initialization phase (instantiateRuntime) is buried in the Container, this is the best entrypoint we currently make available for host customization of that initialization.

### CODE REVIEW

**Comment by vladsud** [comment]
Given that Loader caches containers, there is no actual promise we can make here that this overide scope will be used.
I'd encourage against adding it, and Loop using new Loader instance instead. And moving away from using Loader (per recent discussions in this space between Tony & Leevi)

**Comment by ChumpChief** [comment]
> Given that Loader caches containers, there is no actual promise we can make here that this overide scope will be used.
I'd encourage against adding it, and Loop using new Loader instance instead. And moving away from using Loader (per recent discussions in this space between Tony & Leevi)

That point about caching is a good one, and would apply equally to the `baseLogger` header from #13779.  I think both are solved by using a `LoaderHeader.cache` to force no caching though.

Using a separate Loader instance could be fine too, but my understanding is that this was determined to be less preferable or more problematic previously (hence #13779, which also seems it could have been solvable via a new Loader instance).  If a new Loader instance really is feasible then let's remove both of these new headers.

**Comment by vladsud** [comment]
I think Loop wants to abstract away details like driver factory / uri resolver from components who need to create child containers.
As a temp solution, we should consider Loader.clone() kind of behavior, that copies all the connections (factory, uri resolvers), but starts from clean state RE caching. We can provide (optional) overwrites for scope, logger on that API - feels a bit cleaner.

**Review by vladsud — APPROVED** [review]

**Comment by ssimic2** [comment]
Offline we have chatted about removing container caching from this loader layer. If that is a direction we should consider please add a work item so we don't lose sight of it.

@ChumpChief  Thanks for picking this up and driving to resolution quickly!

**Review by ssimic2 — APPROVED** [review]

**Pull request merged**
