### PR TITLE
Better handling of pending ops in task-manager

### PR DESCRIPTION
**Pull request by ChumpChief**
This change makes a few substantial changes in task-manager:

1. Changes the task queue tracking to reflect the consensus state (previously would remove self on abandon before ack).
2. Most importantly, tracks pending ops with `messageId` to better understand pending state.  This allows us to better understand if we anticipate a future abandon/volunteer when deciding whether to declare ourselves the lock holder.
3. Correctly handles abandon before the ack of a volunteer op by rejecting the promise.

@anthony-murphy found a bug when experimenting with the task-manager which I believe was (3) above -- if you're still able to try your scenario with this fix, I'd love to know if things are working as you expect now.

### CODE REVIEW

**Comment by vladsud** [comment]
Did not look yet through the changes, but one work of caution for future.
Consider future case of serializing and rehydrating container with pending local changes (work that Wes was working on that got put on hold). I.e. the most complex local stacking state, the harder it might be to regenerate it when applying "stash" of local (non-submitted) ops.

I feel like the more it's about fire-and-forget and state machine (that works in response to actual events, i.e. ack of ops), the better.

That said, did not look at your changes yet, so maybe it's all rambling not on the subject :)

**Comment by ChumpChief** [comment]
> Did not look yet through the changes, but one work of caution for future.
> Consider future case of serializing and rehydrating container with pending local changes (work that Wes was working on that got put on hold). I.e. the most complex local stacking state, the harder it might be to regenerate it when applying "stash" of local (non-submitted) ops.
> 
> I feel like the more it's about fire-and-forget and state machine (that works in response to actual events, i.e. ack of ops), the better.
> 
> That said, did not look at your changes yet, so maybe it's all rambling not on the subject :)

I'd love to better understand generally the intended behavior of the stashing scenario - looks like these are not implemented yet anywhere?

I think it doesn't matter here as long as the stashed ops won't be considered "local".  If a stashed op can be "local" then we probably need to do something, but I imagine this is equally true for all DDSs with the `messageId` tracking pattern (map, directory, cell, etc.)

**Comment by vladsud** [comment]
Stashed ops will be local. The expectation is for DDSs when applying stash is to reconstruct local state as if they were made via API calls. And yes, all DDSs will need to do work here, Wes only implemented it for map, I believe.
Again, sorry if it's just a noise :)

**Comment by ChumpChief** [comment]
> Stashed ops will be local. The expectation is for DDSs when applying stash is to reconstruct local state as if they were made via API calls. And yes, all DDSs will need to do work here, Wes only implemented it for map, I believe.
> Again, sorry if it's just a noise :)

Hmm, we should probably chat more on this topic I guess (I don't see much documentation explaining the intended behavior or how a "stashed" scenario is reached -- would be nice to have something in the `IDeltaHandler` tsdoc).

**Comment by ChumpChief** [comment]
Flaky test is #5593, this should be OK to review.

**Review by anthony-murphy — APPROVED** [review]

**Comment by anthony-murphy** [comment]
did some testing. it works better. there is an issue that still exists in both where the task is assigned to a zombie client id. not idea how it's happening at the momement

**Comment by ChumpChief** [comment]
> did some testing. it works better. there is an issue that still exists in both where the task is assigned to a zombie client id. not idea how it's happening at the momement

Maybe I can get a repro from you Monday?  Since I haven't done the disconnect or detached handling I'm tempted to blame something around those scenarios, but would like to verify.

**Comment by anthony-murphy** [comment]
> > idea how it's happening at the momement
> 
> Maybe I can get a repro from you Monday? Since I haven't done the disconnect or detached handling I'm tempted to blame something around those scenarios, but would like to verify.

definitely disconnect scenario :)

**Pull request merged**
