### PR TITLE
Use the correct logger in the container runtime

### PR DESCRIPTION
**Pull request by anthony-murphy**
Fix some cases where ContainerRuntime logs were being sent to the incorrect logger.

### CODE REVIEW

**Review by alexvy86 — COMMENTED** [review]
I see that ContainerRuntime needs to expose a `logger` property because it implements `ISummarizerRuntime`... but shouldn't we make the constructor parameter just a locally-scoped variable and make `this.logger` return `this.mc.logger`? Do we actually need the logger provided by the constructor caller to be exposed from this class?

**Comment by anthony-murphy** [comment]
> I see that ContainerRuntime needs to expose a `logger` property because it implements `ISummarizerRuntime`... but shouldn't we make the constructor parameter just a locally-scoped variable and make `this.logger` return `this.mc.logger`? Do we actually need the logger provided by the constructor caller to be exposed from this class?

Its not just the summarizer contract:
https://github.com/microsoft/FluidFramework/blob/1b21a44bc956fcd60ddd1828b4882956feba396e/packages/runtime/runtime-definitions/src/dataStoreContext.ts#L158

**Comment by alexvy86** [comment]
> Its not just the summarizer contract:

Ah, missed that one... but doesn't the point stand? Why would we expose to datastores the logger provided by the caller when constructing the ContainerRuntime, instead of the one the ContainerRuntime created?

**Comment by anthony-murphy** [comment]
> > Its not just the summarizer contract:
> 
> Ah, missed that one... but doesn't the point stand? Why would we expose to datastores the logger provided by the caller when constructing the ContainerRuntime, instead of the one the ContainerRuntime created?

Its a good question. I believe the idea is that we basically pass through the application provided logger untouched for use in application code, so their datastores can log to their sinks with us changing the events.

**Comment by anthony-murphy** [comment]
> > > Its not just the summarizer contract:
> > 
> > 
> > Ah, missed that one... but doesn't the point stand? Why would we expose to datastores the logger provided by the caller when constructing the ContainerRuntime, instead of the one the ContainerRuntime created?
> 
> Its a good question. I believe the idea is that we basically pass through the application provided logger untouched for use in application code, so their datastores can log to their sinks with us changing the events.

It also looks wrong right now. ContainerRuntime is exposing a ITelemetryLoggerExt when it should only be exposing a ITelemetryBaseLogger based on the interface. If it only exposed ITelemetryBaseLogger it would be clearer to our code that it should not be used, as it wouldn't have the methods we expect. Maybe @markfields knows more.

**Review by tyler-cai-microsoft — APPROVED** [review]
LGTM, looks like some small test fixes are required, I like the change :)

**Comment by alexvy86** [comment]
> Its a good question. I believe the idea is that we basically pass through the application provided logger untouched for use in application code, so their datastores can log to their sinks with us changing the events.

That makes sense, and if it's indeed the case I think it's documentation that we should absolutely add to that property of the interface to make it explicit. Otherwise I think someone else in the future will go through a similar train of though as I just did and "fix" the weird usage patterns. It's feels particularly unnatural that within container runtime we need to log through `this.mc.logger` when `this.logger` exists.

**Comment by anthony-murphy** [comment]
> > Its a good question. I believe the idea is that we basically pass through the application provided logger untouched for use in application code, so their datastores can log to their sinks with us changing the events.
> 
> That makes sense, and if it's indeed the case I think it's documentation that we should absolutely add to that property of the interface to make it explicit. Otherwise I think someone else in the future will go through a similar train of though as I just did and "fix" the weird usage patterns. It's feels particularly unnatural that within container runtime we need to log through `this.mc.logger` when `this.logger` exists.

it is true everywhere what we should log through the monitoring context if it exists. I think comments are fine, but typing is even better, the exposed logger should be an ITelemetryBaseLogger, which isn't a very useful thing, so would pretty clearly hint something else should be used, or a child logger/monitoring context should be created.

**Comment by markfields** [comment]
FYI I opened https://dev.azure.com/fluidframework/internal/_workitems/edit/5160 in response to some of the discussion here

**Pull request merged**
