### PR TITLE
don't send rejoin op when reconnecting with pending ops

### PR DESCRIPTION
**Pull request by wes-carlson**
#8396

### CODE REVIEW

**Comment by vladsud** [comment]
is this basically reverting of change (until we figure out proper fix), or something else?

**Comment by wes-carlson** [comment]
> is this basically reverting of change (until we figure out proper fix), or something else?

Yes, this is where the rejoin ops are being sent

**Review by vladsud — APPROVED** [review]

**Comment by agarwal-navin** [comment]
This is reverting only the sending of the "rejoin" op but leaves the addition of the op type. When we add this code back, we will need to keep it disabled until the telemetry data suggests no one is using runtime version < 0.51.x

**Comment by wes-carlson** [comment]
@DLehenbauer FYI I had to disable the rejoin op due to backwards incompatibility

**Comment by agarwal-navin** [comment]
@wes-carlson @vladsud - Documents affected with this error will have the "rejoin" op as part of their op stream now. I want to confirm that if they try to load with the versions that have this fix, they should be able to process the "rejoin" just fine and these documents will be recovered.
Otherwise, we need to recommend rolling back these documents to previous versions right.

**Pull request merged**
