### PR TITLE
Update async version for build-tools 

### PR DESCRIPTION
**Pull request by jikim-msft**
#### Description
https://dev.azure.com/fluidframework/internal/_workitems/edit/1168/

This PR is a sub-PR to update async version for build-tools 

As `async` in `common/lib/common-utils/package.json` depends on `@fluidframework/build-tools`, this PR attempts to update `async` dependency on `build-tools` and update remaining packages' dependency on `build-tools`.

### CODE REVIEW

**Review by tylerbutler — APPROVED** [review]
Change looks fine, but will you also need a build-tool release to pick up this change?

**Comment by jikim-msft** [comment]
> Change looks fine, but will you also need a build-tool release to pick up this change?

@tylerbutler I think so. As @alexvy86 mentioned in this PR (https://github.com/microsoft/FluidFramework/pull/13128), `async` in `common` directory depends on `@fluidframework/build-tools`, so I think it'd be the best to publish a new version of `build-tools` and then apply the subsequent changes to remaining repos.

**Comment by tylerbutler** [comment]
@jikim-msft @alexvy86 I'm wondering if this can be addressed with a lockfile-only update. The dependency ranges should already be compatible with the new patch of async, so can we avoid pushing a new version of build-tools just for this?

**Comment by tylerbutler** [comment]
> @jikim-msft @alexvy86 I'm wondering if this can be addressed with a lockfile-only update. The dependency ranges should already be compatible with the new patch of async, so can we avoid pushing a new version of build-tools just for this?

If that's not possible, I have another change that I'm trying to get in tomorrow so maybe we can piggyback.

**Comment by jikim-msft** [comment]
> @jikim-msft @alexvy86 I'm wondering if this can be addressed with a lockfile-only update. The dependency ranges should already be compatible with the new patch of async, so can we avoid pushing a new version of build-tools just for this?

@tylerbutler Ah, makes sense! I'll first try to update the dependencies within `common` after merging this in and see if everything works okay.

**Pull request merged**
