### PR TITLE
Remove DeltaManagerProxy and QuorumProxy, deprecate IDisposable on IDeltaManager, IQuorumClients, IQuorumProposals

### PR DESCRIPTION
**Pull request by ChumpChief**
[AB#4864](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4864)

These don't work currently.  If we later decide we want a real proxying mechanism we can safely add it in since it's not public anyway.

Also lifted getSpecifiedCodeDetails out of the context so we can just pass an IQuorumClients, now Container is the only thing with direct access to the full IQuorum including IQuorumProposals.

Deprecated the IDisposable members from these interfaces as well, as we should consolidate the disposal ability with the owners of the objects and not permit random callers to dispose them.

### CODE REVIEW

**Comment by ChumpChief** [comment]
@tylerbutler I'm not sure if I need to do an additional changeset thing for the protocol-definitions changes - I added a changeset but I'm wondering if I need to run a second command targeting that location in addition?

**Comment by tylerbutler** [comment]
> @tylerbutler I'm not sure if I need to do an additional changeset thing for the protocol-definitions changes - I added a changeset but I'm wondering if I need to run a second command targeting that location in addition?



> @tylerbutler I'm not sure if I need to do an additional changeset thing for the protocol-definitions changes - I added a changeset but I'm wondering if I need to run a second command targeting that location in addition?

For protocol-definitions, add an entry to the CHANGELOG.md file for the package directly. As far as I can tell, protocol-defs 2.0 has never been released, so add it to that section and remove the date. We'll need to figure out when to release protocol-defs 2.0.

**Comment by ChumpChief** [comment]
Hi folks!  If you have a chance to review this I'd appreciate it.  Comes with a nice bundle size win :)

**Review by RishhiB — APPROVED** [review]
Looks good to me, nit theres some double spaces in the descriptions, but up to you to remove them!

**Comment by ChumpChief** [comment]
Yeah, I'm old-fashioned about always double-spacing :-P Changed to single spacing in latest.

**Pull request merged**
