### PR TITLE
build(client): remove unused @internal re-exports

### PR DESCRIPTION
**Pull request by jason-ha**
Note: api reports suggest there is an export change, but there is no public or beta export change. The report was incorrect.

### CODE REVIEW

**Comment by anthony-murphy** [comment]
The api reports look correct to me. I don't understand how this isn't a breaking change. Types were exported, but now they are not. am i missing something?

**Comment by Josmithr** [comment]
> Note: api reports suggest there is an export change, but there is no public or beta export change. The report was incorrect.

Is this true? Does our rollup logic look at release tags on members of other packages? If so, does it _only_ look at release tags of other _Fluid_ packages? Not particularly likely, but if an external library happens to be using release tags on their APIs, we may be inadvertently applying our release tag semantics against external things, which we shouldn't be doing.

**Comment by jason-ha** [comment]
> The api reports look correct to me. I don't understand how this isn't a breaking change. Types were exported, but now they are not. am i missing something?

They were not exported via any path except `/internal` which is not in breaking scope. (I mean anything can breaking, but these are fine.)
The API report does not understand re-exports well, but our generated "roll up" files do. Our tooling needed to make sure they weren't exporting anything extra. We don't commit our generated "roll up" files so I only manually confirmed that there is no change in any of the public.d.ts, beta.d.ts, and legacy.d.ts files. (You don't see a container-definitions.legacy.alpha.api.md change here because that report is now generated from legacy.d.ts. The change use to legacy.d.ts "roll up" for generating report is what brought this funkiness to our attention. See #21451.)

**Comment by jason-ha** [comment]
> > Note: api reports suggest there is an export change, but there is no public or beta export change. The report was incorrect.
> 
> Is this true? Does our rollup logic look at release tags on members of other packages? If so, does it _only_ look at release tags of other _Fluid_ packages? If an external library happens to be using release tags on their APIs, we may be inadvertently applying our release tag semantics against external things, which we shouldn't be doing.

It only looks for tags on things that are _exported_. And it does go back to the source for those. If we re-export something from a foreign package (I don't think we do), then it would be looking at those tags. We should be generating our reports from our "roll ups" to have the best reports. We can't quite do that yet though. We need some policy to make sure the right "roll up" is used and we need to fix the `@packageDocumentation` issue.

**Review by anthony-murphy — APPROVED** [review]
took a look at the roll ups and it makes sense now. thanks for the explanation.

**Comment by Josmithr** [comment]
> > > Note: api reports suggest there is an export change, but there is no public or beta export change. The report was incorrect.
> > 
> > 
> > Is this true? Does our rollup logic look at release tags on members of other packages? If so, does it _only_ look at release tags of other _Fluid_ packages? If an external library happens to be using release tags on their APIs, we may be inadvertently applying our release tag semantics against external things, which we shouldn't be doing.
> 
> It only looks for tags on things that are _exported_. And it does go back to the source for those. If we re-export something from a foreign package (I don't think we do), then it would be looking at those tags. We should be generating our reports from our "roll ups" to have the best reports. We can't quite do that yet though. We need some policy to make sure the right "roll up" is used and we need to fix the `@packageDocumentation` issue.

To be safe, we should probably _only_ consider tags on items from external packages if they are one of ours. API-Extractor (at least in theory) controls this policy via the `bundledPackages` option. For our bespoke tooling, we can probably just filter it to `fluid-framework` and packages in our short list of namespaces.

**Comment by jason-ha** [comment]
> To be safe, we should probably _only_ consider tags on items from external packages if they are one of ours. API-Extractor (at least in theory) controls this policy via the `bundledPackages` option. For our bespoke tooling, we can probably just filter it to `fluid-framework` and packages in our short list of namespaces.

I don't know what that practically means. Our packages will export an API or not. For those exported APIs, we need to determine where to export it. Are you saying that we should just never export foreign APIs (effectively internal)? The alternative is always export foreign APIs (effectively public). Generally seems best not to export foreign APIs. Does seem worth a work item. Do you have a post-2.0 place to collect such work?

**Pull request merged**
