### PR TITLE
Pipeline changes to enable publishin GitRest npm packages

### PR DESCRIPTION
**Pull request by hedasilv**
Following up on #9550 and making pipeline changes in order to be able to publish both npm packages and docker images for GitRest.

### CODE REVIEW

**Comment by hedasilv** [comment]
Hey @curtisman, we are making some changes to enable publishing GitRest as an npm package. Please let me know if there is anything I missed here in this PR! Thank you 😄

**Comment by heliocliu** [comment]
what's the publishing behavior for this package?  e.g. is it only going to be published on demand, etc?

**Comment by hedasilv** [comment]
> what's the publishing behavior for this package? e.g. is it only going to be published on demand, etc?

Our intention is to have GitRest be published on the same cadence as routerlicious and historian packages. That is, once we make changes to it, new packages should be generated in the internal feed, and then every now and then we release the packages publicly on npm (I believe that is how it works for historian and r11s today)

**Comment by heliocliu** [comment]
> > what's the publishing behavior for this package? e.g. is it only going to be published on demand, etc?
> 
> Our intention is to have GitRest be published on the same cadence as routerlicious and historian packages. That is, once we make changes to it, new packages should be generated in the internal feed, and then every now and then we release the packages publicly on npm (I believe that is how it works for historian and r11s today)

Gotcha.  We publish r11s (server) on the same cadence as client assuming it has changes just fyi

**Review by heliocliu — APPROVED** [review]

**Pull request merged**
