### PR TITLE
[0.56 bump] package version for client (patch)

### PR DESCRIPTION
**Pull request by sonalivdeshpande**
```
            @fluidframework/build-common:     0.24.0 (unchanged)
     @fluidframework/eslint-config-fluid:     0.26.0 (unchanged)
      @fluidframework/common-definitions:     0.21.0 (unchanged)
            @fluidframework/common-utils:     0.33.0 (unchanged)
         @fluidframework/core-interfaces:     0.42.1 (unchanged)
    @fluidframework/protocol-definitions:   0.1027.0 (unchanged)
      @fluidframework/driver-definitions:     0.44.1 (unchanged)
   @fluidframework/container-definitions:     0.45.1 (unchanged)
                                  Server:   0.1035.0 (unchanged)
                                  Client:     0.56.9 -> 0.56.10
                  @fluid-tools/benchmark:     0.40.0 (unchanged)
                         generator-fluid:      0.3.0 (unchanged)
                             tinylicious:      0.4.0 (unchanged)
     @fluidframework/azure-local-service:      0.1.0 (unchanged)
                             dice-roller:      0.0.1 (unchanged)
```

### CODE REVIEW

**Comment by markfields** [comment]
@sdeshpande3 - Before you merge. I want to take a look and see if this will cause any test validation problems that we should fix in this PR.

**Review by heliocliu — APPROVED** [review]

**Comment by markfields** [comment]
Ok of course not because test validation only applies across major version bumps.  All good.

**Review by markfields — APPROVED** [review]

**Comment by heliocliu** [comment]
but like, 10 patches :(

**Comment by sdeshpande3** [comment]
`npm run ci:test` got cancelled 😢

**Pull request merged**
