### PR TITLE
Fixing the paths to related README.md files

### PR DESCRIPTION
**Pull request by arafat-java**
## Description
Path to README files for fetch-tool and Fluid Debugger were incorrect and leading to **404 - page not found**
Present paths (incorrect) were as follows

- https://github.com/microsoft/FluidFramework/blob/main/packages/tools/fluid-fetch/README.md
- https://github.com/microsoft/FluidFramework/blob/main/packages/drivers/fluid-debugger/README.md

Corrected paths are as follows

- https://github.com/microsoft/FluidFramework/blob/main/packages/tools/fetch-tool/README.md
- https://github.com/microsoft/FluidFramework/blob/main/packages/drivers/debugger/README.md

### CODE REVIEW

**Review by Josmithr — APPROVED** [review]

**Comment by Josmithr** [comment]
@arafat-java Thank you for the fix!!

**Comment by arafat-java** [comment]
@Josmithr It is waiting on "Validate CODEOWNERS Expected — Waiting for status to be reported"

**Comment by Josmithr** [comment]
> @Josmithr It is waiting on "Validate CODEOWNERS Expected — Waiting for status to be reported"

@arafat-java Can you elaborate on where you're seeing that? The PR has already been merged, so there shouldn't be any remaining checks.

**Comment by arafat-java** [comment]
> > @Josmithr It is waiting on "Validate CODEOWNERS Expected — Waiting for status to be reported"
> 
> @arafat-java Can you elaborate on where you're seeing that? The PR has already been merged, so there shouldn't be any remaining checks.

All good now, yesterday while it had not merged it was waiting

**Pull request merged**
