### PR TITLE
tools(client): regenerate pnpm lock file

### PR DESCRIPTION
**Pull request by jason-ha**
Steps:
1. pnpm i --frozen-lockfile
2. pnpm store prune
3. pnpm i --frozen-lockfile
4. pnpm i

### CODE REVIEW

**Review by tylerbutler — CHANGES_REQUESTED** [review]
I cannot replicate these changes on a mac.

**Comment by jason-ha** [comment]
> I cannot replicate these changes on a mac.

I have looked into the prettier dev change and the ts-jest changes and confirmed that they are appropriate.
If you switch to this branch, then do `pnpm i --frozen-lockfile` followed by `pnpm i`, do you see changes? If not, then these will work for everyone. If you do see changes, then we need to understand why your pnpm thinks there is a non-dev prettier dep and why it is okay for all ts-jest users to have a babel/core dependency.

**Comment by jason-ha** [comment]
> It changed the ts-jest refs back to `ts-jest: 29.1.1_7c6s2cwl7nw46fjeerv4uupgbm`
> 
> I did those same steps against main and it produced this: [5c70535](https://github.com/microsoft/FluidFramework/commit/5c705351c11581b33966083de4f970aedea3793d)

If you are going to try those steps, the prune has to be done on every enlistment that might be sharing the store (as I've been told). Usually that only impacts some quirky version bumps which is not the issue here.
I don't know why it would be okay for so many of the ts-jest dependents to have @babel/core in there. Without that explanation this change still looks correct to me.

**Review by DLehenbauer — APPROVED** [review]
I'm going to claim that the result from a clean codespace is authoritative.  (One reason is that codespace is a platform that all team members have access to.)

@tylerbutler - I'm guessing that adding '--prefer-frozen-lockfile' to the last 'pnpm i' doesn't change the results, but might be worth a try?

I wonder if we can safely delete `/Users/<username>/Library/pnpm/store` to "factory reset" the PNPM store without having to track down every repo on a machine.

**Review by tylerbutler — APPROVED** [review]
Go ahead and merge. We'll just have to keep our eyes peeled for unexpected changes coming from other mac users.

**Comment by jason-ha** [comment]
@tylerbutler & @DLehenbauer, I ran a test on CI.
I added lines to run `pnpm i --no-frozen-lockfile` and check the results.
With the above changes - [no diff](https://dev.azure.com/fluidframework/public/_build/results?buildId=247404&view=logs&j=0a267589-51b1-5666-1e58-38835ac8a8c1&t=161dc727-974a-5756-f6a1-34a7e64b9208&l=96)
Just from main (pre-merge) - [diffs we expected](https://dev.azure.com/fluidframework/public/_build/results?buildId=247390&view=logs&j=0a267589-51b1-5666-1e58-38835ac8a8c1&t=161dc727-974a-5756-f6a1-34a7e64b9208&l=165)

Don't know what is up on your system, Tyler :/

**Pull request merged**
