### PR TITLE
Added documentation page for Blazor, ASP.NET and Generic dotnet 

### PR DESCRIPTION
**Pull request by MahmudX**

### CODE REVIEW

**Comment by tylerbutler** [comment]
Hi @MahmudX! Thanks for this PR! We try to only add documentation placeholders for docs that we plan to write, and we don't currently have plans to write any documentation regarding Blazor or dotnet. So I won't merge this PR.

Having said that, please do file an issue with more information about what you expect from this documentation, why it is relevant to you, etc. Then we can evaluate it along with other requests.

**Comment by MahmudX** [comment]
> please do file an issue with more information about what you expect from this documentation, why it is relevant to you

C'mon, I'm a .NET developer and I want to use it in my apps. Also, I got disappointed when you said that you guys will not write docs on your (Microsoft) product such as DotNet or Blazor. This is absurd.

**Comment by MahmudX** [comment]
Wait, why this pull request was closed this wasn't solved and there must be some way to get fluid components in .NET. it's kind of funny that Microsoft does not support their own products with latest technologies.

**Comment by tylerbutler** [comment]
@MahmudX We try to only add documentation placeholders for docs that we plan to write within a sprint or two, and we don't currently have plans to write any documentation regarding Blazor in that timeframe. That's why this PR wasn't merged.

That said, there is an open issue (#8767) requesting examples of integrating Blazor components with Fluid. If you have more details to share about what you're looking for out of this documentation, it would be helpful to add it to that issue.

**Pull request closed without merging**
