### PR TITLE
refactor(server): Update typetests to correct previous version

### PR DESCRIPTION
**Pull request by alexvy86**
## Description

Type tests were still using the 2.0 release of server as reference instead of 4.0. Updated them using `npx flub typetests -v -p --reset --releaseGroup=server` from `server/routerlicious` and then updated the "broken" section of package.json files as necessary to get the tests to pass, and reverting the changes to tinylicious' package.json (updated by the command to use type-tests; it doesn't have any today, and adding them to it is not part of this PRs purpose).

This gets rid of several older dependencies in the server/routerlicious lockfile (e.g. axios 0.26.1), which will contribute towards Component Governance not flagging our pipeline runs for referencing deps with CVEs.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

### CODE REVIEW

**Review by tylerbutler — CHANGES_REQUESTED** [review]
In the tinylicious package.json, add this:

```json
"typeValidation": {
  "disabled": true,
  "broken": {}
}
```

For future you can just run `pnpm typetests:prepare` followed by `pnpm typetests:gen` so you don't have to remember/look up flub commands.

**Comment by tylerbutler** [comment]
> For future you can just run pnpm typetests:prepare followed by pnpm typetests:gen so you don't have to remember/look up flub commands.

And doing it this way is preferred because it uses the release-group-local version of flub.

**Comment by alexvy86** [comment]
> In the tinylicious package.json, add this:
> 
> ```json
> "typeValidation": {
>   "disabled": true,
>   "broken": {}
> }
> ```

I reverted it after flub added it, to leave tinylicious fully untouched 😄 . But I'm also ok having it, I'll add it. The tool also added a dev dep on the previous version, that one I'd rather not re-add since it wouldn't be doing anything.

**Comment by tylerbutler** [comment]
> > In the tinylicious package.json, add this:
> 
> > 
> 
> > ```json
> 
> > "typeValidation": {
> 
> >   "disabled": true,
> 
> >   "broken": {}
> 
> > }
> 
> > ```
> 
> 
> 
> I reverted it after flub added it, to leave tinylicious fully untouched 😄 . But I'm also ok having it, I'll add it. The tool also added a dev dep on the previous version, that one I'd rather not re-add since it wouldn't be doing anything.

I think if you run prepare again after disabling them in package.json it will remove the dep, but I might be wrong. Regardless removing the dep is correct.

**Comment by tylerbutler** [comment]
And disabling it will save the next person the hassle you've run into.

**Review by tylerbutler — APPROVED** [review]

**Pull request merged**
