### PR TITLE
Deprecate core-utils package

### PR DESCRIPTION
**Pull request by ChumpChief**
Only remaining member is compareArrays, which is not used anywhere in our repo (PropertyDDS and Tree both use their own versions, which is preferable for minimizing public surface area).

If no objections, I'll follow up with removing it in next branch.

### CODE REVIEW

**Comment by tylerbutler** [comment]
I'm pretty sure @DLehenbauer **just** added this package.

**Comment by ChumpChief** [comment]
Hah, guess I should have done my research first.  I must have been thinking about /common/lib/common-utils instead of /packages/common/core-utils.  Why the separate package?

In any case, my opinion is still that we shouldn't publish utilities.  Publishing general utilities is public surface area a customer can take a dependency on, which I assume was not a goal here.  It looks like pulling it into its own package was more about code sharing/deduplication/bundle size, but IMO that's not worth the tradeoff of public API surface.

And for this specific example, even if we were to start consuming this package where we do compareArrays today the only durable location that would depend on it is SharedTree (other users are PropertyDDS and legacy SharedTree which have limited lifespan).

Would love to learn more about the motivations for the separate package, and would probably be good to socialize on what we want publicly accessible from our API surface.

**Comment by curtisman** [comment]
@ChumpChief Do you have any idea on the best way to share code across multiple packages, without it becomes a public API surface?

**Comment by ChumpChief** [comment]
> @ChumpChief Do you have any idea on the best way to share code across multiple packages, without it becomes a public API surface (in general)?

I'd take it on a case-by-case basis -- unless I'm missing some context, this specific example doesn't seem to demonstrate a need for sharing yet (only durable usage would be in SharedTree), so I'd probably defer any attempts to share until a second or third durable consumer appears.  Otherwise we're frontloading the cost of expanded public API surface without receiving a corresponding benefit.

I believe this pattern is a problem for many members of our various "utils" packages - folks add items they believe to be generally useful despite not having a second customer at the time, but over time no customer is ever found.  Our utils packages also tend to have ambiguous purpose, and so over time they accumulate an unclear assortment of functionality and layering.  Just to pick on one, consider driver-utils:

- InsecureUrlResolver - a demo tool only intended for examples, not safe for any layer to consume
- MapWithExpiration - one consumer, in the driver
- BlobAggregationStorage - one consumer, in the tools
- MultiDocumentServiceFactory - one consumer in the FF repo, in the loader.  External customers consume it at the app/host layer to pass into the loader (though I would personally recommend against anyone consuming it due to the nonstandard usage of protocol #9236).
- isRuntimeMessage - consumed by a variety of layers (driver, loader, runtime)

So I'd probably propose some criteria like the following for establishing new utils packages:
1. We know at least 2-3 durable places where we will immediately consume it (otherwise just include it locally)
1. We believe our team can deliver unique value in producing this package as opposed to consuming or contributing to an existing library (i.e. our mission isn't to be a React or lodash competitor)
1. The utils package has a clearly defined, distinct purpose from our other utils packages, and a clear position in our layering
1. The duplication is painful (large bundle size, many usages, error-prone code) - e.g. isRuntimeMessage doesn't meet this bar.

**Comment by tylerbutler** [comment]
Is the goal for sharing the code to reduce maintenance costs? That is, there's only one copy to maintain,fix bugs in, test, etc. If so, I think we could explore some tools to address those problems while still shipping separate copies of the shared code.

**Comment by curtisman** [comment]
@ChumpChief is it possible that we declare some package to not be public API? and only for our internal use purpose?

**Comment by tylerbutler** [comment]
> @ChumpChief  I am not pushing back on not creating package or sharing code unnecessarily, but in general, is it possible that we declare some package to not be public API? and only for our internal use purpose?  

@curtisman @ChumpChief This is one application of the `@internal` api decorator in api-extractor. I think we should include those capabilities when deciding how best to meet our needs. @Josmithr and @CraigMacomber have experience with it and I think there are some nice benefits.

**Comment by ChumpChief** [comment]
The internal tag Tyler mentions can be helpful for documentation, but obv. isn't as strong as simply eliminating the surface. 
 TBH I haven't really given code sharing much thought since I don't perceive duplication as being a major problem in our repo at the moment.

I expect we'll develop some new ideas as part of the API surface reduction effort, since we'll want to improve on the should-be-private packages that do get consumed in multiple places today.  But even when private, I think this speculative sharing tends to overcomplicate the repo.

**Comment by ssimic2** [comment]
> > @ChumpChief Do you have any idea on the best way to share code across multiple packages, without it becomes a public API surface (in general)?
> 
> I'd take it on a case-by-case basis -- unless I'm missing some context, this specific example doesn't seem to demonstrate a need for sharing yet (only durable usage would be in SharedTree), so I'd probably defer any attempts to share until a second or third durable consumer appears. Otherwise we're frontloading the cost of expanded public API surface without receiving a corresponding benefit.
> 
> I believe this pattern is a problem for many members of our various "utils" packages - folks add items they believe to be generally useful despite not having a second customer at the time, but over time no customer is ever found. Our utils packages also tend to have ambiguous purpose, and so over time they accumulate an unclear assortment of functionality and layering. Just to pick on one, consider driver-utils:
> 
> * InsecureUrlResolver - a demo tool only intended for examples, not safe for any layer to consume
> * MapWithExpiration - one consumer, in the driver
> * BlobAggregationStorage - one consumer, in the tools
> * MultiDocumentServiceFactory - one consumer in the FF repo, in the loader.  External customers consume it at the app/host layer to pass into the loader (though I would personally recommend against anyone consuming it due to the nonstandard usage of protocol [Stop using non-standard protocols in URLs and switch to native URL() over url-parse #9236](https://github.com/microsoft/FluidFramework/issues/9236)).
> * isRuntimeMessage - consumed by a variety of layers (driver, loader, runtime)
> 
> So I'd probably propose some criteria like the following for establishing new utils packages:
> 
> 1. We know at least 2-3 durable places where we will immediately consume it (otherwise just include it locally)
> 2. We believe our team can deliver unique value in producing this package as opposed to consuming or contributing to an existing library (i.e. our mission isn't to be a React or lodash competitor)
> 3. The utils package has a clearly defined, distinct purpose from our other utils packages, and a clear position in our layering
> 4. The duplication is painful (large bundle size, many usages, error-prone code) - e.g. isRuntimeMessage doesn't meet this bar.

Agree with points you called out here. We should set the bar and clearly call out criteria for introducing new package(s). To help us reason about best practices and get the ball rolling it is very helpful to be specific and have concrete examples and questions we can ask. Narrowing on "utils" topic/context is a good example. And by default we should opt in to "not create new packages", unless we meet the bar that we stated. We can always discuss/conclude/modify what that bar represents. I'm ok with this change, but of course I'd make sure that original author is onboard as well.

@ChumpChief given that we will be making a push to cleanup some of the API/package surface it may be worthwhile finding a way to share broader effort, so reviewers have a better reference on the current size of our API surface, problems we are trying to solve, how they should think of API changes (internal vs external, experimental etc) - basically some of the "vehicles" we discussed today with FF team.

**Review by ssimic2 — APPROVED** [review]

**Comment by ChumpChief** [comment]
@anthony-murphy @DLehenbauer would love your thoughts on this since y'all added the package.  Also noticed that we only have internal/dev versions published currently, so might reframe this to directly remove the package rather than going through `next`.

**Comment by ChumpChief** [comment]
Followed up with @DLehenbauer -- he's going to have a PR that more clearly marks the package as for internal use only, plus some updates to the layer-check to clarify its role there.  Closing this for now, though I expect we'll need to revisit consolidation/reorganization of our many utils packages still.

**Comment by DLehenbauer** [comment]
@ChumpChief - Thank you for the advice on how to leverage @internal and layer-check.  The related PR is #14422.

**Pull request closed without merging**
