### PR TITLE
Move Protocol Defs to Common

### PR DESCRIPTION
**Pull request by anthony-murphy**
In attempt to improve our back compact guarantees and reduce the need to publish unchanged packages we are going to move a number of packages to the common folder. The chain of packages starts with protocol-definitions.

### CODE REVIEW

**Comment by tanviraumi** [comment]
@curtisman and I have discussed this and there an issue to track the work (https://github.com/microsoft/FluidFramework/issues/6073). However, the plan was to create a top level folder called protocol to make sure only to track breaking protocol changes and not others.

@curtisman thoughts on moving to common folder?

**Comment by anthony-murphy** [comment]
this doesn't have to be the final place, but is inline with what we already use common for. also we can't lock container def or driver defs until this is done. also this doesn't hook up a publishing plan, that will have to be done next

**Comment by tanviraumi** [comment]
I think common works too. But I want to move protocol-base there as well. So for now, we will have two protocol packages inside common and later on if we need more, we can reopen the discussion to create a separate folder. Does that sound reasoanable?

**Comment by tylerbutler** [comment]
Suggest a new top level folder because conceptually the protocol packages are a unit, and are versioned together but independently of other packages.

**Comment by anthony-murphy** [comment]
there is on one protocol package. and this get build for free

**Comment by tanviraumi** [comment]
> there is on one protocol package. and this get build for free

@anthony-murphy Did not get that.

@tylerbutler I am fine with both options for now. This one can be an interim solution which will allow us to lock container/driver packages. And then we can create a separate folder as well.

**Comment by tylerbutler** [comment]
@anthony-murphy I'm confused. What is [protocol-base](https://fluidframework.com/docs/apis/protocol-base/) if not a protocol package?

**Comment by anthony-murphy** [comment]
protocol-base is an implementation, not a definitional package, so it doesn't define anything that crosses a layer boundary, it provides concretions. As long as both side agree on the definition, which concretion doesn't really matter

**Comment by tanviraumi** [comment]
Yeah I am concerned about those iffy thing. I don't have a full list but eventually, some of them should move to protocol-def. But thats a relatively bigger change requires multiple iterations. Since we are staging it, we may just want to move it to common as well and unblock rest of the work. Thoughts?

**Comment by tanviraumi** [comment]
Another reason for locking protocol-base is the quorum stuff inside. The piece of code is shared between everyone and I want people to be more deliberate before changing this.

**Comment by anthony-murphy** [comment]
For now i'm only worried about protocol def, driver def, and container def. i agree quorum is critical, but i'm not sure it falls into the same layer as defs. regardless that should be a follow up.

**Comment by tanviraumi** [comment]
Sounds good. I have opened an issue #6170 so lets discuss it there.

When are you planning to change the build and publishing step?

**Review by tanviraumi — APPROVED** [review]

**Comment by anthony-murphy** [comment]
the goal is to release 0.40 this week, but with pinned versions of the defs. once that's enabled, we'll start looking into the rest of the automation. we also need to figure out our release cadence for these layers, with the intent of keeping them more stable.

**Pull request merged**
