### PR TITLE
[bump] client: 2.0.6 => 2.0.7 (patch)

### PR DESCRIPTION
**Pull request by clarenceli-msft**
Bumped client from 2.0.6 to 2.0.7.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

> List any specific things you want to get reviewer opinions on, and anything a reviewer would need to know to review this PR effectively.
> Things you might want to include:
>
> -   Questions about how to properly make automated tests for your changes.
> -   Questions about design choices you made.
> -   Descriptions of how to manually test the changes (and how much of that you have done).
> -   etc.
>
> If you have any questions in this section, consider making the PR a draft until all questions have been resolved.

### CODE REVIEW

**Comment by jatgarg** [comment]
There should be no changes to pnpm file.

**Comment by clarenceli-msft** [comment]
> There should be no changes to pnpm file.

**Comment by clarenceli-msft** [comment]
> There should be no changes to pnpm file.

it might be because I run `pnpm install`, I will create a new PR

**Comment by jatgarg** [comment]
@clarenceli-msft Maybe just revert all changes in pnpm lock file/

**Pull request closed without merging**
