### PR TITLE
Add json2csv to lock file

### PR DESCRIPTION
**Pull request by kian-thompson**
Detected by internal build failure:
https://dev.azure.com/fluidframework/internal/_build/results?buildId=96394&view=logs&j=189bf95d-4688-543c-ef32-29eb64497bc0&t=1c6f3587-845d-5f13-dc31-cb3212cc3bd0

### CODE REVIEW

**Comment by tyler-cai-microsoft** [comment]
Was it running `npm i` that fixed it?

**Review by tylerbutler — APPROVED** [review]

**Comment by tylerbutler** [comment]
Merging to get the build unblocked.

**Comment by kian-thompson** [comment]
> Was it running `npm i` that fixed it?

Running `npm build:fast -- --install` updated the lerna package lock, which I assume is expected to be the one working on the dependencies in lower levels

**Comment by kian-thompson** [comment]
@tylerbutler As a future note, is it possible to have this issue caught in PR builds?

**Comment by tylerbutler** [comment]
@kian-thompson it should have been. I don't understand how the original PR did not fail.

**Pull request merged**
