### PR TITLE
Mock logger: validate expected log events in Unit Tests

### PR DESCRIPTION
**Pull request by markfields**
This moves the MockLogger added in #4290 to a utils package for broader use.  i.e. it could have been used in the tests added in @anthony-murphy's PR #4406.

I wanted to put it in a test package that's typically included as a dev dependency, but couldn't find one suitable.  Hopefully this is ok - assuming no product code takes a dependency on this class, will it be "tree shaken" out when our packages are webpacked...?

Or, would it be better for me to add a new package.  Or maybe update the mocha-test-setup package to be a general Unit Test utils package?

### CODE REVIEW

**Comment by anthony-murphy** [comment]
i think i'd prefer a new or test specific package

**Comment by markfields** [comment]
K.  I prefer it being in a test package too.  I will co-opt the mocha-test-setup package (which currently contains exactly 2 functions) as `@fluidframework/unit-test-utils` and put it in there.

**Review by anthony-murphy — APPROVED** [review]

**Comment by markfields** [comment]
New plan - test-runtime-utils doesn't have too much baggage so I'll put it there for now. The mocha package needs to stay just about the hooks.

**Comment by markfields** [comment]
@anthony-murphy - how does test-runtime-utils seem as its home for now?

**Comment by anthony-murphy** [comment]
looks good to me

**Pull request merged**
