### PR TITLE
build(build-tools): Upgrade oclif

### PR DESCRIPTION
**Pull request by tylerbutler**
Upgrades all oclif packages to the latest except oclif/test, which will require further test changes to upgrade. See #21920.

I also deleted the custom oclif readme wrapper we had, because it doesn't work with the new version of oclif. What we lose is the automatic "usage" section in the README. Now that section is hardcoded. The reason is that `oclif readme` always outputs the platform and version, and the version is always unique when running in the CI pipeline. I don't think this is a big loss.

### CODE REVIEW

**Review by jason-ha — COMMENTED** [review]
Can we get rid of aws before this?

**Comment by tylerbutler** [comment]
> Can we get rid of aws before this?

Done in https://github.com/microsoft/FluidFramework/pull/22032

**Review by jason-ha — COMMENTED** [review]
There are a lot of dependencies that became non-dev dependencies (according to lockfile). (There were also a lot of prod deps that became devDeps; no concerns there. :) )
I would like to understand why they are prod deps now.
I picked on one that change (`typed-array-byte-offset@1.0.0`) and found that it had been a devDep via eslint plugins. Example via `eslint-config-oclif-typescript`. I don't know why this PR would change this. Please have a look.
`pnpm why -r --prod typed-array-byte-offset@1.0.0` should point out an example.

**Comment by tylerbutler** [comment]
> There are a lot of dependencies that became non-dev dependencies (according to lockfile). (There were also a lot of prod deps that became devDeps; no concerns there. :) ) I would like to understand why they are prod deps now. I picked on one that change (`typed-array-byte-offset@1.0.0`) and found that it had been a devDep via eslint plugins. Example via `eslint-config-oclif-typescript`. I don't know why this PR would change this. Please have a look. `pnpm why -r --prod typed-array-byte-offset@1.0.0` should point out an example.

I checked some, and every one I checked is coming from the prod dep chain of oclif/plugin-commands. The ones I checked:

- typed-array-byte-offset
- array.prototype.flat
- arraybuffer.prototype.slice
- available-typed-arrays
- camelcase
- es-to-primitive
- is-boolean-object
- object-keys
- safe-regex-test
- which-typed-array

Most of them seem to come through a dep called es-abstract, which plugin-commands now depends on.

**Comment by jason-ha** [comment]
> > There are a lot of dependencies that became non-dev dependencies (according to lockfile). (There were also a lot of prod deps that became devDeps; no concerns there. :) ) I would like to understand why they are prod deps now. I picked on one that change (`typed-array-byte-offset@1.0.0`) and found that it had been a devDep via eslint plugins. Example via `eslint-config-oclif-typescript`. I don't know why this PR would change this. Please have a look. `pnpm why -r --prod typed-array-byte-offset@1.0.0` should point out an example.
> 
> I checked some, and every one I checked is coming from the prod dep chain of oclif/plugin-commands. The ones I checked:
> 
> * typed-array-byte-offset
> * array.prototype.flat
> * arraybuffer.prototype.slice
> * available-typed-arrays
> * camelcase
> * es-to-primitive
> * is-boolean-object
> * object-keys
> * safe-regex-test
> * which-typed-array
> 
> Most of them seem to come through a dep called es-abstract, which plugin-commands now depends on.

Thanks for looking - at least they won't be production in client/server.

**Review by jason-ha — APPROVED** [review]

**Pull request merged**
