### PR TITLE
Increase Canary Stress Timeout to 4 hours

### PR DESCRIPTION
**Pull request by RishhiB**
https://dev.azure.com/fluidframework/internal/_build/results?buildId=155905&view=logs&j=c7213352-638b-50b5-3c0e-1624a2e64f62&t=b07448fb-6653-5288-d115-8a4b2a0b6833&l=24 is timing out, seeing if thats the only issue

### CODE REVIEW

**Comment by anthony-murphy** [comment]
i'd rather us reduce the config to fit in the two hour window, as increasing the timeout will keep the lock held longer and slow down subsequent runs.

**Comment by Josmithr** [comment]
> i'd rather us reduce the config to fit in the two hour window, as increasing the timeout will keep the lock held longer and slow down subsequent runs.
> 
> the current error rate is crazy high already, so its not like a longer run will be healthier

I believe (@RishhiB correct me if I'm wrong) that this is intended to be a temporary mitigation while we investigate the root cause for the time increase. If so, we should add a comment to that effect in both the PR description and on the line where we increased the timeout in the pipeline template.

**Comment by anthony-murphy** [comment]
> > i'd rather us reduce the config to fit in the two hour window, as increasing the timeout will keep the lock held longer and slow down subsequent runs.
> > the current error rate is crazy high already, so its not like a longer run will be healthier
> 
> I believe (@RishhiB correct me if I'm wrong) that this is intended to be a temporary mitigation while we investigate the root cause for the time increase. If so, we should add a comment to that effect in both the PR description and on the line where we increased the timeout in the pipeline template.

why not just let it fail. what purpose does letting it run longer serve. it consumes resources and prevents other runs so it does matter.

**Comment by anthony-murphy** [comment]
> > > > i'd rather us reduce the config to fit in the two hour window, as increasing the timeout will keep the lock held longer and slow down subsequent runs.
> > > > the current error rate is crazy high already, so its not like a longer run will be healthier
> > > 
> > > 
> > > I believe (@RishhiB correct me if I'm wrong) that this is intended to be a temporary mitigation while we investigate the root cause for the time increase. If so, we should add a comment to that effect in both the PR description and on the line where we increased the timeout in the pipeline template.
> > 
> > 
> > why not just let it fail. what purpose does letting it run longer serve. it consumes resources and prevents other runs so it does matter.
> 
> (Sorry, I initially edited your reply while trying to reply to it 😅 I think I restored it to its original contents.)
> 
> It sounds like the tests are succeeding with the bumped timeout (again, @RishhiB correct me if I'm wrong), and there is a difference between tests running too long, and tests actually failing in ways we may want to detect. I'm not necessarily arguing one way or the other here (either way we need to reduce the amount of time being taken), but until we fix that, the constant failures due to timeouts can make it harder for us to detect real issues.

we don't really monitor the pipeline runs themselves. it all comes for logged error rate. i wouldn't make this change.

**Comment by ssimic2** [comment]
Stress tests on FRS prod/canary should not be taking more then ~30mins.  https://dev.azure.com/fluidframework/internal/_build/results?buildId=157361&view=results. If the test takes more then 2hours, we need to understand why. @Josmithr I know you are currently investigating this issue.

**Pull request closed without merging**
