### PR TITLE
[bump] build-tools: 0.16.0 => 0.17.0 (minor)

### PR DESCRIPTION
**Pull request by tylerbutler**
Bumped build-tools from 0.16.0 to 0.17.0.

### CODE REVIEW

**Review by zhenmichael — APPROVED** [review]

**Comment by zhenmichael** [comment]
Looks like there's some failing tests due to README files. Was this from another PR?

**Comment by tylerbutler** [comment]
> > Looks like there's some failing tests due to README files. Was this from another PR?
> 
> Yeah, it's been happening for a while. `build-cli` and `version-tools` have a `build:readme` npm script which updates their readme files and causes them to get flagged for extraneous modifications. Not sure what the best way forward is for that; I think I'd make it so the modifications to the readme don't include the specific version, so they don't change during CI.

I have a fix here: #15396

**Comment by alexvy86** [comment]
I don't quite get how that other PR fixes the CI build... with the npm scripts as they are today, the readme will still get regenerated, right? If we update the readme at the same time we bump the version, that prevents the "extraneous modifications" issue, but that's independent of where `generate readme` lives, right? Also branches for which we replace the versions in CI (like test/ branches) would still fail to run the pipeline.

**Comment by tylerbutler** [comment]
> I don't quite get how that other PR fixes the CI build... with the npm scripts as they are today, the readme will still get regenerated, right?

You're right; I misspoke earlier. #15396 addresses a circular dependency problem: version-tools needs build-cli to build its readme, but build-cli can't build without build-tools, which requires version-tools. All because of the readme. 😆 

One of the things the custom readme does is strip off pre-release sections of the version:

https://github.com/microsoft/FluidFramework/blob/dfaaff03b54a62d38e8b15e1b0b48a25e2f84d1e/build-tools/packages/build-cli/src/commands/generate/readme.ts#L35-L37

We could remove the version entirely, but I like having the version personally (opinion), because it basically versions the docs alongside the code. When there are changes, it's very useful to know what version of the docs you're looking at.

**Comment by alexvy86** [comment]
> One of the things the custom readme does is strip off pre-release sections of the version:

This piece is nice, but just to be clear, it doesn't address the issue with test/ branches where the "first part" of the version is also changed (to `0.0.0` if I recall correctly), correct?

**Comment by tylerbutler** [comment]
> > One of the things the custom readme does is strip off pre-release sections of the version:
> 
> This piece is nice, but just to be clear, it doesn't address the issue with test/ branches where the "first part" of the version is also changed (to `0.0.0` if I recall correctly), correct?

Sorry, I wasn't aware of that issue. I guess it would still repro, yeah.

**Pull request merged**
