### PR TITLE
r11s: upgrade build-tools

### PR DESCRIPTION
**Pull request by znewton**
## Description

~~Looks like type gens are out of date in R11s. I think this just removes the `: void` return type. Not sure why.~~

Server `build-tools` were out of date, causing unwanted type test generation diffs. Upgrading server `build-tools` dep to 0.28 from 0.26

### CODE REVIEW

**Review by pradeepvairamani — APPROVED** [review]

**Comment by anthony-murphy** [comment]
i think this is wrong. maybe your build tools are out of data. void was added recently

**Comment by znewton** [comment]
@anthony-murphy thanks! I was DM-ing with @scottn12 about this and we couldn't figure out which was "correct". I'll `rm -rf node_modules` and try again to make sure I'm up to date

**Comment by anthony-murphy** [comment]
> @anthony-murphy thanks! I was DM-ing with @scottn12 about this and we couldn't figure out which was "correct". I'll `rm -rf node_modules` and try again to make sure I'm up to date

i would also check that the build tools version matches between server and client. its possible that install order matters if there is a mismtach, in which case we may need to bump a version somewhere

**Comment by znewton** [comment]
@anthony-murphy server was at `^0.26.1`, while client is at `^0.28.0`. This is likely the problem, and thanks for pointing it out. I'll switch the purpose of this PR to be upgrading server build-tools

**Review by anthony-murphy — APPROVED** [review]

**Pull request merged**
