### PR TITLE
Increase maxListeners on DeltaManagerSummarizerProxy and AgentScheduler.

### PR DESCRIPTION
**Pull request by astegmaier**
## Description

Currently, when you load a Loop table component that is built with FluidFramework, you'll see these garbage errors in the console:

image

Because these errors mention "Memory Leak" they have been a source of confusion with our partners. Ironically, until we patched our console object to stringify all error objects, the warning message itself being logged to the console was a source of memory leaks.

This change removes the maxSafeListener check on the two classes in FluidFramework that were responsible for this noise.

The number of listeners on these classes will scale with the number of cells in your table, which could be immense. Since the "limit" is effectively `N` it seemed like removing the warnings was appropriate. They do very little to protect against actual memory leaks, which almost always come from failing to un-register a listener, not from adding too many.

### CODE REVIEW

**Comment by ChumpChief** [comment]
I don't have a particular feeling about the maximum, but it's surprising to me that you're registering listeners directly on the deltaManager - can you elaborate on what you're listening for there?

**Comment by astegmaier** [comment]
> I don't have a particular feeling about the maximum, but it's surprising to me that you're registering listeners directly on the deltaManager - can you elaborate on what you're listening for there?

@ChumpChief - I went ahead and messaged you privately about this.

**Comment by ChumpChief** [comment]
@vladsud - as mentioned above I don't have a strong opinion on the max listeners, but you might have opinions on how folks should observe the "readonly" event from DeltaManager?  I was somewhat surprised to see the reach to the delta manager, wondering if there's something more appropriate to observe?

**Comment by vladsud** [comment]
I do not know much about scenario to comment, to be honest.
I think the issue is - we do not raise (it seems) "readonly" event on data stores, which means individual components of the system do not have another way to register for these events. That would be preferred method, IMHO.
Otherwise yes, we should expect a lot of registrations...

**Comment by astegmaier** [comment]
> I do not know much about scenario to comment, to be honest. I think the issue is - we do not raise (it seems) "readonly" event on data stores, which means individual components of the system do not have another way to register for these events. That would be preferred method, IMHO. Otherwise yes, we should expect a lot of registrations...

Thanks for taking a look! If I understand correctly, the idea of raising "readonly" events on data stores would be a good future improvement for FF, but our current pattern (listening directly to DeltaManager) is the best way of doing so at the moment. @ChumpChief - in that case, would it be okay to approve this PR?

**Comment by ChumpChief** [comment]
I'll defer to Vlad since he owns readonly state - Vlad, are you saying that preferred approach is what should be done instead, or as some followup?

**Comment by astegmaier** [comment]
@vladsud - I just returned from vacation, and I wanted to see if you could take a look at @ChumpChief 's question: 

> I'll defer to Vlad since he owns readonly state - Vlad, are you saying that preferred approach is what should be done instead, or as some followup?

**Review by ChumpChief — APPROVED** [review]
Had a side conversation with @vladsud, he is OK with continuing this pattern for now.

**Pull request merged**
