### PR TITLE
Add interface for updated signal submission logic

### PR DESCRIPTION
**Pull request by GaryWilber**
Adding interfaces to support updated signal submission logic (submit_signals_v2), which allows clients to pass additional properties, a target client id for their signals, and multiple signals at once.

### CODE REVIEW

**Review by vladsud — APPROVED** [review]

**Comment by tylerbutler** [comment]
When and how do you want this change released? Protocol-defs 2.0.0 has been released, so this change should bump the version to either 2.1 or 3.0. We could release 2.1.0 with this change if needed. Otherwise the change will just sit here in the repo. We don't regularly release and integrate the common packages like this one.

**Review by tylerbutler — CHANGES_REQUESTED** [review]
Id like to work out the release plan before merge.

**Comment by GaryWilber** [comment]
> When and how do you want this change released? Protocol-defs 2.0.0 has been released, so this change should bump the version to either 2.1 or 3.0. We could release 2.1.0 with this change if needed. Otherwise the change will just sit here in the repo. We don't regularly release and integrate the common packages like this one.

@tylerbutler Thanks for bringing this up. It would be great if it could be included sooner rather than later. Is a 2.1.0 currently scheduled for release? 
The outcome of this work is to improve signals, in order to support sessions that contain a large number of clients. I will update client & server packages to use leverage these interfaces once it's available.

**Comment by tylerbutler** [comment]
@GaryWilber Thanks for the info. We can release 2.1 with this change. Two more changes needed in this PR:

1. Update the version in package.json to be 2.1.0. I don't think it's needed, but run `pnpm i` to make sure the version change doesn't change the lockfile. Actually, I'm 99% sure it doesn't, so you can probably skip this and wait for a CI failure if I'm wrong.
2. Add a 2.1 heading to the CHANGELOG along with a summary of the change.

**Review by tylerbutler — APPROVED** [review]
Your change log entry is awesome. 👍

**Pull request merged**
