### PR TITLE
fix tsconfig preventing emitting commonjs bundles

### PR DESCRIPTION
**Pull request by karlbom**
I noticed that the published package `@fluid-experimental/tinylicious-client@0.39.3` does not publish any commonjs bundle, which caused some issues importing theses packages into a nodejs application.

Looking deeper into it I noticed that the tsconfig file for these two packages have an override to emit esnext style modules instead of commonjs, which means `npm run build:commonjs`and `npm run build:esnext`will end up emitting the same bundle,

reming this override will no emit commonjs style bundles in the `dist`folder and esnext style bundles in the `lib`folder. 

It would be great if a release for this packages could be made, to make them usable in node.

@SamBroner @DLehenbauer

### CODE REVIEW

**Comment by heliocliu** [comment]
fwiw this change is covered in #6197 as well if you don't want to make it explicitly here

**Review by heliocliu — APPROVED** [review]

**Comment by tylerbutler** [comment]
#6197 is merged so this fix should be made already. @karlbom I'll publish new pre-release versions of the packages and post the versions here.

**Comment by karlbom** [comment]
@tylerbutler marvellous, thank you!

**Comment by tylerbutler** [comment]
@karlbom packages `>=0.40.0-25719` should include the fix. Sorry for the delay on the publishing.

**Pull request closed without merging**
