### PR TITLE
[main > 0.33]: Properly differentiate between epoch 409 and coherency 409 (#5028)

### PR DESCRIPTION
**Pull request by jatgarg**

### CODE REVIEW

**Comment by vladsud** [comment]
Do we really need to port it to 0.33? I'd stay with 0.34, unless there is some signal saying we are corrupting documents or something like that and faster fix is warranted. Even small fix has risk once we are past some time...

**Comment by jatgarg** [comment]
> Do we really need to port it to 0.33? I'd stay with 0.34, unless there is some signal saying we are corrupting documents or something like that and faster fix is warranted. Even small fix has risk once we are past some time...

We are not corrupting documents but without this we would wrongly classify epoch errors as coherency 409 errors.

**Comment by jatgarg** [comment]
So I  don't think it poses any risk here.

**Comment by vladsud** [comment]
We are fine waiting for 0.34, we should not add risk (even if it's minimal) and spend time on Bohemia side integrating and testing.

**Comment by jatgarg** [comment]
ok. Sounds good. I will close it then.

**Pull request closed without merging**
