### PR TITLE
Changing SharedCell type to extends Serializable

### PR DESCRIPTION
**Pull request by chensixx**
#2839 

Changed SharedCell type to <T extends Serializable = any>  in both cell.ts and interfaces.ts , which still allows strong typing from customers.
Then changed type of data held by cell from any to T | undefined in cell.ts because data is undefined when initialized or deleted.
Changed set( ) method to take type T for both implementation and interface
Changed get( ) method type to T in the interface

### CODE REVIEW

**Review by ChumpChief — COMMENTED** [review]
Good start!  In addition to the comments, it would be good to update the consumers of cell to use the generic (CollaborativeCheckbox and TodoItem).  Badge won't work since it's actually storing a non-serializable type, so probably ok to skip it for now.

**Review by skylerjokiel — COMMENTED** [review]
Awesome PR! I'm really excited to see this get in. It will help many developers. 😊

**Review by ChumpChief — COMMENTED** [review]
Couple whitespace issues, and then just following the type through `setCore()` and other methods of the cell that are dealing with the stored value.

**Review by ChumpChief — APPROVED** [review]
Looks good!

**Pull request merged**
