### PR TITLE
Enable dts-trimming for packages/common

### PR DESCRIPTION
**Pull request by jikim-msft**
#### Description

Related: [18176](https://github.com/microsoft/FluidFramework/pull/18176/files)

This PR adds type-trimming for `packages/common` directory. The changes introduced are: 
- Add npm `copyfiles` package as `devDependency`
- Add `dtsRollup` in `api-extractor.json`
- Enable both type-trimming for both `ESM` & `CJS`
- Make `fluidBuild` to fetch dependencies from the scripts included in `dependsOn`

### CODE REVIEW

**Comment by tylerbutler** [comment]
What about container-definitions and core-interfaces? Are those going to be done separately?

**Comment by jikim-msft** [comment]
> What about container-definitions and core-interfaces? Are those going to be done separately?

I believe the work on `commons/container-definitions` and `commons/core-interfaces` are already completed from your previous work on the dts-trimming [18176](https://github.com/microsoft/FluidFramework/pull/18176).

`container-definitions/api-extractor.json`: [Main](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/container-definitions/api-extractor.json#L4)
`container-definitions/package.json`: [Main](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/container-definitions/package.json#L20)

`core-interfaces/api-extractor.json`: [Main](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/core-interfaces/api-extractor.json#L12)
`container-definitions/package.json`: [Main](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/core-interfaces/package.json#L20)

I also see the `alpha`, `beta` and `public` `d.ts` files correctly generated in `dist` folder for those packages in the `main` branch.

**Comment by tylerbutler** [comment]
> > What about container-definitions and core-interfaces? Are those going to be done separately?
> 
> I believe the work on `commons/container-definitions` and `commons/core-interfaces` are already completed from your previous work on the dts-trimming [18176](https://github.com/microsoft/FluidFramework/pull/18176).
> 
> `container-definitions/api-extractor.json`: [Link](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/container-definitions/api-extractor.json#L4) `container-definitions/package.json`: [Link](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/container-definitions/package.json#L20)
> 
> `core-interfaces/api-extractor.json`: [Link](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/core-interfaces/api-extractor.json#L12) `container-definitions/package.json`: [Link](https://github.com/microsoft/FluidFramework/blob/fdd751440dfa1159761f1d620b7bbbc49c42d6ac/packages/common/core-interfaces/package.json#L20)
> 
> I also see the `alpha`, `beta` and `public` `d.ts` files correctly generated in `dist` folder for those packages in the `main` branch.

Ha, forgot I did that. Sorry! :)

**Review by tylerbutler — APPROVED** [review]
Looks good!

**Pull request merged**
