### PR TITLE
build: Bump build-tools to 0.26.1 across repo

### PR DESCRIPTION
**Pull request by tylerbutler**
- Bumped build-tools deps across repo to 0.26.1.
- Ran policy-check:fix to do automated fixup in the repo.
- Cleaned up policy handler exclusion settings in fluid-build config.

### CODE REVIEW

**Review by jason-ha — CHANGES_REQUESTED** [review]
0.26.0 is broken for Windows. PR #18000 is required.

**Comment by jason-ha** [comment]
> 

webpack becomes production dependency?

---
Refers to: pnpm-lock.yaml:43105 in 3bba245. [](commit_id = 3bba2455c8f25edcc7a31f195006c5ec0491727e, deletion_comment = True)

**Review by jason-ha — APPROVED** [review]

**Comment by jason-ha** [comment]
> 

Looks like /webpack-cli/4.10.0_ai6cu5vnuisb2akyozxbiaqwvu already was - so not really a notable change

---
In reply to: [1781831132](https://github.com/microsoft/FluidFramework/pull/18005#issuecomment-1781831132) [](http://example.com/codeflow?ancestors=1781831132)

---
Refers to: pnpm-lock.yaml:43105 in 3bba245. [](commit_id = 3bba2455c8f25edcc7a31f195006c5ec0491727e, deletion_comment = True)

**Comment by tylerbutler** [comment]
Thanks for the review, @jason-ha!

**Pull request merged**
