### PR TITLE
fix(fluid-build): Don't find biome config files outside the repo

### PR DESCRIPTION
**Pull request by tylerbutler**
The biome task in fluid-build would find config files outside the repo. This has been fixed by checking the current directory first and returning early if we've already left the repo.

I also corrected the pattern used for resolvedRoot and gitRepo to use Promises.

### CODE REVIEW

**Review by jason-ha — CHANGES_REQUESTED** [review]
The search logic will still find the first files above the repo root.
Tests would be good.
For now, we can just use the updated find-up package: #20296

**Comment by tylerbutler** [comment]
> The search logic will still find the first files above the repo root.

How so? I can't replicate this. The first check in the recursive function is if we're already outside the repo, so the moment we step to the parent folder of the root config, it will return `[]` and stop the loop. In repeated testing, getBiomeConfigPaths has only returned paths within the repo.

I refactored the function to take a stopDir so it doesn't call getResolvedRoot each iteration.

I'm fine with the other approach, I just want to understand the conditions under which this solution fails.

**Comment by tylerbutler** [comment]
> > The search logic will still find the first files above the repo root.
> 
> How so? I can't replicate this. The first check in the recursive function is if we're already outside the repo, so the moment we step to the parent folder of the root config, it will return `[]` and stop the loop. In repeated testing, getBiomeConfigPaths has only returned paths within the repo.
> 
> I refactored the function to take a stopDir so it doesn't call getResolvedRoot each iteration.
> 
> I'm fine with the other approach, I just want to understand the conditions under which this solution fails.

Figured it out. _If_ there is no root biome config -- never the case in our repo -- then it will fail.

**Comment by tylerbutler** [comment]
Closing in favor of https://github.com/microsoft/FluidFramework/pull/20296.

**Pull request closed without merging**
