### PR TITLE
Allow deli to maintain op batches when passing them forward

### PR DESCRIPTION
**Pull request by GaryWilber**
When a client submits an op batch:
1. The frontend (alfred) produces that op batch to the `rawdeltas` kafka topic in a single `Boxcar` message
2. Deli consumes that `Boxcar` and sequences each op
3. Deli produces each sequenced op to the `deltas` topic _separately_
     -  the op batch has now been broken up into 1 `Boxcar` per op!
5. From this point on, the `broadcaster` lambda (redis pubsub), `scribe` (summary handling), and `scriptorium` (op storage) will be consuming each op one by one.

This change allows deli to maintain the op batch when inserting the sequenced ops into the `deltas` topic. So all the sequenced ops will be sent in a single `Boxcar` message. This lets op batches be maintained when being pubsub'd to the clients and when the ops are inserted into storage / persisted.
This functionality can be enabled via the `maintainBatches` deli service configuration option. Defaulting to false, pending some testing.

### CODE REVIEW

**Review by hedasilv — APPROVED** [review]
Is the mapping between boxcar and Kafka message 1:1, meaning each boxcar becomes the content of the message sent to Kafka? If yes, is there any chance that grouping these deltas in the same boxcar would cause the maximum Kafka message size to be exceeded (e.g. that 1 MB limit)? I believe that should not be the case, since because they were originally batched in Alfred/frontend, they would have exceeded the max message size when being inserted into `raw_deltas`. But since there is a bit of overhead added by Deli to each message when sequencing them, I was wondering if there could be any message size issues we need to account for

**Comment by GaryWilber** [comment]
The mapping is 1:1 when the kafka producer maxBatchSize is set to 1.
The alfred producer will be limiting client submitted batches to 900KB. That allows deli to have a headroom of 124kb for the extra size added due to sequencing. That should be enough headroom.
The main thing to keep in mind here is that producer limit. The limit we are setting in alfred must be smaller than the limit we set in the other lambdas.

**Comment by anthony-murphy** [comment]
@GaryWilber  and @hedasilv has this been turned on anywhere? In general i'd like to see us move in this direction. I think it will give better server performance, and should  improve our ability to throttle more sanely, as we can throttle on messages, and not individual ops. This also provides a better computation of the effects of throttling, given the 1mb limt for messages a throttle on message/time === mb/time

**Comment by GaryWilber** [comment]
@anthony-murphy I briefly enabled this in Push but had to disable it. Deli adds extra data to ops when sequencing, so I ran into issues where the kafka message for the rawops batch was below 1MB, but the sequenced op batch ended up over 1MB. 
I don't think we can enable this until the client can support a maximum batch size. For example, I want the server to tell clients to keep batches until some limit, maybe 0.5MB

**Comment by vladsud** [comment]
@GaryWilber, while we are working on chunking (essentially removing 1Mb limit from consumer POV), we can adjust current limit to let this feature ship:
const defaultMaxBatchSizeInBytes = 950 * 1024;

Note that it should not be hard-coded that way, @andre4i has an issue somewhere to accept proper config from front-end.

**Comment by GaryWilber** [comment]
@vladsud I tried something like that and it didn't work. I limited the max batch size in submitOp to 900kb and deli still sometimes processed/created kafka messages over 1MB.

My current theory is that it's caused by us adding the deli checkpoint data to summarize ops, which could greatly increase the kafka message size depending on how many members were in the quorum at the time. #13172 will prevent that for the single commit summary case. 

If we want this without waiting for single commit work to complete, we would need to allow deli to be defensive and split batches when it needs to (in order to not corrupt the doc for cases where it's adding a lot of extra data).

**Comment by vladsud** [comment]
I'm fine either way with direction (wait or not), but I'd say - it would be great to deeper understand the problem. Summarize ops are never sent as part of a batch. And they are small. Maybe we still can get over 1Mb due to checkpoint data alone, but that feels a bit fishy (and potentially suggests that even if we do all the work on the client to be good citizens around ~1Mb limits, the issue is not fully solves).

**Pull request merged**
