### PR TITLE
perf: Optimizing Performance and Resource Utilization with Concurrent Execution in `Promise.all` ✈

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Hi,

This PR introduces a minor performance and hardware resource utilization gain by running the function in `Promise.all` concurrently.

Sorry, if I made any mistakes :(

### CODE REVIEW

**Comment by sanjaiyan-dev** [comment]
👀

**Comment by tylerbutler** [comment]
@sanjaiyan-dev Thanks for this PR! @Josmithr Any concerns with fully parallelizing these calls?

**Comment by sanjaiyan-dev** [comment]
> @sanjaiyan-dev Thanks for this PR! @Josmithr Any concerns with fully parallelizing these calls?

You're welcome @tylerbutler ✨

**Review by Josmithr — APPROVED** [review]
Looks good to me! Thanks!

**Comment by sanjaiyan-dev** [comment]
> Looks good to me! Thanks!

Welcome 💫

**Comment by tylerbutler** [comment]
It looks like the file was deleted as part of a refactor in https://github.com/microsoft/FluidFramework/pull/18873, so no longer a need to merge this. Thank you for submitting the change!

**Pull request closed without merging**
