### PR TITLE
Removed externalRequest header and its handling

### PR DESCRIPTION
**Pull request by agarwal-navin**
The externalRequest header was added for the following scenario:
When a data store in an app (appA) was shared to an external app (appB) via its URL, appB would get the container and load the data store. Now, if the component was deleted from the appA, it may still exist in appB because there it may not know about the removal. It depends on the application's delete implementation.

We added the "externalRequest" header that as a means to solve this problem. appB would set it to true when requesting the data store. Since GC would mark the table as unreferenced, it would return a 404 when "externalRequest" was true and the data store won't load in teams.

However, this feature was never used and it doesn't work very well because the unreferenced state is only up-to-date in the summarizer client. Other clients would only get this information from the snapshot they loaded from. Removing this feature since its unused and doesn't work very well.

[AB#3249](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/3249)

### CODE REVIEW

**Comment by vladsud** [comment]
@agarwal-navin, can you please provide a bit info on how Loop handles external requests (without relying on feature like this)? I.e.  do they go on same path as internal requests? Will it cause GC telemetry errors (that we could mistake with bugs in GC) if requests are for nodes that were deleted?

**Comment by agarwal-navin** [comment]
> @agarwal-navin, can you please provide a bit info on how Loop handles external requests (without relying on feature like this)? I.e. do they go on same path as internal requests? Will it cause GC telemetry errors (that we could mistake with bugs in GC) if requests are for nodes that were deleted?

Note that this does not handle cases where the node is deleted by GC. In those cases, the data store context will not even exist and it will go down a different path.
This was added to fail request for nodes that are unreferenced from runtime (GC) point to view. Loop does not use external requests. They went with always loading the canvas in external apps as well. The canvas can detect when a component (say table) is deleted and remove it from the canvas. Basically, the flow is similar to how it would work on two loop documents.

**Comment by agarwal-navin** [comment]
Adding @leeviana here to confirm. @leeviana can you please take a look at this PR and confirm my understanding that this is not used.

**Comment by leeviana** [comment]
> @agarwal-navin, can you please provide a bit info on how Loop handles external requests (without relying on feature like this)? I.e. do they go on same path as internal requests? Will it cause GC telemetry errors (that we could mistake with bugs in GC) if requests are for nodes that were deleted?

Today the FF design is that all requests (internal and external) are handled by a registered load handler in the runtime. Soon this will not be the case. Internal requests will be routed through logic that predominately uses typed handle APIs instead of request patterns and external requests will go through the "entrypoint" that the Container object exposes. We have made significant progress on our side to enable and migrate to these two flows and now we need to capture any remaining usages of old load logic before deleting the shared load handler logic.

To this end, our first step here and the usage of this flag is simply so that we can differentiate external requests from internal requests (internal requests should not go through any request sort of API) so that we can collect data and eventually turn off any sort of load handler capability for internal requests (and devs will stop writing code against deprecated flows because "they still work").

**Review by vladsud — APPROVED** [review]

**Pull request merged**
