### PR TITLE
Move MountableView and remove view-adapters package

### PR DESCRIPTION
**Pull request by ChumpChief**
After a series of removals, the view-adapters package has become somewhat uninteresting as it no longer has fluid-specific behaviors (i.e. IFluidHTMLView used to be one of the strong motivators).  This change merges the MountableView into example-utils such that it's no longer published.

The remaining usefulness of MountableView is to permit mounting a React view cross-bundle (by bundling ReactDOM along with), which customers can/should do themselves if desired.  Note that the container-views pattern is not really recommended at this point though, so even this is probably not a great thing for customers to do.

view-interfaces should follow, though will require a bit more work to rearrange layering since webpack-fluid-loader depends upon it (and currently that package doesn't import cleanly).

[AB#7210](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/7210)

### CODE REVIEW

**Comment by RishhiB** [comment]
Should we tell users to move usages of IFluidMountableViewEntryPoint and MountableView, to "@fluid-example/example-utils"?

**Review by Josmithr — APPROVED** [review]
🥳

**Comment by Josmithr** [comment]
> Should we tell users to move usages of IFluidMountableViewEntryPoint and MountableView, to "@fluid-example/example-utils"?

We're not recommending customers continue to use them at all (see the changeset entry). But maybe we do want to also note in the changeset that anyone interested in the patterns can now find them in example-utils to use as reference?

**Comment by ChumpChief** [comment]
> > Should we tell users to move usages of IFluidMountableViewEntryPoint and MountableView, to "@fluid-example/example-utils"?
> 
> We're not recommending customers continue to use them at all (see the changeset entry). But maybe we do want to also note in the changeset that anyone interested in the patterns can now find them in example-utils to use as reference?

Yeah I can add that to the changeset.  Note that in this PR it's only MountableView moving, IFluidMountableViewEntryPoint is already in example-utils.

**Pull request merged**
