### PR TITLE
Bump packages that will be released in release/0.58.0 again to account for adjusted versioning scheme

### PR DESCRIPTION
**Pull request by heliocliu**
See #9428 for matching change.

To address the ambiguity with something like `0.58.1` in the new versioning scheme, we are moving to 1 indexing for minor releases to retain 4 significant digits because padding 0s are invalid.  E.g. `0.58.1000` will be the first minor release instead of `0.58.0`.  `main` needs to be bumped to `0.58.2000` as a result.

### CODE REVIEW

**Review by ChumpChief — APPROVED** [review]
Looks like protocol-definitions just needs another install/build to get the type tests working again (already broken in main).

**Review by ssimic2 — APPROVED** [review]

**Comment by markfields** [comment]
> Looks like protocol-definitions just needs another install/build to get the type tests working again (already broken in main).

@ChumpChief - One of my goals for my OCE shift is to figure out where in the bump/release process these breaks are introduced, so we can update the instructions to include the install/build loop so we don't get broken commits in main.

Is [this](https://github.com/microsoft/FluidFramework/pull/9428/files#diff-5ac494b233895dbeb770123ccd773d793f0515f77cd6bc505dea2ffad9b793ba) the change that should have had a corresponding local install/build in order to get the new type validator goo for (now old) version 0.1027.0?

**Comment by heliocliu** [comment]
> > Looks like protocol-definitions just needs another install/build to get the type tests working again (already broken in main).
> 
> @ChumpChief - One of my goals for my OCE shift is to figure out where in the bump/release process these breaks are introduced, so we can update the instructions to include the install/build loop so we don't get broken commits in main.
> 
> Is [this](https://github.com/microsoft/FluidFramework/pull/9428/files#diff-5ac494b233895dbeb770123ccd773d793f0515f77cd6bc505dea2ffad9b793ba) the change that should have had a corresponding local install/build in order to get the new type validator goo for (now old) version 0.1027.0?

Looking at the history, it broke in main but the "breaking change" was completely unrelated.  I'm guessing what happened was that it broke when we did the release for protocol-definitions yesterday then paused the release process.  Usually the next step would catch that and force the install, so the window during which it's broken is very small.  I think the real issue is probably that there is behavior here that is dependent on available published packages rather than repo state.

**Comment by ChumpChief** [comment]
> I'm guessing what happened was that it broke when we did the release for protocol-definitions yesterday then paused the release process. Usually the next step would catch that and force the install, so the window during which it's broken is very small. I think the real issue is probably that there is behavior here that is dependent on available published packages rather than repo state. Though this wouldn't be a lasting issue so I don't think it's worth the effort to fix.

This is my understanding as well, that main will automatically break (for some duration) every time we release a package which does type tests.  I think this should change (IMO main should never be by-design broken for any duration) though I don't have a concrete proposal of any sort.

**Pull request merged**
