### PR TITLE
Run full tree on 2nd attempt

### PR DESCRIPTION
**Pull request by tyler-cai-microsoft**
[AB#3895](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/3895)

Run full tree on second summarization attempt if the first one fails

- The summarizer receives an ack of a summary from another summarizer
- load from cache - load from an older summary - and get your ack but later summarize twice and hit f5 - get ack 100 and get ack 200 after loading from 100.
- Summary attempt fails (nack, summarize fails, ack timeout, etc.)

### CODE REVIEW

**Comment by agarwal-navin** [comment]
> [AB#3895](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/3895)
> 
> Run full tree on second summarization attempt if the first one fails

Can you add details on what the motivation behind this is. It's hard to tell if this change does what it's supposed to do otherwise.

**Review by NicholasCouri — COMMENTED** [review]
why are you using the summarizeRecoveryMethodKey as a string ? shouldn't it be a boolean and we simply do fullTreeAttempt = this.mc.config.getBoolean() ?? false'; ?

**Comment by NicholasCouri** [comment]
Makes sense! perhaps adding some comments would be helpful.  Can you remind me if we log this FG in teh telemetry events ?
________________________________

**Comment by agarwal-navin** [comment]
> [AB#3895](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/3895)
> 
> Run full tree on second summarization attempt if the first one fails
> 
> The motivation is so that in case the failure of a summary is due to a reference to a previous summary, then we should resubmit the whole summary tree.

Couple of questions:
1. Just doing a `fullTree` in the second attempt isn't enough. The refresh from snapshot function should not be called anymore on summarizer node + GC + any other layers that do incremental summary. That's the core of the problem. While its fine to do that, it's unncessary and expensive work which should be avoided.
2. What about the other case where an ack is received for a summary not generated by a summarizer. Will that be done in a separate PR?

**Comment by agarwal-navin** [comment]
From the ADO item linked in the description:
The summarizer should do a full tree summarization in these cases
- The summarizer receives an ack of a summary from another summarizer
- load from cache - load from an older summary - and get your ack but later summarize twice and hit f5 - get ack 100 and get ack 200 after loading from 100.
- Summary attempt fails (nack, summarize fails, ack timeout, etc.)

**Comment by vladsud** [comment]
@tyler-cai-microsoft, I'm a bit at a loss on what you are trying to achieve here.
What data do we have that this approach addresses a problem (and what is a problem)?

In the past, we talked about full summary, but I thought about it in context of either alternative solution to summarizer client reload (if we have new parent summary handle from previous failed attempt), or possibly - as recovery path for whole client reload (if we detect that whole client reload did run into the same problem). But in both cases - getting rid of refresh flow.

This PR relies on refresh flow, so I'm not sure what problem it addresses.

**Comment by tyler-cai-microsoft** [comment]
Closing as this is relatively expensive

**Pull request closed without merging**
