### PR TITLE
Use service objects in getContainer and FluidStatic

### LINKED ISSUE #5148: getRouterliciousContainer can't be imported from @fluidframework/get-tinylicious-container
## Describe the bug

A `getRouterliciousContainer` function is defined in the the [experimental package](https://github1s.com/microsoft/FluidFramework/blob/main/experimental/framework/get-container/src/getRouterliciousContainer.ts), but the contents of the file is not exported in the index.ts file. Is this method intended to not be publicly available yet or should it be exported?

### To Reproduce
1. install `@fluidframework/get-tinylicious-container`
2. Add `import { getRouterliciousContainer } from '@fluidframework/get-tinylicious-container'` to top of the file;
3. See logs showing getRouterliciousContainer is not defined.

### Expected behavior

The function should be available when imported.

### PR DESCRIPTION
**Pull request by ChumpChief**
This change adds a service parameter to `FluidStatic` methods and `getContainer` and exports experimental service objects to be used.

There are still issues to work through (particularly around the `urlResolver` and correct calling of `container.attach()` with service-appropriate create-new requests) but this is a start.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
How do you envision this looking in production? Does the user need to switch between container services manually? Are we thinking of some abstraction that does that for them? Does this leave room for custom services, or is that even necessary?

**Comment by ChumpChief** [comment]
> How do you envision this looking in production? Does the user need to switch between container services manually? Are we thinking of some abstraction that does that for them? Does this leave room for custom services, or is that even necessary?

I haven't really gotten to that point yet :)  This enables them switching manually with relative ease, though I think ideally we'd like to make it more automatic.

**Comment by micahgodbolt** [comment]
Yeah, no worries. As long as we aren't painting ourselves into any corners I certainly approve of this change :D

**Review by micahgodbolt — APPROVED** [review]

**Comment by Flavyoo** [comment]
Just curious, does this restructure allow developers to query any fluid service endpoint on the internet for a container directly? I'm testing out fluid with an app, and notice I can do this with `getTinilyciousContainer` locally, but when it comes to deploying the app, I can't use that since the service is not running locally but on a different server.

I opened #5148 because I was trying to get this use case working for Routerlicious, but the function was not exported.

@ChumpChief Let me know your thoughts or if I should open up a feature request issue? I'm open to taking it up also.

**Comment by ChumpChief** [comment]
@Flavyoo yes, with this change you can use the `RouterliciousService` in combination with `getContainer` to target a Fluid service endpoint of your choice.

**Pull request merged**
