### PR TITLE
Update client deps

### PR DESCRIPTION
**Pull request by CraigMacomber**
## Description

Update client dependencies, holding back socket.io-client to avoid https://github.com/socketio/socket.io/issues/5202.

Makes type tests target ~ version, to avoid duplicating previous package versions:
`pnpm exec flub typetests -g client --exact "~2.3.0"`

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

### CODE REVIEW

**Review by Abe27342 — COMMENTED** [review]
looks mostly good, but there are a number of FF packages in pnpm-lock on version 2.3.0 as well as 2.3.1 (@fluidframework/tree is one such package). Even with pnpm's dep tree structure, seems like that could cause some strange issues.

**Review by tylerbutler — APPROVED** [review]
Thanks for doing this! It would be nice to also update the package.json files eventually too, but not critical. Maybe we need to consider some per-release maintenance tasks that we do regularly.

**Comment by CraigMacomber** [comment]
> Thanks for doing this! It would be nice to also update the package.json files eventually too, but not critical. Maybe we need to consider some per-release maintenance tasks that we do regularly.

Updating the minimum supported version in our package.json files to remove support for older versions of packages seems like it could be a breaking change for prod deps in some cases, so in general I think we should probably leave them alone. Updating them for dev deps would be ok though.

**Comment by tylerbutler** [comment]
> looks mostly good, but there are a number of FF packages in pnpm-lock on version 2.3.0 as well as 2.3.1 (@fluidframework/tree is one such package). Even with pnpm's dep tree structure, seems like that could cause some strange issues.

@CraigMacomber `flub modify lockfile` that @alexvy86 wrote might be useful: https://github.com/microsoft/FluidFramework/blob/main/build-tools/packages/build-cli/docs/modify.md#flub-modify-lockfile

**Comment by CraigMacomber** [comment]
> looks mostly good, but there are a number of FF packages in pnpm-lock on version 2.3.0 as well as 2.3.1 (@fluidframework/tree is one such package). Even with pnpm's dep tree structure, seems like that could cause some strange issues.

I think this is expected? Our type tests test against the previous minor's .0 release, and those will pull in patched versions of their deps when updating, resulting in this duplication for all packages which have type tests and are also depended on by a package with type tests, and have been patched. If we don't want this behavior, our type tests should probably use ~ versions.

**Comment by CraigMacomber** [comment]
I went ahead and made the type tests target ~ versions to avoid the duplication since it was easy. If we like that we can update our type test tooling to prefer that format by default when updating their package versions.

**Pull request merged**
