### PR TITLE
Move from axios to node fetch for odsp-doclib-utils

### PR DESCRIPTION
**Pull request by jatgarg**

### CODE REVIEW

**Comment by curtisman** [comment]
What testing have you done?

**Comment by jatgarg** [comment]
> What testing have you done?

Used fetch tool, fetching new tokens and ran webpack-fluid-loader with a data-store.

**Review by curtisman — APPROVED** [review]
:shipit:

**Comment by curtisman** [comment]
you mean targeting spo, right?

---
In reply to: [709686526](https://github.com/microsoft/FluidFramework/pull/3955#issuecomment-709686526) [](ancestors = 709686526)

**Comment by jatgarg** [comment]
> you mean targeting spo, right?
> 
> In reply to: [709686526](https://github.com/microsoft/FluidFramework/pull/3955#issuecomment-709686526) [](ancestors = 709686526)

Yes :)

**Pull request merged**
