### PR TITLE
Prevent deli from sending summary throttling nacks mid batch

### PR DESCRIPTION
**Pull request by GaryWilber**
Deli should not nack about summary throttle issues while in the middle of processing a batch. It will now check the summary throttling state after processing the batch.

### CODE REVIEW

**Comment by vladsud** [comment]
> It will now check the summary throttling state after processing the batch.

I'd say "before" would be better, as it will ensure that clients can't avoid throttling policies.
That said, currently we rely on client doing right things (i.e. respecting throttling nack and changing it's behavior),  I assume without any strong enforcement on service, so maybe having it after is totally fine.

**Review by vladsud — APPROVED** [review]

**Comment by GaryWilber** [comment]
It would be hard to run it beforehand since that would require deli to 'preprocess' the batch to determine how much the sequence number would be incremented. The deli ticket logic is complex.

This change stays in line with how it was already working (checking for throttling after sequencing) so I would rather stick with this for now

**Comment by vladsud** [comment]
> It would be hard to run it beforehand since that would require deli to 'preprocess' the batch to determine how much the sequence number would be incremented. The deli ticket logic is complex.
> 
> This change stays in line with how it was already working (checking for throttling after sequencing) so I would rather stick with this for now

Sounds good!

**Review by NicholasCouri — APPROVED** [review]
:shipit:

**Review by hedasilv — APPROVED** [review]

**Pull request merged**
