### PR TITLE
1892 fluid-runner CSV telemetry (#12015)

### PR DESCRIPTION
**Pull request by kian-thompson**
[AB#1892](https://dev.azure.com/fluidframework/internal/_workitems/edit/1892)

Needed to unblock OASYS for the eDiscovery work

- Add support for choosing to export telemetry as a CSV
- Add support for adding additional properties to every telemetry entry

### CODE REVIEW

**Comment by tyler-cai-microsoft** [comment]
main PR: https://github.com/microsoft/FluidFramework/pull/12015

**Review by tyler-cai-microsoft — APPROVED** [review]
LGTM

**Comment by tyler-cai-microsoft** [comment]
We need to port this fix in as well https://github.com/microsoft/FluidFramework/pull/12205

**Comment by agarwal-navin** [comment]
Closing in favor of https://github.com/microsoft/FluidFramework/pull/12249.

**Pull request closed without merging**
