### PR TITLE
build: Remove / update .editorconfig files to accommodate prettier / tsdoc

### PR DESCRIPTION
**Pull request by Josmithr**
The recent prettier changes updated our formatting defaults (everywhere except for `server`, for now) to use tabs instead of spaces. While our vscode settings were updated to reflect this change, our `.editorconfig` files were not.

Additionally, removes settings around c-style comment blocks, as we use jsdoc/tsdoc comment syntax.

This PR removes the `.editorconfig` files from areas of the codebase that are now using prettier for formatting, and updates the remainder to remove tsdoc-incompatible rules.

### CODE REVIEW

**Review by noencke — DISMISSED** [review]

**Review by noencke — COMMENTED** [review]
There are a whole bunch more `.editorconfig` files all over the place in the repo. All the ones that I've checked are only configuring whitespace. Should all of those be removed too (not including the ones in Non-Pretty Zones, like `server/`)?

**Comment by Josmithr** [comment]
> There are a whole bunch more `.editorconfig` files all over the place in the repo. All the ones that I've checked are only configuring whitespace. Should all of those be removed too (not including the ones in Non-Pretty Zones, like `server/`)?

Oof, I missed all of the per-package ones. I'll remove the ones outside of server.

**Review by noencke — APPROVED** [review]

**Review by tylerbutler — APPROVED** [review]
Did this really not require any source code formatting changes?

**Comment by Josmithr** [comment]
> Did this really not require any source code formatting changes?

Can you elaborate on what changes you are expecting? AFAIK this shouldn't result in source-code changes, since these configs strictly affect the live editing behavior, not the end-formatting of the code.

**Comment by tylerbutler** [comment]
> > Did this really not require any source code formatting changes?
> 
> Can you elaborate on what changes you are expecting? AFAIK this shouldn't result in source-code changes, since these configs strictly affect the live editing behavior, not the end-formatting of the code.

Prettier [loads some settings from .editorconfig if present](https://prettier.io/docs/en/configuration.html#editorconfig), so I assumed that some of those would change. If not, great.

**Comment by Josmithr** [comment]
> > > Did this really not require any source code formatting changes?
> > 
> > 
> > Can you elaborate on what changes you are expecting? AFAIK this shouldn't result in source-code changes, since these configs strictly affect the live editing behavior, not the end-formatting of the code.
> 
> Prettier [loads some settings from .editorconfig if present](https://prettier.io/docs/en/configuration.html#editorconfig), so I assumed that some of those would change. If not, great.

Ah, okay. I wasn't aware of that. I'll do a format run as a sanity check before merging then.

**Pull request merged**
