### PR TITLE
Remove branch forking from server side and routes

### PR DESCRIPTION
**Pull request by ChumpChief**
In #4313, support for handling branches was removed from client and server.  This change removes the server-side capability to create new branches.

### CODE REVIEW

**Comment by tanviraumi** [comment]
Are you running this locally using docker? I don't see the changes in the docker-compose file inside server/routerlicious. You may encounter an error because the routemanager service will try to run without the code. In addition, you will also need to delete the routemanager references from helm charts (server/routerlicious/kubernetes/routerlicious). Basically just delete any place where routermanager is referenced.

The change heavily impacts deli so I would also recommend to verify with a component using npm run start:docker

**Review by tanviraumi — COMMENTED** [review]
Are you running this locally using docker? I don't see the changes in the docker-compose file inside server/routerlicious. You may encounter an error because the routemanager service will try to run without the code. In addition, you will also need to delete the routemanager references from helm charts (server/routerlicious/kubernetes/routerlicious). Basically just delete any place where routermanager is referenced.

The change heavily impacts deli so I would also recommend to verify with a component using npm run start:docker

**Comment by ChumpChief** [comment]
Updated the configs in latest.  There seems to be some issue running r11s with `npm run start` in `main` right now, but confirmed `docker-compose -f docker-compose.yml up` works and ran the diceroller on it with `npm run start:docker`.

**Comment by tanviraumi** [comment]
Whats the issue in running "npm run start"? It uses the docker-compose.dev file which volume mounts your local directory to docker. Running docker-compose -f docker-compose.yml up will only run images so your local changes are probably not reflected there.

**Comment by ChumpChief** [comment]
Got `npm run start` working by disabling wsl2 in Docker (and using Hyper-V option instead).  Ran without issues then, as well as the diceroller component using `npm run start:docker`

**Review by tanviraumi — APPROVED** [review]

**Pull request merged**
