### PR TITLE
[0.26 Port] Don't rely on webpack polyfilling path 

### PR DESCRIPTION
**Pull request by christiango**
Cherry pick of #3719

### CODE REVIEW

**Comment by tylerbutler** [comment]
We usually make changes in the release branch and port forward rather than backporting - but we neglected to ask "does this need to be backported?" in the code review for the original change. We should have. Lessons for the future.

**Comment by christiango** [comment]
> We usually make changes in the release branch and port forward rather than backporting - but we neglected to ask "does this need to be backported?" in the code review for the original change. We should have. Lessons for the future.

I hadn't realized we already cut 0.27, so in my mental model I was ok with it coming in 0.27. Since I already backported to 0.27, I figured I'd do 0.26 as well.  But yeah, lessons for next time.

**Comment by tylerbutler** [comment]
@christiango No worries - we're all still figuring all this out. :)

**Review by tylerbutler — APPROVED** [review]
Looks good.

**Pull request merged**
