### PR TITLE
Add Checkout overloads which accept an array of changes

### PR DESCRIPTION
**Pull request by MillerJames**
## Description

Add overloads to Checkout methods so callers can pass an array directly, if they already have one. Also add a helper to conditionally unwrap these parameters and use that helper in some other functions with a similar signature.

Callers of these Checkout methods often already have arrays of Changes. Previously, the caller would spread the array at the call site and the runtime would re-collect the values into a new array for the rest parameter. The new approach still requires some logic to conditionally unwrap the rest parameter, but avoids copying the array multiple times.

## Reviewer Guidance

The most common uses I'm aware of generally pass small arrays (less than 5 elements), but I'm aware of at least one usage in Whiteboard that could potentially pass a very large array. Avoiding the spread operation would be significant in that case. I'm interested to hear thoughts from people more familiar with the common/recommended usage patterns, though.

### CODE REVIEW

**Comment by MillerJames** [comment]
@noencke @taylorsw04 adding both of you, since we discussed this offline a bit. Interested in hearing your thoughts.

**Comment by CraigMacomber** [comment]
A few things to watch our for:
- types which are arrays (I see you documented this issue, already: good)
- places where removing the copy could be an issue due to aliasing

It's this second one we have to be careful with: spread always copies, so the caller gets to keep ownership, and the callee also gets ownership. When adding your non-copying overloads, we need to be explicit about ownership and the potential for future mutations.

If ownership is being transferred to the callee, we should document that the caller should not modify the array after providing it. Sadly the type system can no model this.

If the caller maintains ownership, we need to make sure the callee is not incorrect with this copy removed (ex: that it does not actually need a defensive copy to allow it to modify the array or incase the caller modifies it). We can cover half of this (make sure the callee does not modify it) using read-only on the array (which it looks like you didn't do), however we still need to ensure that if the caller modifies the array after passing it, that things work correctly, or that we document that they must not do so.

**Comment by MillerJames** [comment]
@CraigMacomber The current implementations of the functions I've modified use the provided arrays synchronously and do not store them, so I've updated docs/types to indicate that the caller retains ownership.

**Review by CraigMacomber — APPROVED** [review]

**Comment by CraigMacomber** [comment]
> @CraigMacomber The functions I've modified use the provided arrays synchronously and do not store them, so I've updated docs/types to indicate that the caller retains ownership.

I see they all go through internalizeChange which forces a copy: that does make this seem quite safe!

**Pull request merged**
