### PR TITLE
Introduce a data-objects package into experimental namespace

### PR DESCRIPTION
**Pull request by micahgodbolt**
This package will export custom data-objects like our key-value pair and other future objects. Right now kvpair is simply part of this package, but we could consider breaking them up in the future.

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@chumpchief maybe i should remove FluidStatic from this PR. it depends on get-tinylicious-container, which makes layercheck complicated.

**Comment by SamBroner** [comment]
Interesting w.r.t. get-tinylicious-container. Could you help me understand the issue with layercheck?

**Review by SamBroner — APPROVED** [review]
Great

**Comment by micahgodbolt** [comment]
layercheck isn't expecting to find tinylicious in the framework as a dependency, only a dev-dependency. So either we have to move this AND the top level export out of 'framework' or we need to omit any dependencies on server code

**Pull request merged**
