### PR TITLE
r11s-driver: reduce API export surface

### PR DESCRIPTION
**Pull request by znewton**
## Description

No external consumers of R11s driver should rely on internals like DocumentService or DocumentDeltaStorage. All entry should be through DocumentServiceFactory. There are a few extra exports like DefaultTokenProvider and token types that are necessary for consumers.

Unfortunately, DocumentStorageService is shared with local-driver so ~~it cannot be hidden. It doesn't seem (at a glance) easy to make a "simplified" LocalDocumentStorageService class, so leaving it in the r11s-driver exports for now.~~ I've implemented a simplified LocalDocumentStorageService class within `local-driver` that is very reminiscent of the r11s-driver DocumentStorageService from 2020.

This should help reduce the need to add a hodge-podge of optional params in internal driver classes for the sake of backwards compatibility.

## Does this introduce a breaking change?

Removes export of some internal class declarations.

### CODE REVIEW

**Review by jatgarg — APPROVED** [review]

**Comment by znewton** [comment]
@jatgarg it's hard to say with certainty. We used to use DocumentStorageService internally in an FRS client project for devops, but I can't think of a reason that these internals would be needed outside of the DocumentServiceFactory flow.

I'm also not really up-to-date on the next vs main branch usage. It would probably be ideal to remove these as part of the 2.0 release if that's what `next` is for

**Comment by jatgarg** [comment]
Generally any breaking change should go in next branch instead of main. Like removing of exported files. So lets make this change in next.

**Comment by znewton** [comment]
@jatgarg I added a LocalDocumentStorageService class to local-driver to further reduce the exported API surface. Let me know if you still approve, thanks

**Comment by jatgarg** [comment]
> @jatgarg I added a LocalDocumentStorageService class to local-driver to further reduce the exported API surface. Let me know if you still approve, thanks

I think you should raise this PR against next branch and close this PR.

**Comment by znewton** [comment]
Closing in favor of #11756 into next

**Pull request closed without merging**
