### PR TITLE
Fix lint error

### LINKED ISSUE #9072: Lint errors in connectionManager.spec.ts
CI loop is failing with the following lint errors. Looks like these tests were added in https://github.com/microsoft/FluidFramework/pull/8964.

@fluidframework/container-loader: /mnt/vss/_work/1/s/packages/loader/container-loader/src/test/connectionManager.spec.ts
@fluidframework/container-loader:    72:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:    74:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:    86:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:    90:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:   100:15  error  Multiple spaces found before '('  no-multi-spaces
@fluidframework/container-loader:   104:15  error  Multiple spaces found before '('  no-multi-spaces

### PR DESCRIPTION
**Pull request by markfields**
Fixes #9072

### CODE REVIEW

**Review by tylerbutler — APPROVED** [review]

**Review by agarwal-navin — APPROVED** [review]

**Review by andre4i — COMMENTED** [review]
Lines 72 and 74 also need to be fixed

**Comment by tylerbutler** [comment]
`npm run lint:fix` in the project folder should take care of it.

**Comment by markfields** [comment]
I made this branch in GitHub web UX, I can't connect to my dev box right now and don't trust my laptop at the moment.

**Comment by markfields** [comment]
Repo Policy Check error looks strange:

```
##[error]No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```

I'm going to force merge this one.  Not going to make anything worse, we can't have build errors in main.

**Pull request merged**
