### PR TITLE
feat(merge-tree): register benchmarks in perf pipeline

### PR DESCRIPTION
**Pull request by connorskees**
Adds the `test:benchmark:report` command to the merge-tree package, which should register the package's benchmarks in the performance pipeline. This will allow us to track performance over time (and I believe on every commit). 

Relevant docs for the performance pipeline can be found here: https://eng.ms/docs/experiences-devices/opg/office-shared/fluid-framework/fluid-framework-internal/fluid-framework/docs/infrastructure/ado/pipelines/perf-tests

### CODE REVIEW

**Review by alexvy86 — COMMENTED** [review]
A few things:
- We'll also need to add the merge-tree package to a hardcoded parameter in the pipeline, [here](https://github.com/microsoft/FluidFramework/blob/main/tools/pipelines/test-perf-benchmarks.yml#L27-L38).
- The `postpack` script in merge-tree will need changes, it needs to pack scr/test and dist/test (see the example for @fluidframework/map linked in [the docs](https://eng.ms/docs/experiences-devices/opg/office-shared/fluid-framework/fluid-framework-internal/fluid-framework/docs/infrastructure/ado/pipelines/perf-tests#adding-new-performance-tests)).
  - I think there's a decent chance that the currently generated tar file is not used anywhere (AFAIK only the azure packages were doing something with their test file tar files), so changing the structure of its contents shouldn't impact anything else. Would be nice to do some exploration to try to confirm that.
- The mocha invocation should also have `-r @fluidframework/mocha-test-setup` so all our standard hooks and config for running tests are in effect.

**Comment by connorskees** [comment]
> The mocha invocation should also have -r @fluidframework/mocha-test-setup

The script currently has `-r node_modules/@fluidframework/mocha-test-setup`, which is borrowed from the equivalent script in experimental tree. I've tested this locally and it works, but will this differ meaningfully from `-r @fluidframework/mocha-test-setup`?

**Comment by alexvy86** [comment]
> The script currently has `-r node_modules/@fluidframework/mocha-test-setup`, which is borrowed from the equivalent script in experimental tree. I've tested this locally and it works, but will this differ meaningfully from `-r @fluidframework/mocha-test-setup`?

It used to matter when we were subject to Lerna's dependency hoisting (mocha and other packages ended up existing in the root `node_modules/` but not the `node_modules/` of the package that declared the dependency, but that wasn't necessarily true for the packages in the dynamic requires, so depending on where were running the tests and how we specified the dynamic require, and if other packages were using it, things sometimes worked and sometimes didn't). I think now with pnpm it shouldn't matter, but can you try without the `node_modules/`? I think it's preferable to just specify the package name and let node resolve it.

**Comment by connorskees** [comment]
> can you try without the `node_modules/`

Seems to work the same locally

**Comment by Abe27342** [comment]
> A few things:
> 
> * We'll also need to add the merge-tree package to a hardcoded parameter in the pipeline, [here](https://github.com/microsoft/FluidFramework/blob/main/tools/pipelines/test-perf-benchmarks.yml#L27-L38).
> * The `postpack` script in merge-tree will need changes, it needs to pack scr/test and dist/test (see the example for @fluidframework/map linked in [the docs](https://eng.ms/docs/experiences-devices/opg/office-shared/fluid-framework/fluid-framework-internal/fluid-framework/docs/infrastructure/ado/pipelines/perf-tests#adding-new-performance-tests)).
>   
>   * I think there's a decent chance that the currently generated tar file is not used anywhere (AFAIK only the azure packages were doing something with their test file tar files), so changing the structure of its contents shouldn't impact anything else. Would be nice to do some exploration to try to confirm that.
> * The mocha invocation should also have `-r @fluidframework/mocha-test-setup` so all our standard hooks and config for running tests are in effect.

FYI the existing .tar file is used in the DDS stress pipeline (shares a lot of the run details with real service e2e test pipeline). But the format of the artifact isn't super opinionated--I see other packages which published tar files were already converted to the form the perf pipeline expects (ex: @fluidframework/sequence and @fluid-experimental/tree) and those appear to run fine, see [here](https://dev.azure.com/fluidframework/internal/_build/results?buildId=133416&view=results). So sounds good to me to standardize.

unrelated, but seems like dds stress pipeline may have an install race condition. i'll file a bug to keep an eye on that for the next couple sequence/merge-tree changes I make.

**Review by Abe27342 — APPROVED** [review]

**Review by alexvy86 — APPROVED** [review]

**Pull request merged**
