### PR TITLE
IdCompressor bundle size mitigation

### PR DESCRIPTION
**Pull request by justus-camp**
## Description

Moving the IdCompressor into the runtime (#14340 ) has resulted in a large bundle size increase that we don't want consumers to take on while the compressor isn't being used anywhere. By changing to dynamic imports, only consumers who enable the compressor will have to pay download cost.

### CODE REVIEW

**Comment by taylorsw04** [comment]
> Have we considered switching to a vanilla `Map` from the btree library? I assume that eventually we'll want to make turning this feature on the norm, in which case this is just deferring the problem to a future date. Even if we go with this approach to unblock minor release I think that needs investigating.

Unfortunately, we need the ability to do efficient range queries (to solve the predecessor problem) in addition to using it as a map. It's also used elsewhere (legacy SharedTree and the new SharedTree). We could explore alternative sorted collections that support these operations, but this package has zero dependencies and is pretty ruthlessly minimized.

**Comment by anthony-murphy** [comment]
did we consider a more play to play model here rather than embedding in the container runtime itself, something like mixin, or interface injection? i guess if we think every consumer of fluid will want this, then its not a big deal, but it seems like there are non-insignificant costs associated with it, like code size, that a consumer could want control over.

**Comment by justus-camp** [comment]
I think eventually every consumer of fluid will want this and we can justify the bundle size increase when the feature is turned on by default. It's a bit hand-wavy, but anywhere where we are storing/using UUIDs will greatly benefit from the having the compressor available. For a more concrete example (besides SharedTree needing the compressor), the majority of GC data is UUIDs and we can greatly shrink it by having access to this feature. @agarwal-navin might be able to provide more detail for what he has in mind. 

I agree that we need to provide more concrete data before turning it on by default, which we'll be happy to provide/publish before doing so.

**Comment by anthony-murphy** [comment]
> I think eventually every consumer of fluid will want this and we can justify the bundle size increase when the feature is turned on by default. It's a bit hand-wavy, but anywhere where we are storing/using UUIDs will greatly benefit from the having the compressor available. For a more concrete example (besides SharedTree needing the compressor), the majority of GC data is UUIDs and we can greatly shrink it by having access to this feature. @agarwal-navin might be able to provide more detail for what he has in mind.
> 
> I agree that we need to provide more concrete data before turning it on by default, which we'll be happy to provide/publish before doing so.

for something like azure-client which only has a single data store, and a small set of dds, so like 10 guids, i'm not sure i would want the added code size.

**Review by taylorsw04 — APPROVED** [review]

**Pull request merged**
