### PR TITLE
Update deps (minor) on eslint-config-fluid in the azure release group

### PR DESCRIPTION
**Pull request by jikim-msft**
### Description

This PR is one of the 4 PRs to update dependencies on `eslint-config-fluid` in the `Azure` Release group. Unnecessary updates outside of the `Azure` release group have been discarded.

### CODE REVIEW

**Review by tylerbutler — APPROVED** [review]
Looks good!

**Review by tylerbutler — COMMENTED** [review]
Actually, I just noticed that this includes some changes to common packages. If that's what you intend that's ok but if not you might have hit a bug in the bump tool that I recently fixed. I can help more tomorrow. :)

**Comment by jikim-msft** [comment]
> Actually, I just noticed that this includes some changes to common packages. If that's what you intend that's ok but if not you might have hit a bug in the bump tool that I recently fixed. I can help more tomorrow. :)

Thanks for letting me know! I'll ping you tomorrow so that I can take the change in a bump tool in account before merging it in! Thanks again!

**Comment by tylerbutler** [comment]
Remove all the changes outside of the azure release group, and update the PR description to remove everything except the azure release group. Then I can approve.

**Review by tylerbutler — APPROVED** [review]
:shipit: Looks great!

**Pull request merged**
