### PR TITLE
refactor(merge-tree sequence matrix): enable noImplicitAny

### PR DESCRIPTION
**Pull request by connorskees**
Enables noImplicitAny in merge-tree, sequence, and matrix.

Note that it explicitly disables it for test code, though this is not necessary. The type-tests seem to break with this enabled for tests, and I haven't yet investigated why. For now it seems sane to skip the tests.

### CODE REVIEW

**Comment by tylerbutler** [comment]
I love this change! I think you may need to merge the latest main, because the tsconfigs have been changing.

**Comment by tylerbutler** [comment]
> I love this change! I think you may need to merge the latest main, because the tsconfigs have been changing.

Ahhhh, I see this is targeting next, which makes sense. The PR that changes the tsconfigs is #18152, so if it's possible to wait for that to make it to `next` before you merge, it would save a headache or two.

**Comment by connorskees** [comment]
Of course, just let me know if you notice it's been merged. I'll also keep my eye out.

**Comment by tylerbutler** [comment]
> Of course, just let me know if you notice it's been merged. I'll also keep my eye out.

This is the main-next PR that includes the change: https://github.com/microsoft/FluidFramework/pull/18248

**Review by tylerbutler — APPROVED** [review]

**Pull request merged**
