### PR TITLE
Add SharedTree to bundle-size-tests

### PR DESCRIPTION
**Pull request by Abe27342**
This should give the SharedTree team slightly more visibility on impact of various changes.

### CODE REVIEW

**Comment by Abe27342** [comment]
here's current status:

image

gzipped 62kb vs. SharedString 44kb. not too bad considering larger scope.

**Review by taylorsw04 — APPROVED** [review]

**Comment by tylerbutler** [comment]
> 
> 
> 
> 
> 
> <details><summary><b><span style="color: red">⯅</span> @fluid-example/bundle-size-tests:</b> +239.12 KB</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr>
>     <td>aqueduct.js</td>
>     <td>437 KB</td>
>     <td>437 KB</td>
>     <td><span style="color: coral">⯅</span> +6 Bytes</td>
>   </tr><tr>
>     <td>connectionState.js</td>
>     <td>680 Bytes</td>
>     <td>680 Bytes</td>
>     <td><span style="color: green">■</span> No change</td>
>   </tr><tr>
>     <td>containerRuntime.js</td>
>     <td>229.71 KB</td>
>     <td>229.71 KB</td>
>     <td><span style="color: coral">⯅</span> +2 Bytes</td>
>   </tr><tr>
>     <td>loader.js</td>
>     <td>160.81 KB</td>
>     <td>160.82 KB</td>
>     <td><span style="color: coral">⯅</span> +6 Bytes</td>
>   </tr><tr>
>     <td>map.js</td>
>     <td>44.07 KB</td>
>     <td>44.07 KB</td>
>     <td><span style="color: coral">⯅</span> +2 Bytes</td>
>   </tr><tr>
>     <td>matrix.js</td>
>     <td>137.65 KB</td>
>     <td>137.65 KB</td>
>     <td><span style="color: coral">⯅</span> +2 Bytes</td>
>   </tr><tr>
>     <td>odspDriver.js</td>
>     <td>92.35 KB</td>
>     <td>92.36 KB</td>
>     <td><span style="color: coral">⯅</span> +6 Bytes</td>
>   </tr><tr>
>     <td>odspPrefetchSnapshot.js</td>
>     <td>43.58 KB</td>
>     <td>43.59 KB</td>
>     <td><span style="color: coral">⯅</span> +4 Bytes</td>
>   </tr><tr>
>     <td>sharedString.js</td>
>     <td>158.21 KB</td>
>     <td>158.22 KB</td>
>     <td><span style="color: coral">⯅</span> +2 Bytes</td>
>   </tr><tr>
>     <td>Total Size</td>
>     <td>1.38 MB</td>
>     <td>1.61 MB</td>
>     <td><span style="color: red">⯅</span> +239.12 KB</td>
>   </tr></table></details><hr><p>Baseline commit: 309fe9801f48d9cdec4571c55242c0d529c3109e</p>
> <p align="right">
>   Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9a4a068d7c0f0dc8a8f808cc2aaebfcbe501587
> </p>
> 

Shouldn't tree be a line item here?

**Comment by Abe27342** [comment]
> > ⯅ @fluid-example/bundle-size-tests: +239.12 KBMetric NameBaseline SizeCompare SizeSize Diff
> >     aqueduct.js
> >     437 KB
> >     437 KB
> >     ⯅ +6 Bytes
> >   
> >     connectionState.js
> >     680 Bytes
> >     680 Bytes
> >     ■ No change
> >   
> >     containerRuntime.js
> >     229.71 KB
> >     229.71 KB
> >     ⯅ +2 Bytes
> >   
> >     loader.js
> >     160.81 KB
> >     160.82 KB
> >     ⯅ +6 Bytes
> >   
> >     map.js
> >     44.07 KB
> >     44.07 KB
> >     ⯅ +2 Bytes
> >   
> >     matrix.js
> >     137.65 KB
> >     137.65 KB
> >     ⯅ +2 Bytes
> >   
> >     odspDriver.js
> >     92.35 KB
> >     92.36 KB
> >     ⯅ +6 Bytes
> >   
> >     odspPrefetchSnapshot.js
> >     43.58 KB
> >     43.59 KB
> >     ⯅ +4 Bytes
> >   
> >     sharedString.js
> >     158.21 KB
> >     158.22 KB
> >     ⯅ +2 Bytes
> >   
> >     Total Size
> >     1.38 MB
> >     1.61 MB
> >     ⯅ +239.12 KB
> >   Baseline commit: [309fe98](https://github.com/microsoft/FluidFramework/commit/309fe9801f48d9cdec4571c55242c0d529c3109e)
> > 
> >   Generated by 🚫 [dangerJS](https://danger.systems/js) against [f9a4a06](https://github.com/microsoft/FluidFramework/commit/f9a4a068d7c0f0dc8a8f808cc2aaebfcbe501587)
> 
> Shouldn't tree be a line item here?

I did notice the same thing and glance at the diff logic when I opened this. It makes sense it doesn't appear now--look at handling of `commonBundleMetrics`. It's a bit odd that the total size shows up larger, but should be transient...

I'll look into it if it doesn't start appearing in the diff for PRs with baseline above this one's CI, though.

**Comment by Abe27342** [comment]
> > ⯅ @fluid-example/bundle-size-tests: +239.12 KBMetric NameBaseline SizeCompare SizeSize Diff
> >     aqueduct.js
> >     437 KB
> >     437 KB
> >     ⯅ +6 Bytes
> >   
> >     connectionState.js
> >     680 Bytes
> >     680 Bytes
> >     ■ No change
> >   
> >     containerRuntime.js
> >     229.71 KB
> >     229.71 KB
> >     ⯅ +2 Bytes
> >   
> >     loader.js
> >     160.81 KB
> >     160.82 KB
> >     ⯅ +6 Bytes
> >   
> >     map.js
> >     44.07 KB
> >     44.07 KB
> >     ⯅ +2 Bytes
> >   
> >     matrix.js
> >     137.65 KB
> >     137.65 KB
> >     ⯅ +2 Bytes
> >   
> >     odspDriver.js
> >     92.35 KB
> >     92.36 KB
> >     ⯅ +6 Bytes
> >   
> >     odspPrefetchSnapshot.js
> >     43.58 KB
> >     43.59 KB
> >     ⯅ +4 Bytes
> >   
> >     sharedString.js
> >     158.21 KB
> >     158.22 KB
> >     ⯅ +2 Bytes
> >   
> >     Total Size
> >     1.38 MB
> >     1.61 MB
> >     ⯅ +239.12 KB
> >   Baseline commit: [309fe98](https://github.com/microsoft/FluidFramework/commit/309fe9801f48d9cdec4571c55242c0d529c3109e)
> > 
> >   Generated by 🚫 [dangerJS](https://danger.systems/js) against [f9a4a06](https://github.com/microsoft/FluidFramework/commit/f9a4a068d7c0f0dc8a8f808cc2aaebfcbe501587)
> 
> Shouldn't tree be a line item here?

New PRs include it now that it's in the baseline, see [here](https://github.com/microsoft/FluidFramework/pull/15248#issuecomment-1520631237). so we should be in good shape.

**Pull request merged**
