### PR TITLE
Start running e2e test targeting tinylicious in realsvc pipeline

### PR DESCRIPTION
**Pull request by curtisman**

### CODE REVIEW

**Comment by agarwal-navin** [comment]
We won't run against ODSP anymore?

**Review by anthony-murphy — APPROVED** [review]

**Comment by anthony-murphy** [comment]
wondering if we want a stress run for tinylicious too

**Comment by anthony-murphy** [comment]
> We won't run against ODSP anymore?

ODSP is defined later in the file

**Comment by agarwal-navin** [comment]
Missed that :-)

**Review by agarwal-navin — APPROVED** [review]

**Pull request merged**
