### PR TITLE
(odsp-client): Duplicate TokenResponse

### PR DESCRIPTION
**Pull request by sonalideshpandemsft**
This PR duplicates the `TokenResponse` code in odsp-client and tags `odsp-driver-definitions#TokenResponse` as alpha. 
 
[AB#8287](https://dev.azure.com/fluidframework/internal/_workitems/edit/8287)

### CODE REVIEW

**Review by ChumpChief — APPROVED** [review]
Couple nits but looks good I think - @anthony-murphy @jason-ha I think y'all are more familiar with AB#8287, does this look like a satisfactory resolution?

**Comment by jason-ha** [comment]
> Couple nits but looks good I think - @anthony-murphy @jason-ha I think y'all are more familiar with AB#8287, does this look like a satisfactory resolution?

Looks good to me.
Should there be any notes about keeping these in sync? Do they need to be kept in sync right now? If so, we could add some tests that they are the same.

**Review by jason-ha — APPROVED** [review]
downstream api reports need updated.
Ideally there would be test that confirms the types are the same.

**Comment by sonalideshpandemsft** [comment]
> > Couple nits but looks good I think - @anthony-murphy @jason-ha I think y'all are more familiar with [AB#8287](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/8287), does this look like a satisfactory resolution?
> 
> Looks good to me. Should there be any notes about keeping these in sync? Do they need to be kept in sync right now? If so, we could add some tests that they are the same.

I don't see a need for them to be in sync. Probably, the new interface should be renamed to `IOdspTokenResponse` or something else.  @ChumpChief, @anthony-murphy let me know if you feel different.

**Comment by ChumpChief** [comment]
> > > Couple nits but looks good I think - @anthony-murphy @jason-ha I think y'all are more familiar with [AB#8287](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/8287), does this look like a satisfactory resolution?
> > 
> > 
> > Looks good to me. Should there be any notes about keeping these in sync? Do they need to be kept in sync right now? If so, we could add some tests that they are the same.
> 
> I don't see a need for them to be in sync. Probably, the new interface should be renamed to `IOdspTokenResponse` or something else. @ChumpChief, @anthony-murphy let me know if you feel different.

Generally agree they don't need to be kept in sync (I think this is the purpose of having two versions with different tagging, is that they're permitted to change at different rates) - but I'd also probably not rename right now unless/until we have a strong motivation to deviate.  I think being exported from the odsp-client package is sufficient signal that this is an odsp-specific type.

**Pull request merged**
