### PR TITLE
fix(devtools): Fixed bug causing multiple focuses on Audience tables

### PR DESCRIPTION
**Pull request by WayneFerrao**
[AB#4839](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4839)

## Description

This PR fixes an a11y bug where tab navigating to the Audience table would show multiple focuses on the table cell and info icon, without being able to interact with it to show the tooltip text. The fix ensures only the info icon is accessible with tab/arrow navigation.

#### Notes
I tried using the built in utilities like useArrowNavigationGroup and tweaking tabIndex, but that didn't work. [reference](https://react.fluentui.dev/?path=/docs/components-table--default)
Updating from TableHeaderCell to TableCell seemed to do the trick without any major changes to the appearance.

### CODE REVIEW

**Comment by alexvy86** [comment]
Hmm I wonder if TableHeaderCell -> TableCell costs us on another accessibility front though. I'd imagine it was previously rendered as a `<th>` and now it's a `<td>`? Not sure what screen readers would make of that distinction. Maybe @Josmithr has thoughts on that?

**Comment by Josmithr** [comment]
> Hmm I wonder if TableHeaderCell -> TableCell costs us on another accessibility front though. I'd imagine it was previously rendered as a `<th>` and now it's a `<td>`? Not sure what screen readers would make of that distinction. Maybe @Josmithr has thoughts on that?

Yeah, I believe the header aspect is important for screen readers in particular, both to help differentiate "content" from "context", as well as to associate individual data cells with their semantics. I suspect that making this change will result in a different bug we'll have to contend with in the future ☹️

**Review by Josmithr — APPROVED** [review]

**Comment by Josmithr** [comment]
Nit: for your PR title, I would just use "fix" rather than "bugfix"

**Comment by WayneFerrao** [comment]
Merging with temp fix for now. Tracking TableHeaderCell bug here: https://github.com/microsoft/fluentui/issues/31588
Relevant ADO Task: AB#8277

**Review by Josmithr — APPROVED** [review]

**Pull request merged**
