### PR TITLE
Assert: Optionally log telemetry error event on assertion failure

### PR DESCRIPTION
**Pull request by DLehenbauer**
@anthony-murphy - Curious what you think about expanding assert() to optionally log a telemetry error event?  (Vlad and I were recently looking at a PR that was throwing an unreachable code error and logging telemetry back-to-back in several places.)

@vladsud - Inspired by your feedback on Wes's PR.

(You won't hurt my feelings if you feel this has low value.)

### CODE REVIEW

**Comment by anthony-murphy** [comment]
i'm pretty against this. it leads to a lot of redundant logging. my perspective is exceptions should just be thrown, and only entry points should capture and log them

**Comment by anthony-murphy** [comment]
in general i think we should move away for assert. so if someone wants to log more information, they should throw a logging error directly, or just log at that point

**Comment by vladsud** [comment]
I've started with something like that by having debugAssert() and shipAssert() methods directly on the logger, with expectation that they would be used in log-and-continue flow. It did not take off, and I think Tony removed them :)

Not directly on subject, but this issue is interesting to look at overall problem space.
And it's useful to look at how it's done in parallel universe - devmain / C++ code base -  we use 3 forms of constraints validation:
1. assert() - only works in debug builds by bringing attention of developer (syncronously) to the problem. Noop in ship builds.
2. shipAssert() - same as above, but also logs a assert tag to telemetry. There was a way to request more data to be collected from machines that are hitting an issue.
3. VerifyElseCrash - terminate process of pre-condition is violated, pushing data to http://Watson and resulting in automatic bugs opened for developers to investigate.

There is one very important tidbit to add - C++ exceptions were mostly for exceptional cases, i.e. it was discouraged to catch exceptions, in most cases they would lead to a crash (for example, new() operator throwing out of memory case). Normal flows (aka expected errors) usually do not use exceptions, both because it's expensive from perf side, as well as lack of type safety / validation.

Usage of asserts is not great in our repo, as it changes control flow in unpredictable way. That combined with catching exceptions and continuing (in some state) and lack of easy RAII patterns in JS makes it in general really dangerous tool. That said, I do not see a great alternative, given lack of something like # 3 at our disposal (in the form of construct to use, but also in a form of centralized database of app defects for all apps in ecosystem).

**Comment by markfields** [comment]
I'm with @anthony-murphy here on both points (let higher layers log errors as they impact specific activities, and use assert more judiciously).

Are there specific cases we have in mind where a thrown error is never logged (whether from assert or otherwise)?  I guess we could look at Office Fluid's unhandled exceptions table, I think they register on `window` and log anything that gets that far.  Other than those, we should be capturing errors at entrypoints and logging them then - and maybe also logging them as intermediate activities (that is, perf events) fail.

To @vladsud's big-picture comment, we should be very critical of wherever we catch an error and continue...

**Pull request closed without merging**
