### PR TITLE
Bump version of @types/node

### PR DESCRIPTION
**Pull request by markfields**
I noticed it's still on 10.17 in places when I was trying to register a listener for an event added in 12.17 and intellisense wasn't picking it up.

Only updating those that were older than 12.17.  Happy to update others too though for whatever reason.

I wonder if we should try to keep this version and the version in .nvmrc in sync?  @tylerbutler , @curtisman - thoughts?

### CODE REVIEW

**Comment by curtisman** [comment]
Old typing probably doesn't matter that much in general, as they are usually forward compatible. 
But if we are updating, moving everything forward consistently would be good.

**Comment by markfields** [comment]
> Old typing probably doesn't matter that much in general

True, but since I stumbled on a missing API I figured I'd do something about it.

Except YIKES more build errors.  Putting on hold for today at least...

**Comment by markfields** [comment]
PS - there's no @types/node at 12.18.3 (the version in .nvmrc) so I couldn't set it to match exactly.  @tylerbutler any objection to me bumping that too so they match, if I press on here?

**Comment by tylerbutler** [comment]
> PS - there's no @types/node at 12.18.3 (the version in .nvmrc) so I couldn't set it to match exactly. @tylerbutler Tyler Butler FTE any objection to me bumping that too so they match, if I press on here?

That's fine with me, but I would prefer bumping forward rather than back. I.e. 12.21.0, the latest v12 release.

**Comment by tylerbutler** [comment]
> Except YIKES more build errors.

Yeah, you'll probably hit a bunch of "value can be null or undefined" errors because the typings have improved.

**Comment by curtisman** [comment]
In general,  typing package and node version isn't always one to one and I don't know if they actually following the same version scheme. To be safe,  we should bump to the closest older version so we don't accidentally depends on newer features

**Comment by markfields** [comment]
Ok thinking a little more critically here, and remembering so past research. The types versions correspond to the JS package versions for major/minor but not patch. This is sensible since major/minor bumps are where API changes are introduced.

As mentioned in another thread, we are periodically taking updates of Node e.g. for security fixes, but could also include minor bumps. Nonetheless our docs say min requires version is 12.17. So to Curtis's point, I don't think any of us should be developing with types past 12.17.  I'll take a look at this again soon and push an update along those lines if it still makes sense to me :)

**Comment by tylerbutler** [comment]
@markfields FYI @DLehenbauer took care of this in PR #5796.

**Comment by markfields** [comment]
@curtisman @tylerbutler @DLehenbauer - Our main docs page says Fluid supports 12.17 and later.  But importing @types/node v 12.19 we could quietly introduce a dependency on a 12.19 feature new since 12.17.  I haven't looked at the release notes to know what that delta is like, but IMO we should keep these two versions in sync.  I'll leave it to you three to decide if it's worth following up on, just want to raise it.

**Comment by markfields** [comment]
Oops I thought I was commenting on Daniel's PR.  Anyway...

**Pull request closed without merging**
