### PR TITLE
Remove unneeded built-tools deps

### PR DESCRIPTION
**Pull request by CraigMacomber**
## Description

Build-tools (the release group) should use the version of build-tools (the package) that it contains, not a published one.

Also it does not require test-tools since it just uses mocha and not jest.

## Reviewer Guidance

The review process is outlined on [this wiki page](https://github.com/microsoft/FluidFramework/wiki/PR-Guidelines#guidelines).

Question: why does this add "dev: false" to a bunch of places?

### CODE REVIEW

**Review by Josmithr — APPROVED** [review]
🚀

**Comment by tylerbutler** [comment]
@CraigMacomber that was an intentional change in preparation for using fluid-build to build build-tools. @curtisman FYI.

**Comment by CraigMacomber** [comment]
@tylerbutler Which part was intended? Depending on but not using test-tools, or depending on a non-workspace version of build-tools?

**Comment by CraigMacomber** [comment]
I can confirm this breaks running build:fast on a cleaned build:tools. I'll either revert that change or provide a fix.

**Pull request merged**
