### PR TITLE
Fix IsoBuffer.from (0.35)

### PR DESCRIPTION
**Pull request by vladsud**

### CODE REVIEW

**Comment by vladsud** [comment]
Note - there is already test _"bufferToString working with IsoBuffer"_ for IsoBuffer (which is typed array).

**Comment by anthony-murphy** [comment]
i you want client packages 0.35 to get this change, it needs to be made is branch release/0.33, which is the branch common utils 0.27 is released from.

**Comment by vladsud** [comment]
I can do that, but can't we release 0.27.2 (or whatever the latest) from here?

**Comment by anthony-murphy** [comment]
no, becuase the version of common utils in this branch is 0.28 which is a yet to be released version, and may not be compatible with 0.27

**Comment by vladsud** [comment]
Ok, will do that, though I do not understand why would we bump a version of common-util and not consume it - that does not make sense to me. It's time bomb - we accumulate a bunch of changes and hope future consumption would be easy - it should be more incremental IMHO (bump version and consume latest every release, or not bump it).

**Comment by anthony-murphy** [comment]
agreed. whoever bumped it should consume it. super weird it's bumped but not used

**Comment by vladsud** [comment]
Moving to 0.33 / https://github.com/microsoft/FluidFramework/pull/5378

**Pull request closed without merging**
