### PR TITLE
Fixed an assert in container runtime GC code that was incorrect (#10237)

### PR DESCRIPTION
**Pull request by agarwal-navin**
Ported from main (#10237).

The assert in `getGCNodePackagePath` if the package path is undefined is incorrect. The package path can be undefined if the data store has not been loaded.
This assert was meant to validate that `getGCNodePackagePath` is only called for attachment blob nodes and nodes belonging to a data store. Update the assert to validate that:

Added a new GC node type: `SubDataStore` - Any nodes that are children of data stores. For example, nodes for DDS / nodes within a DDS.
The assert validates that `getGCNodePackagePath` is called for data stores, sub data stores or blob nodes.

### CODE REVIEW

**Comment by agarwal-navin** [comment]
This is failing with the following error which is unrelated to this change:
@fluidframework/undo-redo: [build:commonjs] src/test/types/validateUndoRedoPrevious.ts:111:5 - error TS2345: Argument of type 'TypeOnly<import("/mnt/vss/_work/1/s/packages/framework/undo-redo/dist/sequenceHandler").SharedSegmentSequenceRevertible>' is not assignable to parameter of type 'TypeOnly<import("/mnt/vss/_work/1/s/node_modules/@fluidframework/undo-redo-previous/dist/sequenceHandler").SharedSegmentSequenceRevertible>'.
@fluidframework/undo-redo: [build:commonjs]   Types of property 'sequence' are incompatible.
@fluidframework/undo-redo: [build:commonjs]     Type 'TypeOnly<SharedSegmentSequence<ISegment>>' is missing the following properties from type 'TypeOnly<SharedSegmentSequence<ISegment>>': createLocalReferencePosition, localReferencePositionToPosition, removeLocalReferencePosition
@fluidframework/undo-redo: [build:commonjs] 
@fluidframework/undo-redo: [build:commonjs] 111     get_current_ClassDeclaration_SharedSegmentSequenceRevertible());

**Comment by wes-carlson** [comment]
No clue why it's happening. I'm guessing you should just suppress this error. @anthony-murphy ?

**Comment by anthony-murphy** [comment]
> Adding the following to the package.json under `packages/framework/undo-redo` fixes this but I am not sure why this was not caught before:
> 
> ```
> "broken": {
>       "0.59.1000": {
>         "ClassDeclaration_SharedSegmentSequenceRevertible": {
>           "backCompat": false
>         }
>       }
>     }
> ```
fails in the lab too. not sure how we got to this state

**Comment by agarwal-navin** [comment]
Should I add this fix so we can get a patch with the fix released?

**Comment by anthony-murphy** [comment]
> Should I add this fix so we can get a patch with the fix released?

yes

**Comment by agarwal-navin** [comment]
I added it in this PR itself. Please take a look.

**Review by wes-carlson — APPROVED** [review]

**Pull request merged**
