### PR TITLE
[bump] server: 2.0.2 => 2.0.3 (patch)

### PR DESCRIPTION
**Pull request by arafat-java**
## Description
Version bump from 2.0.2 to 2.0.3 for patch release of server

### CODE REVIEW

**Comment by arafat-java** [comment]
@microsoft-github-policy-service agree

**Comment by arafat-java** [comment]
@CraigMacomber  ,  @tylerbutler  ,  @nmsimons 
Had fixed a minor bug in deleting summarized ops and we need a patch release for this

**Comment by arafat-java** [comment]
@tylerbutler , @anthony-murphy , @nmsimons 
Any updates on this

**Review by CraigMacomber — APPROVED** [review]

**Comment by CraigMacomber** [comment]
Looks like this version bump was missed after 2.0.2, then a patch was merged that has not been released. A new release is needed, and this patch is the next step.

**Pull request merged**
