### PR TITLE
Remove IFluidObject from Default IFluidHandle Generic

### LINKED ISSUE #8940: Move IFluidHandle off IFluidObject
## Work Item
**Describe the outcome you expect**

**Approach**

**Open questions**

**Additional context**

**Acceptance criteria**

### PR DESCRIPTION
**Pull request by anthony-murphy**
IFluidObject is no longer part of the type of IFluidHandle generic's default.

``` diff
- IFluidHandle<T = IFluidObject & FluidObject & IFluidLoadable>
+ IFluidHandle<T = FluidObject & IFluidLoadable>
```

This will affect the result of all `get()` calls on IFluidHandle's, and the default return will no longer be and IFluidObject by default. IFluidHandle generic's default is still an [FluidObject](https://github.com/microsoft/FluidFramework/blob/main/BREAKING.md#Deprecate-IFluidObject-and-introduce-FluidObject) which should be used instead.

fixes #8940

### CODE REVIEW

**Comment by agarwal-navin** [comment]
Is the work to integrate this already done in FFX? From what I understand, the plan is that they move to the new patterns before the version that removes this will be released.

**Comment by anthony-murphy** [comment]
> Is the work to integrate this already done in FFX? From what I understand, the plan is that they move to the new patterns before the version that removes this will be released.

@leeviana  would know best. nothing here changes at runtime. IFluidObject has been deprecated for a long while, but still seems heavily used. They can still pass IFluidObject to the generic, but we don't do it by default anymore.

**Review by agarwal-navin — APPROVED** [review]

**Comment by leeviana** [comment]
Hmm, this does seem likely to break typings somewhere but I'd consider this "backwards compatible" since I think anywhere this breaks things, we could actually split out the change as pre-work and do it before the bump?

**Comment by anthony-murphy** [comment]
> Thanks for the heads up/checking! This does seem likely to break typings somewhere but I'd consider this "backwards compatible" since I think anywhere this breaks things, we could actually split out the change as pre-work and do it before the bump?

@leeviana  I've looked at it and don't see anything obvious beside things i'm already fixing. there could be stuff, but usually things gotten from handles are already casted appropriately.

**Pull request merged**
