### PR TITLE
Bump async to 3.2.0

### PR DESCRIPTION
**Pull request by evaliyev**

### CODE REVIEW

**Comment by curtisman** [comment]
It looks ok to me.  But since mostly server changes, @tanviraumi  Can you take a look?

**Comment by evaliyev** [comment]
@curtisman Thanks for taking a look! I'm not sure what is the procedure for bumping versions of affected packages.

**Comment by DLehenbauer** [comment]
@tanviraumi - I'm pretty confident that changes are equivalent to the original, so I'm going to go ahead and approve/merge to keep things flowing.

The API changes introduced in Async 3.0 are:

1.  You register event callbacks with a method instead of assigning a property (e.g. `q.empty(callback)` instead of `q.empty = callback`.  If you omit the callback, async returns a promise instead (e.g. `await q.empty()`).
2.  Similarly, `q.push(..)` now returns a Promise if the callback is omitted.
3.  The type returned from `queue()` is now `QueueObject` instead of `AsyncQueue`...  but it's the same thing created the same way.

You may want to tag a code owner to have a look at where @evaliyev needed to add 'void' to suppress lint errors and verify that the dropped Promise is intentional.  (These should probably have either a comment or a .catch() that logs the error.)

**Review by DLehenbauer — APPROVED** [review]

**Review by tanviraumi — APPROVED** [review]

**Comment by SamBroner** [comment]
So glad to see this commit @evaliyev. Big moment!

**Pull request merged**
