### PR TITLE
Remove 'tryWhileSummarizing' workaround for Property-Query tests

### PR DESCRIPTION
**Pull request by DLehenbauer**
Fixes GH #7340

### CODE REVIEW

**Comment by vladsud** [comment]
Interesting, it did pass for you. Might be just luck with timing?

**Comment by DLehenbauer** [comment]
@vladsud - If I'm reading the test history correctly, you hit the failure just once?

I'll give it a few more tries to see if there's evidence it's running close to it's time limit.

**Comment by vladsud** [comment]
No, I hit it continuously when rerunning pipeline on same bits. And the moment I've submitted that last commit, it cleared. What's possible is that there were more changes in between these runs and something changed somewhere else that changed timing?
If we can't repro, I'd submit this change and wait till we get further signal.

**Comment by vladsud** [comment]
Interesting, it hit timeout in latest retry. So the is there, maybe we are right on the boundary of that 4s timeout.
I was not able to find where we set it or how to overwrite it though

**Review by vladsud — APPROVED** [review]

**Pull request closed without merging**
