### PR TITLE
fix(driver-utils): Fix comparison that always return true

### PR DESCRIPTION
**Pull request by tylerbutler**
This issue was uncovered while experimenting using esbuild to build Fluid apps. The former checks were invalid and would always return true or false because object comparison in JS is done via reference, not value.

I'm not certain that my change is correct. I think the old code was trying to check if the object was empty, which is what my change does, but there may be subtle differences.

Also, I don't know if this would cause some sort of runtime error, because now codepaths will open up that were previously skipped.

### CODE REVIEW

**Review by ChumpChief — APPROVED** [review]
LGTM as far as the technique used and probable intention of the code.  Might want an opinion from someone more familiar with this specific code re: whether the fix might break something that was expecting the bug.

**Comment by tylerbutler** [comment]
An alternative might be to use EmptyObject from type-fest: <https://github.com/sindresorhus/type-fest/blob/HEAD/source/empty-object.d.ts>

**Comment by vladsud** [comment]
> Also, I don't know if this would cause some sort of runtime error, because now codepaths will open up that were previously skipped.

This code is not used - it was implemented in response to ODSP escalation, but improvements on back-end made it less important, so we never shipped it. Probably should remove :)

**Comment by vladsud** [comment]
> @vladsud When you say it should be removed, do you mean the whole [compressSmallBlobs](https://github.com/tylerbutler/FluidFramework/blob/deb3b5d5e6fa8aad7d7d8912681a58871e37348c/packages/loader/driver-utils/src/blobAggregationStorage.ts#L281) method, or something else?

No, the whole file / BlobAggregationStorage class

**Comment by tylerbutler** [comment]
Closing in favor of #14157.

**Pull request closed without merging**
