### PR TITLE
test(devtools-view): Add SharedMatrix to test app

### PR DESCRIPTION
**Pull request by Josmithr**
Adds a usage of SharedMatrix by updating the emoji button view to be a small 2x2 grid of emoji buttons.

emoji-grid

### CODE REVIEW

**Comment by Josmithr** [comment]
Observations from the data view:
* We don't currently do a good job of annotating the associated row/column metadata to the tree view. That data is being generated, we just need to add it to the view. @jikim-msft I believe you filed a task for adding the missing metadata, right?
* For each of the row entries under the matrix, we are annotating the "type" as "TreeNode", but "TreeNode" is a devtools-internal concept, and isn't representative of the Matrix data. I see a couple of ways we can improve this:
    1. We could flatten the tree for Matrix visuals, and annotate each entry with row and column (rather than having a child for each row with their own hierarchy).
    2. We update the way we annotate nested tree visuals to be more explicit in terms of metadata.
    - I think we ultimately probably want to do both. SharedMatrix doesn't store its data in the hierarchical form being displayed, so it's a bit misleading, but we also don't want to leak external concepts in our visualizations.

**Comment by jikim-msft** [comment]
> 

I do not recall if I have created a separate item for the missing metadata. But I remember having a conversation with you about the missing metadata in the DDS which makes it harder to render useful data. 

One question about the picture from description is, is rendering a boolean value `true` serve any purpose in DevTools?

**Comment by Josmithr** [comment]
> I do not recall if I have created a separate item for the missing metadata. But I remember having a conversation with you about the missing metadata in the DDS which makes it harder to render useful data.

I filed a task for the metadata visualization here: https://dev.azure.com/fluidframework/internal/_workitems/edit/4254

And a task for improving the visual keys generated by the SharedMatrix visualizer: https://dev.azure.com/fluidframework/internal/_workitems/edit/4255

> One question about the picture from description is, is rendering a boolean value `true` serve any purpose in DevTools?

Booleans are what are stored by the app to represent the emoji state in our example, so I would argue yes. We want our devtools to match the underlying data model, which is what we're doing there.

**Review by jikim-msft — APPROVED** [review]
Everything looks great and I love the new emoji matrix! Just want to give you a heads up that `App.tsx` and `EmojiGrid.tsx` will be subject to significant changes as I am currently working on a PR which removes `StackItem` and `Accordion` for UI consistency (which Rohan has pointed out in our team chat) 😃.

**Comment by Josmithr** [comment]
> Everything looks great and I love the new emoji matrix! Just want to give you a heads up that `App.tsx` and `EmojiGrid.tsx` will be subject to significant changes as I am currently working on a PR which removes `StackItem` and `Accordion` for UI consistency (which Rohan has pointed out in our team chat) 😃.

Sounds good! Yeah, no worries if this changes style wise, just so long as the buttons continue to work 😁 Thanks!

**Pull request merged**
