### PR TITLE
webpack config cleanup

### PR DESCRIPTION
**Pull request by CraigMacomber**
## Description

A few webpack config changes for examples:

- remove unneeded require.resolve from webpack loaders. Webpack can resolve these by itself just fine, and in many other places we already rely on it doing so.
- remove unnneded quoting and escaping for env in a few package,json files
- fix detection of production vs development in config files:
  - Simplify logic using `?.`
  - Correct several configs which always returned development because detection of production checked environment object against string. The old incorrect behavior was determined by debugging the smde example and checking that it worked incorrectly before and is fixed afterward.

### CODE REVIEW

**Comment by ChumpChief** [comment]
> Currently running npm run webpack in the root fails due to issues with css in prosemirror: these issues are unchanged by my changes, but leaves me without a great way to test this. I don't see any new errors in top level npm run webpack, but it has a lot of console spam and warning already, so I might have missed something. At least CI will confirm the test webpack configs work.

It looks like the prosemirror-menu dependency got updated recently, from 1.1.4 to 1.2.0 (probably unintentionally).  In 1.2.0 it looks like prosemirror-menu added an exports field in its package.json but forgot the css.  It looks like this has been fixed in 1.2.1 if you want to bump to that version.
https://github.com/ProseMirror/prosemirror-menu/commit/11d85967a637b774b925a85c059a24dfab27b08b

**Comment by ChumpChief** [comment]
Looks like the demo still errors at runtime using 1.2.1 but at least packing succeeds.  Probably needs a little more attention.

**Comment by CraigMacomber** [comment]
> Looks like the demo still errors at runtime using 1.2.1 but at least packing succeeds. Probably needs a little more attention.

I made a separate PR for that https://github.com/microsoft/FluidFramework/pull/10893 and file an issue in our internal tracker to follow-up on the broken examples (its beyond the scope of what I have time for currently): https://dev.azure.com/fluidframework/internal/_workitems/edit/1024

**Comment by tylerbutler** [comment]
Regarding the require.resolve, that was originally done per the guidance in the "no unqualified webpack config" section here: https://yarnpkg.com/api/modules/yarnpkg_doctor.html

The issue linked there is closed, but it's unclear if it was fixed. Maybe we don't care because we don't plan to use yarn PnP, but that's the reason the require.resolve calls are there.

**Comment by tylerbutler** [comment]
Also if all our configs are in private projects or in packages that are otherwise not extended, then this is even less relevant.

**Comment by CraigMacomber** [comment]
> Also if all our configs are in private projects or in packages that are otherwise not extended, then this is even less relevant.

> Regarding the require.resolve, that was originally done per the guidance in the "no unqualified webpack config" section here: https://yarnpkg.com/api/modules/yarnpkg_doctor.html
> 
> The issue linked there is closed, but it's unclear if it was fixed. Maybe we don't care because we don't plan to use yarn PnP, but that's the reason the require.resolve calls are there.

We don't ship any of these configs as part of the packages. They are all for testing, or in the one case of property-inspector-table where it's used as a build step: but we still don't include the config as part of the package.

Thus I don't think the concern expressed in that article applies.

I mostly removed the resolve since we only do it sometimes, and inconsistently copying that pattern when we don't think we need it seems like a bad idea. If we actually did if everywhere it might make sense to leave it.

Also most of the resolvers are ts-loader. We don't ship the ts-source in our packages (we ship JS and d.ts files), so those webpack configs wouldn't even make sense for consuming our actual published packages.

**Review by tylerbutler — APPROVED** [review]
Looks good once CI passes.

**Pull request merged**
