### PR TITLE
Ensure error is not undefined when raising "disconnected" event

### PR DESCRIPTION
**Pull request by markfields**
Fixes a bug introduced in https://github.com/microsoft/FluidFramework/pull/12223 which we probably want to patch

### CODE REVIEW

**Review by jatgarg — APPROVED** [review]

**Comment by wes-carlson** [comment]
Is this just a hotfix? From the containers I looked at it looks like we are dropping socket errors that we handled fine before.

**Review by NicholasCouri — APPROVED** [review]

**Review by NicholasCouri — COMMENTED** [review]
@markfields I haven't looked into all the scenarios in which we emit the disconnect and the error might be undefined - to be honest I stopped when I found this one. Did you check for other instances ?  I will try just to be safe.

**Comment by anthony-murphy** [comment]
this doesn't look quite right to me, but the details might be more complicated. i would think the event should just add undefined to the type defintion, as closeing a socket without error, like when shutting everything down, should be totatally valid. it seems really wierd that all disconnects must have an error, even in non-error cases

**Comment by anthony-murphy** [comment]
it does look like this is new in this release: 
https://github.com/microsoft/FluidFramework/commit/fdd60e13b9eca996eddf21f5a99248e30ef4686a

I think the the type is wrong

**Comment by markfields** [comment]
@anthony-murphy I had the same thought when I went to patch this up. And @vladsud obviously had the same assumption too.  This fix was based on the precedent I found in this code:  https://github.com/markfields/FluidFramework/blob/cfbed8781364dd1a68cf0184c32444a638d215e3/packages/drivers/driver-base/src/documentDeltaConnection.ts#L326

Definitely could see a follow-up change to add support for error-less disconnects, or as discussed in other APIs, maybe it's error | reason in some shape or form.

Also, the gap in type checking on emitting events is a serious bummer.  I had a prototype of a different approach to event typing I've been planning to bring to Office Hours one day, maybe I'll try to prioritize that a little more given this example of it actually biting us.

**Pull request merged**
