### PR TITLE
Add docker-compose.dev.yml to server/

### PR DESCRIPTION
**Pull request by znewton**
It's currently a bit of a pain to develop across R11s, Historian, and Gitrest. This docker-compose.dev file makes it as easy as `docker compose -f docker-compose.dev.yml up`, then you can simply make any necessary changes in R11s, Historian, or Gitrest, rebuild that service, then `docker compose restart <service>`

### CODE REVIEW

**Review by pradeepvairamani — COMMENTED** [review]
Nice! Maybe add a script in package.json too?

**Comment by znewton** [comment]
@pradeepvairamani there is no FluidFramework/server/package.json

**Comment by pradeepvairamani** [comment]
> 

oh I thought we could have it at the root package.json itself like 
`
"start:docker": "docker-compose -f server/docker-compose.yml up",
"stop:docker": "docker-compose -f server/docker-compose.yml down",
`
 but maybe we don't want to pollute that too much.

**Review by hedasilv — APPROVED** [review]
This is great! Alternatively to a package.json, we could edit (in case there are any) or add a README.md in `server/` with those commands you listed on the PR description, to help anyone not familiar with Docker.

**Comment by znewton** [comment]
Thanks for the suggestions @pradeepvairamani and @hedasilv. I added a chunk to the server/README about this new dev feature. I think I'll open a separate PR for the root package.json so that any discussion around pollution does not hinder this PR.

**Review by hedasilv — APPROVED** [review]

**Review by pradeepvairamani — APPROVED** [review]

**Review by tanviraumi — APPROVED** [review]
:shipit:

**Pull request merged**
