### PR TITLE
Pull json-web-token out of server-services-client

### PR DESCRIPTION
**Pull request by christiango**
Server-services-client is used in a browser context today, therefore it should not have any node dependencies. This is not currently the case due to the dependency on json-web-token which has dependencies on stream and crypto. This PR splits out the json-web-token bits from server-services client so we can start using a native JS implementation in browser scenarios like local-driver.

### CODE REVIEW

**Comment by christiango** [comment]
Will need help from the FF folks once this is in to get the new server packages generated so I can do the client bump. Who is the right person to help with that?

**Comment by tanviraumi** [comment]
@anthony-murphy for the client bump.

**Review by tanviraumi — APPROVED** [review]

**Comment by christiango** [comment]
@tanviraumi - it looks like there is a test in lambdas that enforces that server-utils is isomorphic. How should we proceed?

**Comment by anthony-murphy** [comment]
utils has a bunch of stuff that definitly won't work is a browser, which will break a bunch of our local web server scenarios, like https://fluidframework.com/playground/

i would see if there is a common place that's already references where this can go, or you might need to create a new package

**Comment by christiango** [comment]
> utils has a bunch of stuff that definitly won't work is a browser, which will break a bunch of our local web server scenarios, like https://fluidframework.com/playground/
> 
> i would see if there is a common place that's already references where this can go, or you might need to create a new package

So what's interesting here Tony is that I'm specifically extracting out things that do not work in the browser. In theory, this isomorphic test should already be failing since JSON web token is certainly not isomorphic. It might have to do with the fact that server-services-client generates ESM to enable tree shaking, but this line here is already not browser friendly and this PR doesn't really change that (at least not directly)

https://github.com/microsoft/FluidFramework/blob/main/server/routerlicious/packages/lambdas/src/foreman/lambda.ts#L15

I'm wondering if we should just go back to moving to jsrassign everywhere, which should work on both browser and server with no dependencies.

**Comment by tanviraumi** [comment]
> So what's interesting here Tony is that I'm specifically extracting out things that do not work in the browser. In theory, this isomorphic test should already be failing since JSON web token is certainly not isomorphic. It might have to do with the fact that server-services-client generates ESM to enable tree shaking, but this line here is already not browser friendly and this PR doesn't really change that (at least not directly)

This is interesting. I am not sure whats special about "jsonwebtoken" library, but the errors are probably caused by other node specific libraries inside service-utils. 

I have been thinking whether we should use jsrassign everywhere but other than the security issue, there is one more issue. Tokens are not signed by us. They are signed by hosts. Our job is to verify it. Using a more standard library helps us to maintain compatibility. And I am afraid to use a less standard library on our end to verify the tokens signed by external hosts. But I also understand the the issues you are facing, so here is a potential workaround.

Currently no one uses foreman lambda. But we are keeping it alive for some future service scenarios for the FRS team. So for now, you can just replace the token with a string in the foreman lambda. Open an issue against me and I will make it an interface rather than direct dependency. We already have the pattern to keep the lambda separate from implementation details. You can also do that in this PR if its worth your time :) 

Doing this will stop the errors in lambda package. Next one is local-server. For that, you can just sign with jsrassign directly and add a comment why. This one is not scary cause its meant to run locally anyway so no security concern. We may not need to sign any token here cause the verification is probably pass through. But @anthony-murphy can verify.

I think these two will isolate this use between client and server. Rest are already service specific so the tests should pass.

**Comment by christiango** [comment]
Thanks for the suggestion. I removed the server lambdas usage with a todo to #4010. Updating the test now

**Comment by christiango** [comment]
@tanviraumi / @anthony-murphy - can one of you help me figure out what the test failure here is? It passes locally and it doesn't say what the error is in the build logs.

At first I thought it was this bit:
@fluidframework/server-local-server: 2020-10-21T16:56:57.199Z fluid-server:LocalDeltaConnectionServer Protocol error SyntaxError: Unexpected token w in JSON at position 0
@fluidframework/server-local-server: 2020-10-21T16:56:57.203Z fluid-server:LocalDeltaConnectionServer Protocol error SyntaxError: Unexpected token r in JSON at position 0

But I see that's happening in master and for other PR builds that pass!

https://dev.azure.com/fluidframework/public/_build/results?buildId=7411&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=138573f1-1c81-5936-fd5c-74f32fbb8748

**Comment by tanviraumi** [comment]
I am not sure why the test failing is crashing here while others are passing. @anthony-murphy ?

**Comment by anthony-murphy** [comment]
it looks like the web pack test is timing out. not sure why. does it fail locally? maybe just try webpacking the lambda's package to see if that gives a better error?

**Comment by christiango** [comment]
> it looks like the web pack test is timing out. not sure why. does it fail locally? maybe just try webpacking the lambda's package to see if that gives a better error?

It passes just fine for me locally when I run npm run test from packages/lambdas


  Routerlicious
    Broadcaster
      Lambda
        .handler()
9
          √ Should broadcast incoming messages

  Routerlicious
    Deli
      CheckpointContext
        .checkpoint
          √ Should be able to submit a new checkpoint
          √ Should be able to submit multiple checkpoints

  Routerlicious
    Deli
      Lambda
        .handler
          √ Should nack a client that has not sent a join
          √ Should nack a client that sends a message under the min sequence number
          √ Should nack all future messages from a nacked client
          √ Should be able to ticket an incoming message
          √ Should ticket new clients connecting above msn
          √ Should timeout idle clients
          √ Should remove clients after a disconnect

  Routerlicious
    Scriptorium
      Lambda
        .handler()
          √ Should store incoming messages to database

  Routerlicious.Lambdas
    √ Webpack to ensure isomorphism (299ms)

**Comment by christiango** [comment]
I reverted some of the lockfile changes and now I get this on the buddy build, but not locally:

fluidframework/server-local-server: Unhandled rejection AssertionError [ERR_ASSERTION]: ModuleNotFoundError: Module not found: Error: Can't resolve 'moniker' in '/usr/src/server/packages/memory-orderer/dist'

**Comment by christiango** [comment]
What I can repro locally is that I get this if I run npm run test in packages/routerlicious, but there is no details as to what the error is. I also get this same exact issue in master. I'm not sure what to do next since I was hoping this PR would be a lot quicker to get in.

D:\FluidFramework\server\routerlicious\packages\routerlicious>npm run test

> @fluidframework/server-routerlicious@0.1014.0 test D:\FluidFramework\server\routerlicious\packages\routerlicious
> mocha --recursive dist/test --unhandled-rejections=strict



  Routerlicious
    Alfred
      WebSockets
        Messages
          #connect_document
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            √ Should connect to and create a new interactive document on first connection
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            √ Should connect to and set existing flag to true when connecting to an existing document
          #disconnect
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            √ Should disconnect from an interactive document
          #submitOp
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            √ Can connect to the web socket server
    storage
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"protocolTree {\"sha\":\"c715aff4-421c-433c-be38-351a7c9393ad\",\"url\":\"\",\"tree\":[{\"mode\":\"100644\",\"path\":\"quorumMembers\",\"sha\":\"0637a088a01e8ddab3bf3fa98dbe804cbde1a0dc\",\"size\":0,\"type\":\"blob\",\"url\":\"\"},{\"mode\":\"100644\",\"path\":\"quorumProposals\",\"sha\":\"0637a088a01e8ddab3bf3fa98dbe804cbde1a0dc\",\"size\":0,\"type\":\"blob\",\"url\":\"\"},{\"mode\":\"100644\",\"path\":\"quorumValues\",\"sha\":\"95a5cd3624be83a3a654967fac6e8a79055f4882\",\"size\":0,\"type\":\"blob\",\"url\":\"\"},{\"mode\":\"100644\",\"path\":\"attributes\",\"sha\":\"c08fa99c0bae706e525ee64afbdcf901b1e993c1\",\"size\":0,\"type\":\"blob\",\"url\":\"\"}]}"}
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"appSummaryTree {\"sha\":\"19e2171a-ac3c-4ea5-b056-436a0b372557\",\"url\":\"\",\"tree\":[]}"}
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"commit sha: \"cc9a4e62-eb94-4535-9642-9b3919f41fda\""}
      √ create document with summary


  5 passing (74ms)

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! @fluidframework/server-routerlicious@0.1014.0 test: `mocha --recursive dist/test --unhandled-rejections=strict`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the @fluidframework/server-routerlicious@0.1014.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chrisgo\AppData\Roaming\npm-cache\_logs\2020-10-21T22_11_53_405Z-debug.log

**Comment by anthony-murphy** [comment]
@tanviraumi  any idea why server\routerlicious\packages\routerlicious\src\test\alfred\io.spec.ts is failing the test run? all the test's pass, but lerna is complaining about std error output

**Comment by tanviraumi** [comment]
I can't rerpo it locally. My test results are this and I am on latest main.

> @fluidframework/server-routerlicious@0.1014.0 test /Users/tanvir/Desktop/FluidFramework/server/routerlicious/packages/routerlicious
> mocha --recursive dist/test --unhandled-rejections=strict



  Routerlicious
    Alfred
      WebSockets
        Messages
          #connect_document
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            ✓ Should connect to and create a new interactive document on first connection
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            ✓ Should connect to and set existing flag to true when connecting to an existing document
          #disconnect
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            ✓ Should disconnect from an interactive document
          #submitOp
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"tenant orderer: {\"type\":\"kafka\",\"url\":\"http://test\"}"}
            ✓ Can connect to the web socket server
    storage
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"protocolTree {\"sha\":\"ea5e0f0f-5a6f-42ff-8a78-9cdbf1a73b84\",\"url\":\"\",\"tree\":[{\"mode\":\"100644\",\"path\":\"quorumMembers\",\"sha\":\"0637a088a01e8ddab3bf3fa98dbe804cbde1a0dc\",\"size\":0,\"type\":\"blob\",\"url\":\"\"},{\"mode\":\"100644\",\"path\":\"quorumProposals\",\"sha\":\"0637a088a01e8ddab3bf3fa98dbe804cbde1a0dc\",\"size\":0,\"type\":\"blob\",\"url\":\"\"},{\"mode\":\"100644\",\"path\":\"quorumValues\",\"sha\":\"95a5cd3624be83a3a654967fac6e8a79055f4882\",\"size\":0,\"type\":\"blob\",\"url\":\"\"},{\"mode\":\"100644\",\"path\":\"attributes\",\"sha\":\"c08fa99c0bae706e525ee64afbdcf901b1e993c1\",\"size\":0,\"type\":\"blob\",\"url\":\"\"}]}"}
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"appSummaryTree {\"sha\":\"eb870162-b1d8-4956-a02e-73a393996c92\",\"url\":\"\",\"tree\":[]}"}
[winston] Attempt to write logs with no transports {"messageMetaData":{"documentId":"test","tenantId":"test"},"level":"info","message":"commit sha: \"e1d37aa1-a0ca-496d-bb5f-6e52e4f0e5f0\""}
      ✓ create document with summary


  5 passing (22ms)

**Comment by tanviraumi** [comment]
Other than the tests, the PR is failing due to the moniker not found error. So that might be a lockfile issue. Can you try building a clean master and then apply your changes? A different version of node and npm can mess up the lockfile sometimes. My node version is v12.16.3 (same as Dockerfile) and npm version is 6.14.4.

If you get to a state where only tests are failing, we can bypass the tests in this PR and tackle it in an issue.

**Comment by christiango** [comment]
> Other than the tests, the PR is failing due to the moniker not found error. So that might be a lockfile issue. Can you try building a clean master and then apply your changes? A different version of node and npm can mess up the lockfile sometimes. My node version is v12.16.3 (same as Dockerfile) and npm version is 6.14.4.
> 
> If you get to a state where only tests are failing, we can bypass the tests in this PR and tackle it in an issue.

I've reverted the lockfiles back to the state where I didn't get the moniker issue

**Comment by christiango** [comment]
Moniker issue has been addressed. Is it ok to merge this now and start working on the client bits? How should we track the test issue?

**Comment by tanviraumi** [comment]
You need to bypass the tests as well. Adding @curtisman for recommendation on how to do that.

@curtisman : We have a problem where PR builds are failing on test for no apparent reason. This PR (https://github.com/microsoft/FluidFramework/pull/3983) is also failing with same errors. Any idea how to fix it? In the meantime, should we bypass tests for unblocking and tackle it on our end?

**Comment by christiango** [comment]
@curtisman any thoughts on how to unblock this PR? I've been fighting the build system for a few days now trying to make a relatively small change

**Comment by curtisman** [comment]
So there is a reference in the memory-orderer's package.json that maps moniker to the generateNames.js.
Since the file got moved, that needs to be updated as well.

**Comment by christiango** [comment]
> memory-orderer

Weird, is it an implicit dependency? I don't see it as an import

**Comment by christiango** [comment]
Actually @curtisman -  can you provide more info here on what you mean? The only file I moved was generateNames.ts which moved from server-client to server-utils. Moniker is not in the package.json for server-client, so not sure how that move could impact moniker.

What package.json do I need to modify?

**Comment by christiango** [comment]
Oh, I think I know what you mean, this thing: 

  "browser": {
    "moniker": "@fluidframework/server-services-client/dist/generateNames.js"
  },

**Comment by christiango** [comment]
Due to the nature of the dependency tree, I need to have a generate names in both server-client and server-utils. I simply copied the file, I think that's the least terrible option and it lets me reduce the entropy of this PR

**Comment by christiango** [comment]
I think the PR is building now, thanks everyone. Any final thoughts from reviewers? 

Would like to merge and start working on the client side bits if possible once the new server bits are published (need help with that)

**Review by anthony-murphy — APPROVED** [review]

**Comment by christiango** [comment]
Seems like the build status is still not updating, can someone help with that? I'll also need help getting the new server bits generated once this is merged

**Review by tanviraumi — APPROVED** [review]

**Comment by tanviraumi** [comment]
Looks like the Azure pipeline + github is still having outage.

**Comment by christiango** [comment]
> Looks like the Azure pipeline + github is still having outage.

So does this mean the PR is just blocked?

**Comment by tanviraumi** [comment]
So currently the pipelines are having an outage and we are still waiting for an update. I am bypassing the check and merging your changes manually. Once the build goes through, I will release your changes manually. Once that is done and packages are published in npm, I will let you know.

Rest is easy cause you are already publishing to 0.1014.0 and thats what the client consumes today. So you just have to delete the top level lerna-package-lock.json file and run npm install again. You should be able to see your changes reflected after that.

**Comment by tanviraumi** [comment]
Trying one last time to run it by closing and reopening your PR. If this does not work, I will force merge.

**Review by tanviraumi — APPROVED** [review]

**Comment by tanviraumi** [comment]
> Trying one last time to run it by closing and reopening your PR. If this does not work, I will force merge.

Looks like its working. I will merge as soon as the PR build passes.

**Comment by tanviraumi** [comment]
> Rest is easy cause you are already publishing to 0.1014.0-0 and thats what the client consumes today. So you just have to delete the top level lerna-package-lock.json file and run npm install again. You should be able to see your changes reflected after that.

It should be published now. So the above steps should work now

**Pull request merged**
