### PR TITLE
Remove line rate comparison for code coverage as that is not much useful due to comments

### PR DESCRIPTION
**Pull request by jatgarg**
## Description

[AB#23400](https://dev.azure.com/fluidframework/internal/_workitems/edit/23400)
Based on the feedback and analysis we are removing line rate comparison for code coverage as that is not much useful due to comments increasing and decreasing it based on whether the comments was in covered code or non-covered code.

### CODE REVIEW

**Review by alexvy86 — APPROVED** [review]
This bit looks fine. I suggest that we either remove the properties related to line coverage from `CodeCoverageComparison` or add notes to them saying we deliberately don't use them.

**Review by jatgarg — COMMENTED** [review]
## Code Coverage Summary

No packages impacted by the change.



<hr><p>Baseline commit: 9bdb9b5d606d9312f3679cf501edff5c8dd68537 <br>Baseline build: <a target="_blank" href=https://dev.azure.com/fluidframework/10f9b53e-c7fd-4538-9fff-13cd088a436c/_build/results?buildId=313948> 313948 </a><br> Happy Coding!!</p>

### Code coverage comparison check passed!!

**Review by jason-ha — COMMENTED** [review]
How is coverage reported for type only files with this change? They have 1 branch that is never covered? That happens all the time or some?
Definitely forward progress - just wondering what to expect.

**Review by jason-ha — APPROVED** [review]

**Comment by jatgarg** [comment]
> How is coverage reported for type only files with this change? They have 1 branch that is never covered? That happens all the time or some? Definitely forward progress - just wondering what to expect.

Removed line coverage in order to prevent that. From what I noticed, the types or declaration will not be counted a branch and therefore, that would not affect the code coverage. We will plan to add method coverage as well alongside branch coverage to make it more robust.

**Pull request merged**
