### PR TITLE
Upgrade socket.io-client to v3

### LINKED ISSUE #4608: Upgrade Fluid to latest version of socket.io-client
Socket.io released V3 recently. As a consumer of Fluid, I am not looking for any new features, but the new version of socket.io does update the versions of debug and ms that it uses to the latest versions, which makes it compatible with what Fluid Framework already requires.

Upgrading socket IO could resolve #4080

We should also update the duplicate package checker exception in the bundle tests package to remove all the socket.io specific overrides:
https://github.com/microsoft/FluidFramework/blob/955a4c77c7c4b29c66572097caf5818983b7ef25/examples/utils/bundle-size-tests/webpack.config.js#L50

### PR DESCRIPTION
**Pull request by christiango**
Socket.io-client v3 will (slightly) reduce bundle sizes downstream by removing the duplicate versions of ms/debug from consumers of Fluid.

We can remove references to @types/socket.io-client since it ships with TS types now.

Resolves #4608

### CODE REVIEW

**Comment by christiango** [comment]
@vladsud How good is the automation in FF these days? Do I have to manually test this in Fluid preview or is a clean buddy build sufficient?

**Comment by GaryWilber** [comment]
The fluid socket.io server is running with socket.io v2. Do you know if the v3 client is fully compatible with the v2 server? Curious if any protocol changes occurred.

**Comment by christiango** [comment]
> The fluid socket.io server is running with socket.io v2. Do you know if the v3 client is fully compatible with the v2 server? Curious if any protocol changes occurred.

Looks like it isn't :( https://socket.io/docs/v3/migrating-from-2-x-to-3-0/index.html. This is going to be hard to manage the upgrade if it's not compatible in either direction... 

I know I say this a lot, but I really don't like socket.io

**Comment by christiango** [comment]
I'm going to close due to the server incompatibility issue. We'll need ODSP and the runtime to coordinate a plan here if we want to upgrade

**Pull request closed without merging**
