### PR TITLE
IContainerContext removals

### PR DESCRIPTION
**Pull request by ChumpChief**
Followups from #16180 and #16182.  [AB#4879](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/4879)

### CODE REVIEW

**Comment by ChumpChief** [comment]
@tylerbutler the changes to UPCOMING.md look more dramatic than I expected - wanted to make sure I'm not doing something wrong here.

**Review by anthony-murphy — APPROVED** [review]

**Comment by ChumpChief** [comment]
Forgot that we can also remove the implementations here too, removed in latest.

**Comment by ChumpChief** [comment]
I see the policy check is running a "generate minor" but I think it's appropriate for it to instead generate major since this is targeting next branch?

**Comment by tylerbutler** [comment]
> I see the policy check is running a "generate minor" but I think it's appropriate for it to instead generate major since this is targeting next branch?

Working as expected right now, but it looks like next may have some unexpected changesets. I'll look more at it later, but once the latest main is merged (#16275), let's see what things look like.

**Comment by tylerbutler** [comment]
@ChumpChief Try merging the latest next into this PR; I think that should improve the UPCOMING.md situation, but I still need to figure out how to deal with main vs. next more generally.

**Comment by ChumpChief** [comment]
> @ChumpChief Try merging the latest next into this PR; I think that should improve the UPCOMING.md situation, but I still need to figure out how to deal with main vs. next more generally.

Merged latest, but I think UPCOMING.md looks wrong in current `next`, doesn't include all the major changes that have happened in `next`.  If I run the command with the major flag it looks more like I'd expect (including the changeset for this PR).

"generate:upcoming": "flub generate upcoming --releaseGroup client -t ~~minor~~ major"

**Comment by ChumpChief** [comment]
Tagging merge-next since I think the UPCOMING behavior is consistent with what's in `next` currently, but probably something to figure out there still.

**Comment by tylerbutler** [comment]
> "generate:upcoming": "flub generate upcoming --releaseGroup client -t ~minor~ major"

Yes, what you're describing is the expected behavior. UPCOMING.md always contains ONLY minor changes. That's what I meant by "figure out how to deal with main vs. next more generally."

**Pull request merged**
