### PR TITLE
refactor: Introduce message type pattern to better encapsulate boilerplate

### PR DESCRIPTION
**Pull request by Josmithr**
Refactors message type organization to better encapsulate type constraints without bloating the public API surface.

Follow-up to #14979

### CODE REVIEW

**Comment by Josmithr** [comment]
@alexvy86 Here is a sample direction we could take for message type encapsulation. We still have to declare boilerplate for each message type, but consumers don't have to import numerous API members. It also gives us a nice place to put type-safe factory functions.

And since namespaces don't provide any runtime behavior, I don't think this creates any new forwards / backwards compat complexities.

Interested in your thoughts.

**Comment by alexvy86** [comment]
I like it! I was thinking how it compares to just having standard polymorphism with an abstract `DevToolsMessage` class and children with their own type property, factory function, etc. I guess that would have a bit of overhead because message passing would have to reconstruct the instance on the receiving end after deserializing the messages? At least if we wanted to actually pass an instance of the class around, which might not be necessary today since these are basically POJOs with no functionality... but could pave the way for funky patterns and bugs down the road.

I'll do a bit more research on namespaces for my own education, to be able to discuss any potential implications. But overall I do like the idea.

**Comment by Josmithr** [comment]
@alexvy86 Currently, each of the message namespaces is exported separately, but we could potentially bundle all of them under a root "Messages" namespace to further scope them. Curious what your thoughts are.

**Review by alexvy86 — APPROVED** [review]
I didn't look at every single namespace file in detail; if we find some bug about a wrong message type used somewhere we can fix it then. 🚀 

I'll say, I was going to suggest maybe putting all the messages for an area in the same file, but then I saw the `container-devtools-messages` folder and that one would have been pretty long. I'm ok with this approach.

**Pull request merged**
