### PR TITLE
fix(version-tools): Detect bump types between RC builds and internal builds correctly

### PR DESCRIPTION
**Pull request by tylerbutler**
When comparing RC and internal builds, RC builds should be considered major bumps compared to internal builds. There may be further fixes needed, but this enables `flub release report` to work on the RC1 version.

### CODE REVIEW

**Review by jason-ha — APPROVED** [review]
We want to consider each prerelease compare individually as have them. Expect some not to be major?

**Comment by tylerbutler** [comment]
> We want to consider each prerelease compare individually as have them. Expect some not to be major?

Sorry, I don't know what you mean.

**Comment by jason-ha** [comment]
> > We want to consider each prerelease compare individually as have them. Expect some not to be major?
> 
> Sorry, I don't know what you mean.

I could see that any prereleaseId difference is major. But in logic we allow internal <=> rc, but otherwise error. So we want to visit all difference cases as we encounter them in the future?

**Comment by tylerbutler** [comment]
> > > We want to consider each prerelease compare individually as have them. Expect some not to be major?
> > 
> > 
> > Sorry, I don't know what you mean.
> 
> I could see that any prereleaseId difference is major. But in logic we allow internal <=> rc, but otherwise error. So we want to visit all difference cases as we encounter them in the future?

Ahhh, yes, my general approach is to be very narrow with the assumptions and error out if we find ourselves trying to compare versions of "kinds" that we don't understand. If a version like 2.0.0-foo.4.1.2 shows up somehow, this function doesn't and shouldn't know what to do with it. But in order for that to happen, the version would need to be interpreted as an internal version, which should only be the rc and internal prerelease IDs. So it shouldn't happen. But if someone adds a new prerelease ID that we consider internal, then yes, this code would need to be updated too. I think that's safer than being more general in the logic.

**Comment by tylerbutler** [comment]
Thanks for the review, @jason-ha!

**Pull request merged**
