### PR TITLE
refactor(client-debugger): Add the ability to specify explicit message types in `MessageRelay`'s `postMessage` method

### PR DESCRIPTION
**Pull request by Josmithr**
Affords extra type-safety when posting messages defined (untyped) inline. 

Also update usages to specify explicit type parameters.

### CODE REVIEW

**Review by alexvy86 — APPROVED** [review]
I'd love to not have to provide the type property on each call if we can specify the generic type for the method but not sure if we can in a clean way... `Omit<>` could be part of it, but then all implementations of `IMessageRelay` would need to add it with a big `switch`?

**Comment by Josmithr** [comment]
> I'd love to not have to provide the type property on each call if we can specify the generic type for the method but not sure if we can in a clean way... `Omit<>` could be part of it, but then all implementations of `IMessageRelay` would need to add it with a big `switch`?

As implemented, it isn't strictly required to specify the argument if the compiler can determine the type statically. The type specification should only be required if the type can't be determined. This should only be for inline object declarations, which was the primary case I was hoping to catch. I added the types everywhere for paranoid completeness, but there are a few places where it wasn't strictly necessary.

If we take the approach I started prototyping in #14988 for creating the message types, we should no longer need to specify in most places.

**Comment by alexvy86** [comment]
> As implemented, it isn't strictly required to specify the argument if the compiler can determine the type statically. The type specification should only be required if the type can't be determined. This should only be for inline object declarations, which was the primary case I was hoping to catch. I added the types everywhere for paranoid completeness, but there are a few places where it wasn't strictly necessary.

Oh, really? The transpiler adds the type field in the generated JS so it exists at runtime if we define the object directly in the "argument slot" of the method call? That's nice if it works that way.

**Comment by Josmithr** [comment]
> > As implemented, it isn't strictly required to specify the argument if the compiler can determine the type statically. The type specification should only be required if the type can't be determined. This should only be for inline object declarations, which was the primary case I was hoping to catch. I added the types everywhere for paranoid completeness, but there are a few places where it wasn't strictly necessary.
> 
> Oh, really? The transpiler adds the type field in the generated JS so it exists at runtime if we define the object directly in the "argument slot" of the method call? That's nice if it works that way.

I'm not sure I understand what you mean.

Examples of what I mean:

**Works**
```typescript
const message: FooMessage = {...};
relay.postMessage(message);
```

**Works**
```typescript
const message = createFooMessage(); // Returns value of type FooMessage
relay.postMessage(message);
```

**Doesn't work**
```typescript
relay.postMessage({
    type: "Foo",
    data: {...},
});
```

**Comment by alexvy86** [comment]
Ah, got you, I misunderstood earlier.

I was thinking of being able to not specify the `type` property when doing this:

```typescript
relay.postMessage<FooMessage>({
    data: {...},
});
```

That's why I jumped to "TS transpiling would realize that the inline object is missing `type` and put it there?", but I now realize it wouldn't work, that sample code would just complain that the object is not really a `FooMessage` because of the missing property. Plus, the messages are not a discriminated union, so it wouldn't be able to figure out the value for `type` just from `FooMessage` (which also means that right now the compiler won't prevent us from potentially introducing a bug where we give two messages the same `type` value by mistake).

The current direction seems fine 👍 .

**Pull request merged**
