### PR TITLE
Couple the client build and test stability pipeline

### PR DESCRIPTION
**Pull request by clarenceli-msft**
[AB#4808](https://dev.azure.com/fluidframework/internal/_workitems/edit/4808)

Since the client build pipeline yaml file is updated frequently, there is a high risk of breaking the test stability pipeline due to the async changes in Install/Build/Test steps. Moving the overlapped/shared parts to separate template files will help to forcibly keep them in sync and reduce future overhead.

The Test Stability pipeline with this update was run successfully on the personal test branch: https://dev.azure.com/fluidframework/internal/_build/results?buildId=180300&view=results

### CODE REVIEW

**Review by alexvy86 — COMMENTED** [review]
One comment below; and it'd be good to validate that Build - client packages also runs successfully in your branch.

**Comment by tylerbutler** [comment]
@clarenceli-msft when I make a change to the client build, how do I know that I haven't broken the test stability pipeline? Is it triggered by PRs?

**Comment by clarenceli-msft** [comment]
> @clarenceli-msft when I make a change to the client build, how do I know that I haven't broken the test stability pipeline? Is it triggered by PRs?

It will not be triggered by PRs since it runs the building and test for 100 times, which would occupy all agents and block other pipeline runs. Apart from the weekly run scheduled during weekends, it is only executed manually on personal test branch (with running times reduced)

**Comment by scarlettjlee** [comment]
> > @clarenceli-msft when I make a change to the client build, how do I know that I haven't broken the test stability pipeline? Is it triggered by PRs?
> 
> It will not be triggered by PRs since it runs the building and test for 100 times, which would occupy all agents and block other pipeline runs. Apart from the weekly run scheduled during weekends, it is only executed manually on personal test branch (with running times reduced)

The intent here is an incremental improvement. If we want [better] automatic validation when making changes, we could consider making the iteration count configurable and running a 1x (instead of usual 100x) run triggered by changes to these files. I'm inclined to wait and see if that's needed (i.e. weekly weekend run is too much latency to catch breaks or OCE is to busy too look). Engineers can manually run this pipeline against their changes (optionally reducing the count) as a best practice.

**Review by scarlettjlee — APPROVED** [review]

**Pull request merged**
