### PR TITLE
Move TelemetryNullLogger to telemetry-utils

### PR DESCRIPTION
**Pull request by ChumpChief**
Doesn't seem to make sense for this single logger to live in common-utils -- moving this will make it easier to find and consolidate related code, and I think it aligns with the similar movement in #9016.  This change would also update all existing imports in our repo in preparation for the eventual removal.

### CODE REVIEW

**Comment by tylerbutler** [comment]
@ChumpChief any idea why this causes a bundle size increase?

**Comment by ChumpChief** [comment]
> @ChumpChief any idea why this causes a bundle size increase?

I think it's wrong about the baseline size?  Running the bundle-size-tests locally I see the same sizes both with and without my change (generally the larger number, i.e. map.js is 47.38KB).  I see that PR #11480 had the same claims of bundle size growth that also don't make sense to me.

**Comment by ChumpChief** [comment]
> > @ChumpChief any idea why this causes a bundle size increase?
> 
> I think it's wrong about the baseline size? Running the bundle-size-tests locally I see the same sizes both with and without my change (generally the larger number, i.e. map.js is 47.38KB). I see that PR #11480 had the same claims of bundle size growth that also don't make sense to me.

Looked into this a bit more - it appears to be comparing against main rather than next.  So the bundle size change is already in next, and the comparison bot is making incorrect comparisons.

**Comment by ChumpChief** [comment]
In particular, this looks to be the problematic bit.  Presumably needs to differentiate which comparison commit based on target branch.
https://github.com/microsoft/FluidFramework/blob/main/tools/bundle-size-tools/src/utilities/gitCommands.ts#L12

**Comment by ChumpChief** [comment]
Filed AB#1570

**Review by tylerbutler — APPROVED** [review]

**Pull request merged**
