### PR TITLE
0.27.5-0.27.6 Client Package Bump

### PR DESCRIPTION
**Pull request by skylerjokiel**
Bump the client package so we can deploy a new version

### CODE REVIEW

**Review by ksbrar — APPROVED** [review]

**Comment by curtisman** [comment]
repo-policy-check is failing: https://dev.azure.com/fluidframework/public/_build/results?buildId=7691&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=baa7d181-d9ee-513a-8016-f44a98fd040e&l=218

**Comment by ksbrar** [comment]
> repo-policy-check is failing: [dev.azure.com/fluidframework/public/_build/results?buildId=7691&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=baa7d181-d9ee-513a-8016-f44a98fd040e&l=218](https://dev.azure.com/fluidframework/public/_build/results?buildId=7691&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=baa7d181-d9ee-513a-8016-f44a98fd040e&l=218)

Package-lock and lerna-package-lock were accidentally included, just removed them.

**Comment by ksbrar** [comment]
Successful policy-check run now: https://dev.azure.com/fluidframework/public/_build/results?buildId=7699&view=results

**Comment by ksbrar** [comment]
Successful packages build as well: https://dev.azure.com/fluidframework/public/_build/results?buildId=7700&view=results

**Pull request merged**
