### PR TITLE
fix(build-tools): Run install with `--no-frozen-lockfile`

### PR DESCRIPTION
**Pull request by tylerbutler**
We recently updated the pnpm config in the repo to do a lockfile-only install by default. This updates the build tools to pass the `--no-frozen-lockfile` flag when installing, so the lockfile will be updated if needed.

### CODE REVIEW

**Review by alexvy86 — APPROVED** [review]
Curious: when are these used? I'm surprised no obvious failures (that I know of) prompted us to update these sooner.

**Review by jason-ha — COMMENTED** [review]
Are there situations when we don't need unfrozen lockfile?
It would be cool if we aren't sure if we tried first with frozen and then only use unfrozen when needed. It is possible for updates to be made even if none are strictly required. pnpm is pretty good but not perfect.

**Comment by tylerbutler** [comment]
> Curious: when are these used? I'm surprised no obvious failures (that I know of) prompted us to update these sooner.

The main place is in the release tools where we check that the correct dependencies are installed at various points. Scenario is: I just switched to an old release branch to do a patch, but forgot to install, so my local env isn't really valid because deps are missing and/or the wrong version.

It's also called in `fluid-build --install`, but few people use that.

**Comment by tylerbutler** [comment]
> Are there situations when we don't need unfrozen lockfile? It would be cool if we aren't sure if we tried first with frozen and then only use unfrozen when needed. It is possible for updates to be made even if none are strictly required. pnpm is pretty good but not perfect.

There are times we don't expect to need a lockfile update, yes. But much of the calling code expects it to do a lockfile update if needed. This is something that is addressed in the in-progress build-infrastructure, which is one reason I'm leaving this change as minimal as possible. The new install function takes a bool controlling whether a lockfile update is expected, so the caller has to be explicit. If they're not expecting a lockfile update then the functions will throw and the calling code is expected to handle it.

`install(updateLockfile: boolean): Promise<boolean>;`

**Pull request merged**
