### PR TITLE
Website CTAs: use hover styles when focusing to avoid inaccessible text 

### PR DESCRIPTION
**Pull request by micahgodbolt**
Focus Before:

image

image

Focus After:

image

image

### CODE REVIEW

**Comment by tylerbutler** [comment]
@micahgodbolt Can you check if this corresponds to one of the issues and link it if so?

**Comment by micahgodbolt** [comment]
I didn't see anything under "focus" or "area: website".

**Comment by micahgodbolt** [comment]
I don't believe any of the automated tests catch focus styles. so #3816 i'm assuming is only looking at the default link styles in the bottom chunk of the page

**Review by tylerbutler — APPROVED** [review]
Forgot to approve earlier!

**Pull request merged**
