### PR TITLE
Updated exported members of devtools and devtools-core to beta

### PR DESCRIPTION
**Pull request by WayneFerrao**
[AB#6559](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/6559)

## Description

 This PR updates the exported members of the `@fluidframework/devtools` package and marks them as `@beta`. Relevant exports from devtools-core were also marked as beta.

### CODE REVIEW

**Review by alexvy86 — COMMENTED** [review]
These changes look correct but I think we're missing some things... @Josmithr the `initializeDevtools` function in devtools-core (and anything it transitively needs) should be @beta as well, right?

**Review by Josmithr — APPROVED** [review]

**Comment by Josmithr** [comment]
> These changes look correct but I think we're missing some things... @Josmithr the `initializeDevtools` function in devtools-core (and anything it transitively needs) should be @beta as well, right?

No, the `devtools` package has its own `initializeDevtools` function that takes a config including an `IFluidContainer`. It calls the counterpart function in `devtools-core`, but strictly as an implementation detail. That part of the API shouldn't need to be exposed yet. At least not until we're ready for users to engage with `devtools-core` directly.

**Comment by alexvy86** [comment]
I thought consumers using IContainer & co (vs azure-client/IFluidContainer) would need to use devtools-core and this is their only entrypoint to Fluid Devtools... is that not the case?

**Review by Josmithr — APPROVED** [review]
🚀

**Pull request merged**
