### PR TITLE
bug fix for Historian not logging correlation id

### PR DESCRIPTION
**Pull request by PingZhu2232**
Doing a bug fix to pass correlation id to winston as a property in messageMetaData since Historian/Gitrest use different AsyncLocalStorage instances from routerlicious.

### CODE REVIEW

**Review by tanviraumi — COMMENTED** [review]
Why are the lockfiles changing?

**Comment by PingZhu2232** [comment]
> Why are the lockfiles changing?

For lerna-package-lock.json, some drivers have devDependency @types/node ^10.17.24 and are automatically upgraded from 12.19.13 to 12.19.14. For package.json in Historian, it changes integrity from sha1 to sha512. This looks like an issue with npm ([ref1](https://github.com/npm/npm/issues/17749), [ref2](https://stackoverflow.com/questions/47638381/why-did-package-lock-json-change-the-integrity-hash-from-sha1-to-sha512)). Do we want to keep the old ones?

**Review by znewton — COMMENTED** [review]
Not sure how I feel about this workaround. To add some context for @tanviraumi and others, the reason this PR exists is because our team is consuming historian-base in a location that uses private fluidframework package versions, while historian-base uses public versions. This leads to the `AsyncLocalStorage` instance used in `bindCorrelationId()` to be different than the `AsyncLocalStorage` instance used in our service's winston transport which calls `getCorrelationId()` from the private package version.

It seems our service's package conflicts are causing this, and therefore we shouldn't unnecessarily pollute the historian and gitrest codebase with all these getCommonMessageMetaData calls. I also don't believe this workaround scales well.

Perhaps, instead, we should have the `AsyncLocalStorage` instance passed into getCorrelationId and bindCorrelationId functions, rather than having that module instantiate the instance itself?

**Comment by tanviraumi** [comment]
> Perhaps, instead, we should have the AsyncLocalStorage instance passed into getCorrelationId and bindCorrelationId functions, rather than having that module instantiate the instance itself?

This sounds like a better solution.

**Comment by PingZhu2232** [comment]
> Not sure how I feel about this workaround. To add some context for @tanviraumi and others, the reason this PR exists is because our team is consuming historian-base in a location that uses private fluidframework package versions, while historian-base uses public versions. This leads to the `AsyncLocalStorage` instance used in `bindCorrelationId()` to be different than the `AsyncLocalStorage` instance used in our service's winston transport which calls `getCorrelationId()` from the private package version.
> 
> It seems our service's package conflicts are causing this, and therefore we shouldn't unnecessarily pollute the historian and gitrest codebase with all these getCommonMessageMetaData calls. I also don't believe this workaround scales well.
> 
> Perhaps, instead, we should have the `AsyncLocalStorage` instance passed into getCorrelationId and bindCorrelationId functions, rather than having that module instantiate the instance itself?

I agree this is not an elegant solution. For passing into getCorrelationId and bingCorrelationId, could you talk more about how we can initiate and pass AsyncLocalStorage instance through different packages?

**Comment by znewton** [comment]
> could you talk more about how we can initiate and pass AsyncLocalStorage instance through different packages?

Something like this: [Passing AsyncLocalStorage instance through nconf](https://gist.github.com/znewton/e0fadcab43bd701487a8011d4caafb6e)

The trick for passing complex objects via nconf is to wrap it in an array. This would allow you to create your own AsyncLocalStorage instance in our services' `www.ts` files before running `utils.RunService`, while keeping the currently elegant approach mostly the same aside from passing the AsyncLocalStorage instance into the bindCorrelationId middleware in Historian's `app.ts`. For consistency, you might also want to duplicate this process for Routerlicious

**Pull request closed without merging**
