### PR TITLE
Dev Container: Install dependencies for Puppeteer

### PR DESCRIPTION
**Pull request by DLehenbauer**
Installs required Debian packages for running Puppeteer tests (e.g., 'examples/data-objects/diceRoller')

Headless Chrome depends on some *.so files that are commonly omitted from headless Linux installations.

### CODE REVIEW

**Review by ksbrar — APPROVED** [review]
1st approve 3x champ, ha

**Comment by DLehenbauer** [comment]
Thanks, @ksbrar!

**Review by tanviraumi — APPROVED** [review]

**Comment by curtisman** [comment]
The change looks good.  I am curious how you come up with the list of dependencies.

**Comment by DLehenbauer** [comment]
@curtisman - I did it the tedious way: I ran 'npm run test' seventeen times and looked up each missing *.so file on https://packages.debian.org/.  :-)

(It probably would have been smarter to find a trusted working container on DockerHub and examine the DockerFile.)

**Comment by curtisman** [comment]
@DLehenbauer I was wondering because I had to deal with it with our CI VM's.   I went the lazy way out and just find the version of chrome that puppeteer uses and install it, which also installs the dependencies :)

**Pull request merged**
