### PR TITLE
Remove usage of addView on the Math component in flow-scroll

### PR DESCRIPTION
**Pull request by ChumpChief**
The Math component is interesting because it's the only one that uses the `scope` from `addView`.  This PR represents step 1 from #1042, and does a couple things:

1. It creates `MathView`s without routing through the `MathInstance`.  This is important in opening the door for alternate view components to be used, and for allowing `MathInstance` to become a purely model component.  It does this by registering a request handler on the container, very similar to what I did in #767.
2. It extracts the passing of scope to be separate from `addView`.  I think this separation is conceptually appropriate (since any component may wish to receive scope from its host, not just view components), though I'm still somewhat uncomfortable with the loose typing of the "scope" concept -- it's difficult to norm on what should really be passed here between both the scope-taker and scope-giver in a universal way.  I'd be happier if/when we come up with a stronger contract.

Cross-linking #1078 as well.

### CODE REVIEW

**Review by skylerjokiel — APPROVED** [review]
:shipit:

**Review by curtisman — APPROVED** [review]
:shipit:

**Review by kurtb — CHANGES_REQUESTED** [review]
I still don't understand what the replacement for `addView` is that continues to provide the scope capability. Until we have something I think it's too early to deprecate it.

The view factory doesn't seem to have gone away in this new world but we've forced the user to do independent URL requests in order to gain multiple views. And there's no way to to indicate context or intent as part of that where there was this before. An explicit set call seems to complicate the API more since it provides multiple bind opportunities rather than the expected one.

It also seems like you can still get at experimenting with just having render without needing to go full deprecation.

It might be worth meeting in person to go over the API design. I'm fine with experimenting on a subset of components to learn about the design space. A good amount of time went into the current set of rendering interfaces. Although I'm sure they need work it feels like we're rushing to replace them without having guidance for replacements for aspects of the existing design.

**Review by DLehenbauer — APPROVED** [review]
Seems like a reasonable first step.

**Review by skylerjokiel — APPROVED** [review]
👍

**Review by kurtb — APPROVED** [review]

**Pull request merged**
