### PR TITLE
build: Use .cjs file extension with CJS jest configs

### PR DESCRIPTION
**Pull request by tylerbutler**
Renames all the Jest config files to use the .cjs file extension. This will make it easier to add type: module to ESM-only packages.

I used these commands to do the bulk of the work:

```shell
fd --glob "**/jest*.config.js" --hidden --exec mv {} {.}.cjs
fd --extension test.ts --exec sd --fixed-strings 'jest.config";' 'jest.config.cjs";'
```

### CODE REVIEW

**Review by jason-ha — APPROVED** [review]
Looking good.

**Comment by jason-ha** [comment]
Heh. It was too good. Still good for me.

**Comment by tylerbutler** [comment]
Reverted the common-utils changes since that package is deprecated and hopefully will just go away before we MUST do something. I'll just exclude it from the no-js policy.

**Review by jikim-msft — APPROVED** [review]

**Pull request merged**
