### PR TITLE
r11s-driver: implement persistent caching for RestLess HTTP requests

### PR DESCRIPTION
**Pull request by znewton**
RestLess requests are not compatible with Browsers' built-in cache because they are all POST requests. We can use IndexedDB to replace the built-in browser cache when needed.

Bonus: previous additions of in-memory cache were a bit haphazard and not well-thought-out. This PR also cleans those up.

### CODE REVIEW

**Comment by vladsud** [comment]
Somewhat similar topic popped up for ODSP, and internet suggests that POSTs could be cached. Not clear if it's browser specific, etc. Have you had chance to look into it (and conclude that's not possible / not an option)?

**Comment by vladsud** [comment]
It would be great to have a mini spec describing this feature.
Some questions:
1. Do we give control to hosts re indexDB caching? What is the implication for user leveraging Fluid app on public PC? The min requirement I've heard is that when user logs out, all cached data should be deleted. Do we provide right documentation and tools for app developers to be able to do so?
2. You will likely need ability to clear all cache info for a file. It's not a big issue if all the content stored there is content addressable, but if not, you are likely to find yourself in a situation in future where file was overwritten / reset (let's say due to data center fall-over / restore) where cache needs to be reset.
3. Hosts should be able to provide their own implementation of caching interface. I do not remember the details, but Fluid/ODSP users on iOS/Android (I believe) want to use their own storage (assuming usage of WebView to run JS code).
4. In practice, we are finding that indexDB perf is all over the place. For example, please see https://github.com/microsoft/FluidFramework/issues/9177, where we see doing rest call is actually faster in many cases than getting data from indexDB. We do not fully yet understand these cases, but data suggests indexDB can be terribly slow (likely if CPU is overscheduled / other players on machine use indexDB).

**Comment by znewton** [comment]
> Somewhat similar topic popped up for ODSP, and internet suggests that POSTs could be cached. Not clear if it's browser specific, etc. Have you had chance to look into it (and conclude that's not possible / not an option)?

Yes, I had looked into this before when implementing RestLess because I was really hoping I wouldn't have to implement manual caching (especially for Shredded summaries w/ Git storage where everything is content addressable by URL). Technically, the response of a POST request _is_ cacheable, however, in order to access the cached resource, the next request  to that resource would have to be a GET, so we would still need to implement some method for storing and retrieving information about what has been cached so that we can disable RestLess for any follow-up requests to that resource. That seemed like as much or more effort than just implementing a manual cache, especially since the manual cache would be extensible for non-content-addressable resources (e.g. WholeSummaries w/ Antler/PragueGraph).

**Comment by znewton** [comment]
@vladsud I found [this article about IndexedDB performance](https://rxdb.info/slow-indexeddb.html) saying that "many small transactions" is slow, while "few large transactions" is fast. This article links to some of the resources you mentioned in #9177, and seems to line up with what you're saying about many transactions for reads being a problem. I'm wondering if leveraging `idb-keyval`'s [getMany()](https://github.com/jakearchibald/idb-keyval#getmany) method for specific scenarios (ops and summary-blobs caches) where we know many requests will likely happen in quick succession. Thoughts?

**Comment by vladsud** [comment]
I do not have much info here, other than what's shared above. in ODSP stack we basically try to (as much as possible) push decisions for some of these problems to hosts that use us. I.e. we ask to provide cache implementation (object implementing some small interface), but defer all the management and concerts to hosts, and some of the things I shared re public PC usage is what I've heard from Bohemia. @AndreiZe might be right person to chat about security / privacy aspects here.

in ODSP stack the problem that caused us to re-evaluate it is slightly different - it's usage of tokens in query parameters and push back from clients that it's less secure than alternatives. We are evaluating switching to POST or GET with OPTIONS calls. I think the latter is what we will chose, especially for calls that are cachable (like blob reads)

**Comment by znewton** [comment]
Closing this to take a different approach in a future PR when this can be prioritized again. Thanks Vlad for all the feedback and info offline!

**Pull request closed without merging**
